package xolova.blued00r.divinerpg.client.misc;

public class Sounds
{
    //private static final String SOUND_RESOURCE_LOCATION = "DivineRPG/sounds/";
    private static final String mobDirectory = "mob/RPG/";
    private static final String divinerpg = "xolovon/";
    private static final String biomeMusic = "biomemusic/";
    private static final String blockSounds = "blocks/";
    private static final String ambientSounds = "ambient/";
    

    public static String[] soundFiles =
    {
    	blockSounds + "ArcanaPortal.ogg",
    	
    	divinerpg + "phaser.ogg",
        divinerpg + "blitz.ogg",
        divinerpg + "serenade.ogg",
        divinerpg + "Frostcannon.ogg",
        divinerpg + "GhastCannon.ogg",
        divinerpg + "HealingStone.ogg",
        divinerpg + "maelstrom.ogg",
        divinerpg + "SoundOfMusic.ogg",
        divinerpg + "Starlight.ogg",
        divinerpg + "KarOTsummon.ogg",
        divinerpg + "Firefly.ogg",
        divinerpg + "deeplaugh.ogg",
        divinerpg + "Reflector.ogg",
        divinerpg + "ArcaniumSaber.ogg",
        divinerpg + "MeriksMissile.ogg",
        divinerpg + "ShadowSaber.ogg",
        divinerpg + "Sparkler.ogg",
        divinerpg + "LaVekor.ogg",
        divinerpg + "EnderScepter.ogg",
        divinerpg + "EnderScepter1.ogg",
        
        divinerpg + "FractiteCannon.ogg",
        divinerpg + "FrostclawCannon.ogg",
        
        divinerpg + "DramixSpawn.ogg",
        divinerpg + "ParasectaSpawn.ogg",
        divinerpg + "SoundOfCarols.ogg",
        
        mobDirectory + "Cyclops.ogg",
        mobDirectory + "Frost.ogg",
        mobDirectory + "Iceman.ogg",
        mobDirectory + "roar.ogg",
        mobDirectory + "Cadillion.ogg",
        mobDirectory + "Insect.ogg",
        mobDirectory + "CyclopsHit.ogg",
        mobDirectory + "IcemanHit.ogg",
        mobDirectory + "JungleSpider.ogg",
        mobDirectory + "Scorcher.ogg",
        mobDirectory + "Hellspider.ogg",
        mobDirectory + "whale.ogg",
        mobDirectory + "whalehurt.ogg",
        mobDirectory + "crab.ogg",
        mobDirectory + "crabhurt.ogg",
        mobDirectory + "shark.ogg",
        mobDirectory + "sharkhurt.ogg",
        mobDirectory + "buzz.ogg",
        mobDirectory + "croak.ogg",
        mobDirectory + "DemonOfDarkness.ogg",
        mobDirectory + "Golem.ogg",
        mobDirectory + "growl.ogg",
        mobDirectory + "growlhit.ogg",
        mobDirectory + "high.ogg",
        mobDirectory + "highHit.ogg",
        mobDirectory + "hiss.ogg",
        mobDirectory + "merchantsound.ogg",
        mobDirectory + "Mucky.ogg",
        mobDirectory + "nesro.ogg",
        mobDirectory + "rowl.ogg",
        mobDirectory + "Deathcryx.ogg",
        mobDirectory + "DeathCryxHit.ogg",
        mobDirectory + "DeathHound.ogg",
        mobDirectory + "DeathHoundHit.ogg",
        mobDirectory + "DungeonPrisoner.ogg",
        mobDirectory + "DungeonPrisonerHit.ogg",
        mobDirectory + "DungeonDemon.ogg",
        mobDirectory + "Roamer.ogg",
        mobDirectory + "RoamerHit.ogg",
        mobDirectory + "buzz.ogg",
        mobDirectory + "Cadillion.ogg",
        mobDirectory + "AridWarrior.ogg",
        mobDirectory + "AridWarriorHit.ogg",
        mobDirectory + "Crawler.ogg",
        mobDirectory + "CrawlerHit.ogg",
        mobDirectory + "Dramcryx.ogg",
        mobDirectory + "DramcryxHit.ogg",
        mobDirectory + "Rotatick.ogg",
        mobDirectory + "RotatickHit.ogg",
        mobDirectory + "TheEye.ogg",
        mobDirectory + "TheEyeHit.ogg",
        
        mobDirectory + "Alicanto.ogg",
        mobDirectory + "AlicantoHit.ogg",
        mobDirectory + "Rollum.ogg",
        mobDirectory + "RollumHit.ogg",
        mobDirectory + "Hastreus.ogg",
        mobDirectory + "HastreusHit.ogg",
        mobDirectory + "Glacide.ogg",
        mobDirectory + "GlacideHit.ogg",
        mobDirectory + "Fractite.ogg",
        mobDirectory + "FractiteHit.ogg",
        mobDirectory + "Razorback.ogg",
        mobDirectory + "RazorbackHit.ogg",
        
        mobDirectory + "Wraith.ogg",
        mobDirectory + "WraithHit.ogg",
        mobDirectory + "Parasecta.ogg",
        mobDirectory + "ParasectaHit.ogg",
        mobDirectory + "Dramix.ogg",
        mobDirectory + "DramixHit.ogg",
        mobDirectory + "Golem.ogg",
        mobDirectory + "Archer.ogg",
        mobDirectory + "DungeonPrisonerChange.ogg",
        
        mobDirectory + "Enderspider.ogg",
        mobDirectory + "Rainbour.ogg",
        mobDirectory + "RainbourHit.ogg",
        mobDirectory + "coriHit.ogg",
        mobDirectory + "coriIdle.ogg",
        mobDirectory + "coriShoot.ogg",
        mobDirectory + "dungeonConstructorHit.ogg",
        mobDirectory + "dungeonConstructorPunch.ogg",
        mobDirectory + "kingScorcher.ogg",
        mobDirectory + "kingScorcherHit.ogg",
        mobDirectory + "Wildfire.ogg",
        mobDirectory + "WildfireHit.ogg",

        mobDirectory + "Densos.ogg",
        mobDirectory + "DensosHit.ogg",
        mobDirectory + "Dex.ogg",
        mobDirectory + "DexHit.ogg",
        mobDirectory + "Reyvor.ogg",
        mobDirectory + "ReyvorHit.ogg",
        mobDirectory + "Zichile.ogg",
        mobDirectory + "ZichileHit.ogg",
        mobDirectory + "KarOTsummon.ogg",
        
        mobDirectory + "AncientEntitySpawn.ogg",
        mobDirectory + "DensosReyvorSpawn.ogg",
        mobDirectory + "DexZichileSpawn.ogg",
        mobDirectory + "KarotSpawn.ogg",
        mobDirectory + "ScorcherKingSpawn.ogg",
        mobDirectory + "SoulFiendSpawn.ogg",
        mobDirectory + "TwilightDemonSpawn.ogg",
        mobDirectory + "VamacheronSpawn.ogg",
        mobDirectory + "WatcherSpawn.ogg",

        mobDirectory + "Ayeraco.ogg",
        mobDirectory + "AyeracoHalfHealth.ogg",
        mobDirectory + "AyeracoHit.ogg",
        mobDirectory + "AyeracoPillar.ogg",
        mobDirectory + "AyeracoSpawn.ogg",
        mobDirectory + "AyeracoTeleport.ogg",

        mobDirectory + "BunnyHit.ogg",
        mobDirectory + "Varek.ogg",
        mobDirectory + "VarekHit.ogg",
        mobDirectory + "madivel.ogg",
        mobDirectory + "madivalHit.ogg",
        mobDirectory + "NesroHit.ogg",
        mobDirectory + "kingScorcher.ogg",
        mobDirectory + "kingScorcherHit.ogg",
        
        divinerpg + "ArcanaPortal.ogg",
        divinerpg + "DravitePortal.ogg",
        divinerpg + "AzuritePortal.ogg",
        divinerpg + "UvitePortal.ogg",
        divinerpg + "MythrilPortal.ogg",
        divinerpg + "AugitePortal.ogg",
        divinerpg + "IceikaPortal.ogg",
        
        biomeMusic + "Augite.ogg",
        biomeMusic + "Azurite.ogg",
        biomeMusic + "Desert.ogg",
        biomeMusic + "Dravite.ogg",
        biomeMusic + "End.ogg",
        biomeMusic + "Grass.ogg",
        biomeMusic + "Jungle.ogg",
        biomeMusic + "MushoomBiomes.ogg",
        biomeMusic + "Mythril.ogg",
        biomeMusic + "Nether.ogg",
        biomeMusic + "Ocean.ogg",
        biomeMusic + "Snowbiomes.ogg",
        biomeMusic + "Swamp.ogg",
        biomeMusic + "Uvite.ogg",
        
        ambientSounds + "Arcana.ogg"
        
               
        
    };
}
