package net.divinerpg.utils.helpers.render;

import net.divinerpg.entities.vethea.mobs.EntityAcidHag;
import net.divinerpg.entities.vethea.mobs.EntityBiphron;
import net.divinerpg.entities.vethea.mobs.EntityBohemite;
import net.divinerpg.entities.vethea.mobs.EntityCryptKeeper;
import net.divinerpg.entities.vethea.mobs.EntityCymesoid;
import net.divinerpg.entities.vethea.mobs.EntityDissiment;
import net.divinerpg.entities.vethea.mobs.EntityDreamwrecker;
import net.divinerpg.entities.vethea.mobs.EntityDuo;
import net.divinerpg.entities.vethea.mobs.EntityEhu;
import net.divinerpg.entities.vethea.mobs.EntityEndiku;
import net.divinerpg.entities.vethea.mobs.EntityEnt;
import net.divinerpg.entities.vethea.mobs.EntityGalroid;
import net.divinerpg.entities.vethea.mobs.EntityGorgosion;
import net.divinerpg.entities.vethea.mobs.EntityHelio;
import net.divinerpg.entities.vethea.mobs.EntityHerbomancer;
import net.divinerpg.entities.vethea.mobs.EntityHiveQueen;
import net.divinerpg.entities.vethea.mobs.EntityHiveSoldier;
import net.divinerpg.entities.vethea.mobs.EntityHoverStinger;
import net.divinerpg.entities.vethea.mobs.EntityHungerHungry;
import net.divinerpg.entities.vethea.mobs.EntityHusk;
import net.divinerpg.entities.vethea.mobs.EntityKaros;
import net.divinerpg.entities.vethea.mobs.EntityKazrotic;
import net.divinerpg.entities.vethea.mobs.EntityLadyLuna;
import net.divinerpg.entities.vethea.mobs.EntityLheiva;
import net.divinerpg.entities.vethea.mobs.EntityLorga;
import net.divinerpg.entities.vethea.mobs.EntityLorgaFlight;
import net.divinerpg.entities.vethea.mobs.EntityMandragora;
import net.divinerpg.entities.vethea.mobs.EntityMysteriousManLayer1;
import net.divinerpg.entities.vethea.mobs.EntityMysteriousManLayer2;
import net.divinerpg.entities.vethea.mobs.EntityMysteriousManLayer3;
import net.divinerpg.entities.vethea.mobs.EntityQuadro;
import net.divinerpg.entities.vethea.mobs.EntityRaglok;
import net.divinerpg.entities.vethea.mobs.EntityShadahier;
import net.divinerpg.entities.vethea.mobs.EntitySpinebackWorm;
import net.divinerpg.entities.vethea.mobs.EntitySpinebackWormBody;
import net.divinerpg.entities.vethea.mobs.EntityStoneGolem;
import net.divinerpg.entities.vethea.mobs.EntityTempleGuardian;
import net.divinerpg.entities.vethea.mobs.EntityTocaxin;
import net.divinerpg.entities.vethea.mobs.EntityTwins;
import net.divinerpg.entities.vethea.mobs.EntityVermenous;
import net.divinerpg.entities.vethea.mobs.EntityVermsillion;
import net.divinerpg.entities.vethea.mobs.EntityVhraak;
import net.divinerpg.entities.vethea.mobs.EntityWreck;
import net.divinerpg.entities.vethea.mobs.EntityZone;
import net.divinerpg.entities.vethea.mobs.EntityZoragon;
import net.divinerpg.entities.vethea.projectile.EntityAmthirmisDisk;
import net.divinerpg.entities.vethea.projectile.EntityArksianeDisk;
import net.divinerpg.entities.vethea.projectile.EntityBouncingProjectile;
import net.divinerpg.entities.vethea.projectile.EntityCermileDisk;
import net.divinerpg.entities.vethea.projectile.EntityDarvenDisk;
import net.divinerpg.entities.vethea.projectile.EntityDissimentShot;
import net.divinerpg.entities.vethea.projectile.EntityEvernightProjectile;
import net.divinerpg.entities.vethea.projectile.EntityEversightProjectile;
import net.divinerpg.entities.vethea.projectile.EntityHeliosisDisk;
import net.divinerpg.entities.vethea.projectile.EntityKarosCannonShot;
import net.divinerpg.entities.vethea.projectile.EntityKarosDisk;
import net.divinerpg.entities.vethea.projectile.EntityKazroticShot;
import net.divinerpg.entities.vethea.projectile.EntityMandragoraProjectile;
import net.divinerpg.entities.vethea.projectile.EntityPardimalDisk;
import net.divinerpg.entities.vethea.projectile.EntityQuadroticDisk;
import net.divinerpg.entities.vethea.projectile.EntityRaglokBomb;
import net.divinerpg.entities.vethea.projectile.EntityTeakerDisk;
import net.divinerpg.entities.vethea.projectile.EntityVetheanArrow;
import net.divinerpg.entities.vethea.projectile.EntityVetheanArrow2;
import net.divinerpg.entities.vethea.projectile.EntityVetheanCannonShot;
import net.divinerpg.entities.vethea.projectile.EntityVetheanWarArrow;
import net.divinerpg.entities.vethea.projectile.EntityVetheanWrathArrow;
import net.divinerpg.entities.vethea.projectile.EntityWreckBouncingProjectile;
import net.divinerpg.entities.vethea.projectile.EntityWreckExplosiveShot;
import net.divinerpg.entities.vethea.projectile.EntityWreckStrengthShot;
import net.divinerpg.entities.vethea.projectile.EntityZoragonBomb;
import net.divinerpg.lib.EntityResourceLocs;
import net.divinerpg.models.vethea.mobs.AcidHag;
import net.divinerpg.models.vethea.mobs.Biphron;
import net.divinerpg.models.vethea.mobs.Boheimite;
import net.divinerpg.models.vethea.mobs.CryptKeeper;
import net.divinerpg.models.vethea.mobs.Cymesoid;
import net.divinerpg.models.vethea.mobs.Dissiment;
import net.divinerpg.models.vethea.mobs.Dreamwrecker;
import net.divinerpg.models.vethea.mobs.Duo;
import net.divinerpg.models.vethea.mobs.Ehu;
import net.divinerpg.models.vethea.mobs.Endiku;
import net.divinerpg.models.vethea.mobs.Ent;
import net.divinerpg.models.vethea.mobs.Galroid;
import net.divinerpg.models.vethea.mobs.Gorgosion;
import net.divinerpg.models.vethea.mobs.Helio;
import net.divinerpg.models.vethea.mobs.Herbomancer;
import net.divinerpg.models.vethea.mobs.HiveQueen;
import net.divinerpg.models.vethea.mobs.HiveSoldier;
import net.divinerpg.models.vethea.mobs.HoverStinger;
import net.divinerpg.models.vethea.mobs.Husk;
import net.divinerpg.models.vethea.mobs.Karos;
import net.divinerpg.models.vethea.mobs.Kazrotic;
import net.divinerpg.models.vethea.mobs.LadyLuna;
import net.divinerpg.models.vethea.mobs.Lheiva;
import net.divinerpg.models.vethea.mobs.Lorga;
import net.divinerpg.models.vethea.mobs.Lorgaflight;
import net.divinerpg.models.vethea.mobs.Mandragora;
import net.divinerpg.models.vethea.mobs.ModelHungerHungry;
import net.divinerpg.models.vethea.mobs.MysteriousMan;
import net.divinerpg.models.vethea.mobs.Quadro;
import net.divinerpg.models.vethea.mobs.RaglokGogdure;
import net.divinerpg.models.vethea.mobs.Shadahier;
import net.divinerpg.models.vethea.mobs.SpinebackBody;
import net.divinerpg.models.vethea.mobs.SpinebackHead;
import net.divinerpg.models.vethea.mobs.StoneGolem;
import net.divinerpg.models.vethea.mobs.Tocaxin;
import net.divinerpg.models.vethea.mobs.Twins;
import net.divinerpg.models.vethea.mobs.Vermenous;
import net.divinerpg.models.vethea.mobs.Versmillion;
import net.divinerpg.models.vethea.mobs.Vhraak;
import net.divinerpg.models.vethea.mobs.WreckForm1;
import net.divinerpg.models.vethea.mobs.Zone;
import net.divinerpg.models.vethea.mobs.Zoragon;
import net.divinerpg.renders.RenderBasicProjectile;
import net.divinerpg.renders.RenderDivineDisc;
import net.divinerpg.renders.RenderDivineEntity;
import net.divinerpg.renders.RenderLivingDivine;
import net.divinerpg.renders.vethea.mob.RenderDarvenArrow;
import net.divinerpg.renders.vethea.mob.RenderKarosArrow;
import net.divinerpg.renders.vethea.mob.RenderLadyLuna;
import net.divinerpg.renders.vethea.mob.RenderPardimalArrow;
import net.divinerpg.renders.vethea.mob.RenderTeakerArrow;
import net.divinerpg.renders.vethea.mob.RenderWreck;
import net.divinerpg.utils.helpers.item.VetheaItemHelper;
import net.minecraft.client.model.ModelBiped;
import cpw.mods.fml.client.registry.RenderingRegistry;
import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;

@SideOnly(Side.CLIENT)
public class VetheaRenderHelper 
{
	public static void init()
	{
		RenderingRegistry.registerEntityRenderingHandler(EntityVermenous.class, new RenderDivineEntity(new Vermenous(), 0.0F, EntityResourceLocs.VERMENOUS));
        RenderingRegistry.registerEntityRenderingHandler(EntityEnt.class, new RenderDivineEntity(new Ent(), 0.0F, EntityResourceLocs.ENT));
        RenderingRegistry.registerEntityRenderingHandler(EntityCymesoid.class, new RenderDivineEntity(new Cymesoid(), 0.0F, EntityResourceLocs.CYMESOID));
        RenderingRegistry.registerEntityRenderingHandler(EntityDreamwrecker.class, new RenderDivineEntity(new Dreamwrecker(), 0.0F, EntityResourceLocs.DRAMCRYX));
        RenderingRegistry.registerEntityRenderingHandler(EntityTocaxin.class, new RenderDivineEntity(new Tocaxin(), 0.0F, EntityResourceLocs.TOCAXIN));
        RenderingRegistry.registerEntityRenderingHandler(EntityShadahier.class, new RenderDivineEntity(new Shadahier(), 0.0F, EntityResourceLocs.SHADAHIER));
        RenderingRegistry.registerEntityRenderingHandler(EntityAcidHag.class, new RenderDivineEntity(new AcidHag(), 0.0F, EntityResourceLocs.ACID_HAG));
        RenderingRegistry.registerEntityRenderingHandler(EntityKazrotic.class, new RenderDivineEntity(new Kazrotic(), 0.0F, EntityResourceLocs.KAZROTIC));
        RenderingRegistry.registerEntityRenderingHandler(EntityHelio.class, new RenderDivineEntity(new Helio(), 0.0F, EntityResourceLocs.HELIO));
        RenderingRegistry.registerEntityRenderingHandler(EntityGorgosion.class, new RenderDivineEntity(new Gorgosion(), 0.0F, EntityResourceLocs.GORGOSION));
        RenderingRegistry.registerEntityRenderingHandler(EntityHoverStinger.class, new RenderDivineEntity(new HoverStinger(), 0.0F, 0.35F, EntityResourceLocs.HOVER_STINGER));
        RenderingRegistry.registerEntityRenderingHandler(EntityZone.class, new RenderDivineEntity(new Zone(), 0.0F, EntityResourceLocs.ZONE));
        RenderingRegistry.registerEntityRenderingHandler(EntityZoragon.class, new RenderDivineEntity(new Zoragon(), 0.0F, 5F, EntityResourceLocs.ZORAGON));
        RenderingRegistry.registerEntityRenderingHandler(EntityDissiment.class, new RenderDivineEntity(new Dissiment(), 0.0F, 3, EntityResourceLocs.DISSIMENT));
        RenderingRegistry.registerEntityRenderingHandler(EntitySpinebackWorm.class, new RenderDivineEntity(new SpinebackBody(), 0.0F, EntityResourceLocs.ALICANTO));
        RenderingRegistry.registerEntityRenderingHandler(EntitySpinebackWormBody.class, new RenderDivineEntity(new SpinebackHead(), 0.0F, EntityResourceLocs.ALICANTO));
        RenderingRegistry.registerEntityRenderingHandler(EntityVhraak.class, new RenderDivineEntity(new Vhraak(), 0.0F, EntityResourceLocs.VHRAAK));
        RenderingRegistry.registerEntityRenderingHandler(EntityGalroid.class, new RenderDivineEntity(new Galroid(), 0.0F, EntityResourceLocs.GALROID));
        RenderingRegistry.registerEntityRenderingHandler(EntityLadyLuna.class, new RenderLadyLuna(new LadyLuna(), 0.0F, EntityResourceLocs.LADY_LUNA_MELEE)); // BOSS
        RenderingRegistry.registerEntityRenderingHandler(EntityBohemite.class, new RenderDivineEntity(new Boheimite(), 0.0F, EntityResourceLocs.BOHEMITE));
        RenderingRegistry.registerEntityRenderingHandler(EntityWreck.class, new RenderWreck(new WreckForm1(), 0.0F, EntityResourceLocs.WRECK)); // BOSS
        RenderingRegistry.registerEntityRenderingHandler(EntityBiphron.class, new RenderDivineEntity(new Biphron(), 0.0F, EntityResourceLocs.BIPHRON));
        RenderingRegistry.registerEntityRenderingHandler(EntityHiveQueen.class, new RenderDivineEntity(new HiveQueen(), 0.0F, 2, EntityResourceLocs.HIVE_QUEEN));
        RenderingRegistry.registerEntityRenderingHandler(EntityHiveSoldier.class, new RenderDivineEntity(new HiveSoldier(), 0.0F, EntityResourceLocs.HIVE_SOLDIER));
        RenderingRegistry.registerEntityRenderingHandler(EntityLheiva.class, new RenderDivineEntity(new Lheiva(), 0.0F, EntityResourceLocs.LHEIVA));
        RenderingRegistry.registerEntityRenderingHandler(EntityTwins.class, new RenderDivineEntity(new Twins(), 0.0F, EntityResourceLocs.TWINS));
        RenderingRegistry.registerEntityRenderingHandler(EntityEndiku.class, new RenderLivingDivine(new Endiku(), 0.0F, EntityResourceLocs.ENDIKU));
        RenderingRegistry.registerEntityRenderingHandler(EntityTempleGuardian.class, new RenderLivingDivine(new ModelBiped(), 0.0F, EntityResourceLocs.TEMPLE_GUARDIAN));
        RenderingRegistry.registerEntityRenderingHandler(EntityMysteriousManLayer1.class, new RenderLivingDivine(new MysteriousMan(), 0.0F, EntityResourceLocs.MYSTERIOUS_MAN_LAYER_1));
        RenderingRegistry.registerEntityRenderingHandler(EntityMysteriousManLayer2.class, new RenderLivingDivine(new MysteriousMan(), 0.0F, EntityResourceLocs.MYSTERIOUS_MAN_LAYER_2));
        RenderingRegistry.registerEntityRenderingHandler(EntityMysteriousManLayer3.class, new RenderLivingDivine(new MysteriousMan(), 0.0F, EntityResourceLocs.MYSTERIOUS_MAN_LAYER_3));
        RenderingRegistry.registerEntityRenderingHandler(EntityCryptKeeper.class, new RenderLivingDivine(new CryptKeeper(), 0.0F, EntityResourceLocs.CRYPT_KEEPER));
        RenderingRegistry.registerEntityRenderingHandler(EntityDuo.class, new RenderLivingDivine(new Duo(), 0.0F, EntityResourceLocs.DUO));
        RenderingRegistry.registerEntityRenderingHandler(EntityEhu.class, new RenderLivingDivine(new Ehu(), 0.0F, EntityResourceLocs.EHU));
        RenderingRegistry.registerEntityRenderingHandler(EntityHusk.class, new RenderLivingDivine(new Husk(), 0.0F, EntityResourceLocs.HUSK));
        RenderingRegistry.registerEntityRenderingHandler(EntityVermsillion.class, new RenderLivingDivine(new Versmillion(), 0.0F, EntityResourceLocs.VERMSILLION));
        RenderingRegistry.registerEntityRenderingHandler(EntityStoneGolem.class, new RenderLivingDivine(new StoneGolem(), 0.0F, EntityResourceLocs.STONE_GOLEM));
        RenderingRegistry.registerEntityRenderingHandler(EntityGalroid.class, new RenderLivingDivine(new Galroid(), 0.0F, EntityResourceLocs.GALROID));
        RenderingRegistry.registerEntityRenderingHandler(EntityHerbomancer.class, new RenderLivingDivine(new Herbomancer(), 0.0F, EntityResourceLocs.HERBOMANCER));
        RenderingRegistry.registerEntityRenderingHandler(EntityKaros.class, new RenderLivingDivine(new Karos(), 0.0F, EntityResourceLocs.KAROS));
        RenderingRegistry.registerEntityRenderingHandler(EntityLheiva.class, new RenderLivingDivine(new Lheiva(), 0.0F, EntityResourceLocs.LHEIVA));
        RenderingRegistry.registerEntityRenderingHandler(EntityLorga.class, new RenderLivingDivine(new Lorga(), 0.0F, EntityResourceLocs.LORGA));
        RenderingRegistry.registerEntityRenderingHandler(EntityLorgaFlight.class, new RenderLivingDivine(new Lorgaflight(), 0.0F, EntityResourceLocs.LORGA_FLIGHT));
        RenderingRegistry.registerEntityRenderingHandler(EntityMandragora.class, new RenderLivingDivine(new Mandragora(), 0.0F, EntityResourceLocs.MANDRAGORA));
        RenderingRegistry.registerEntityRenderingHandler(EntityQuadro.class, new RenderLivingDivine(new Quadro(), 0.0F, EntityResourceLocs.QUADRO));
        RenderingRegistry.registerEntityRenderingHandler(EntityRaglok.class, new RenderLivingDivine(new RaglokGogdure(), 0.0F, EntityResourceLocs.RAGLOK));
        RenderingRegistry.registerEntityRenderingHandler(EntityTocaxin.class, new RenderLivingDivine(new Tocaxin(), 0.0F, EntityResourceLocs.TOCAXIN));
        RenderingRegistry.registerEntityRenderingHandler(EntityHungerHungry.class, new RenderLivingDivine(new ModelHungerHungry(), 0.0F, EntityResourceLocs.HUNGER_HUNGRY));

        RenderingRegistry.registerEntityRenderingHandler(EntityKazroticShot.class, new RenderBasicProjectile(EntityResourceLocs.KAZROTIC_SHOT));
        RenderingRegistry.registerEntityRenderingHandler(EntityZoragonBomb.class, new RenderBasicProjectile(EntityResourceLocs.ZORAGON_BOMB));
        RenderingRegistry.registerEntityRenderingHandler(EntityDissimentShot.class, new RenderBasicProjectile(EntityResourceLocs.DISSIMENT_SHOT));
        
        RenderingRegistry.registerEntityRenderingHandler(EntityTeakerDisk.class, new RenderDivineDisc(VetheaItemHelper.teakerDisk));
        RenderingRegistry.registerEntityRenderingHandler(EntityAmthirmisDisk.class, new RenderDivineDisc(VetheaItemHelper.amthrimisDisk));
        RenderingRegistry.registerEntityRenderingHandler(EntityDarvenDisk.class, new RenderDivineDisc(VetheaItemHelper.darvenDisk));
        RenderingRegistry.registerEntityRenderingHandler(EntityCermileDisk.class, new RenderDivineDisc(VetheaItemHelper.cermileDisk));
        RenderingRegistry.registerEntityRenderingHandler(EntityPardimalDisk.class, new RenderDivineDisc(VetheaItemHelper.pardimalDisk));
        RenderingRegistry.registerEntityRenderingHandler(EntityQuadroticDisk.class, new RenderDivineDisc(VetheaItemHelper.quadroticDisk));
        RenderingRegistry.registerEntityRenderingHandler(EntityKarosDisk.class, new RenderDivineDisc(VetheaItemHelper.karosDisk));
        RenderingRegistry.registerEntityRenderingHandler(EntityHeliosisDisk.class, new RenderDivineDisc(VetheaItemHelper.heliosisDisk));
        RenderingRegistry.registerEntityRenderingHandler(EntityArksianeDisk.class, new RenderDivineDisc(VetheaItemHelper.arksianeDisk));
        
        RenderingRegistry.registerEntityRenderingHandler(EntityVetheanArrow.class, new RenderTeakerArrow());
        RenderingRegistry.registerEntityRenderingHandler(EntityVetheanArrow2.class, new RenderDarvenArrow());
        RenderingRegistry.registerEntityRenderingHandler(EntityVetheanWarArrow.class, new RenderPardimalArrow());
        RenderingRegistry.registerEntityRenderingHandler(EntityVetheanWrathArrow.class, new RenderKarosArrow());
        RenderingRegistry.registerEntityRenderingHandler(EntityKarosCannonShot.class, new RenderKarosArrow());
        
        RenderingRegistry.registerEntityRenderingHandler(EntityVetheanCannonShot.class, new RenderBasicProjectile(EntityResourceLocs.VETHEAN_CANNON_SHOT));
        RenderingRegistry.registerEntityRenderingHandler(EntityEvernightProjectile.class, new RenderBasicProjectile(EntityResourceLocs.EVERNIGHT));
        RenderingRegistry.registerEntityRenderingHandler(EntityEversightProjectile.class, new RenderBasicProjectile(EntityResourceLocs.EVERSIGHT));
        RenderingRegistry.registerEntityRenderingHandler(EntityBouncingProjectile.class, new RenderBasicProjectile(EntityResourceLocs.EVERNIGHT));
        RenderingRegistry.registerEntityRenderingHandler(EntityWreckBouncingProjectile.class, new RenderBasicProjectile(EntityResourceLocs.EVERNIGHT));
        RenderingRegistry.registerEntityRenderingHandler(EntityWreckStrengthShot.class, new RenderBasicProjectile(EntityResourceLocs.EXPLOSIVE_SHOT));
        RenderingRegistry.registerEntityRenderingHandler(EntityWreckExplosiveShot.class, new RenderBasicProjectile(EntityResourceLocs.EXPLOSIVE_SHOT));
        RenderingRegistry.registerEntityRenderingHandler(EntityRaglokBomb.class, new RenderBasicProjectile(EntityResourceLocs.RAGLOK_BOMB));
        RenderingRegistry.registerEntityRenderingHandler(EntityMandragoraProjectile.class, new RenderBasicProjectile(EntityResourceLocs.MANDRAGORA_PROJECTILE));
	}
}
