package xolova.blued00r.divinerpg.misc;

import net.minecraft.block.Block;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import cpw.mods.fml.common.registry.GameRegistry;
import xolova.blued00r.divinerpg.DivineRPG;


public class ModRecipes {
	
	public static void init()
	{
		GameRegistry.addRecipe(new ItemStack(DivineRPG.draviteLamp, 1), new Object[] { "xxx", "xyx", "xxx", 'y', DivineRPG.serenityFragments, 'x', Item.ingotIron });
        GameRegistry.addRecipe(new ItemStack(DivineRPG.aquaticTrident, 1), new Object[] {" y ", "yyy", " x ", 'y', DivineRPG.aquaticIngot , 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.aquaton, 1), new Object[] {"yyy", "yyy", " x ", 'y', DivineRPG.aquaticIngot , 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.hamreicher, 1), new Object[] {"yyy", "yyy", "yxy", 'y', DivineRPG.aquaticIngot , 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.crabClawCannon, 1), new Object[] {" y ", " y ", " x ", 'y', DivineRPG.crabClaw , 'x', DivineRPG.aquaticIngot});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.sharkSword, 1), new Object[] {" y ", " y ", " x ", 'y', DivineRPG.sharkFin , 'x', DivineRPG.aquaticIngot});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.bowheadCannon, 1), new Object[] {" y ", " y ", " x ", 'y', DivineRPG.whaleFin , 'x', DivineRPG.aquaticIngot});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.oceanKnife, 1), new Object[] {" y ", " y ", " x ", 'y', DivineRPG.aquaticIngot , 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.dualClaw, 1), new Object[] {" y ", "xxx", " y ", 'y', DivineRPG.crabClaw , 'x', DivineRPG.aquaticIngot});
        //GameRegistry.addRecipe(new ItemStack(DivineRPG.crabClawMaul, 1), new Object[]{"yyy", " y ", "yxy", 'y', DivineRPG.crabClaw , 'x', DivineRPG.aquaticIngot});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.daggerOfBlood, 1), new Object[] {" y ", " x ", 'y', DivineRPG.aquaticIngot , 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.clawAnchor, 1), new Object[] {"yyy", "yxy", " x ", 'y', DivineRPG.crabClaw , 'x', DivineRPG.aquaticIngot});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.bowheadAnchor, 1), new Object[] {"yyy", "yxy", " x ", 'y', DivineRPG.whaleFin , 'x', DivineRPG.aquaticIngot});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.sharkAnchor, 1), new Object[] {"yyy", "yxy", " x ", 'y', DivineRPG.sharkFin , 'x', DivineRPG.aquaticIngot});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.pureAquaticPellets, 1), new Object[] {"xxx", "xxx", "xxx", 'x', DivineRPG.aquaticPellets});
        GameRegistry.addSmelting(DivineRPG.pureAquaticPellets.itemID, new ItemStack(DivineRPG.aquaticIngot, 1), 0);
        //Recipes
        //Armor
        GameRegistry.addRecipe(new ItemStack(DivineRPG.netheriteHead, 1), new Object[] {"xxx", "s s", "x x", 'x', DivineRPG.netheriteChunk, 's', DivineRPG.shadowBar});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.netheriteBody, 1), new Object[] {"xsx", "xsx", " x ", 'x', DivineRPG.netheriteChunk, 's', DivineRPG.shadowBar});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.netheriteLegs, 1), new Object[] {"sss", "x x", "s s", 'x', DivineRPG.netheriteChunk, 's', DivineRPG.shadowBar});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.netheriteBoots, 1), new Object[] {"s s", "x x", 'x', DivineRPG.netheriteChunk, 's', DivineRPG.shadowBar});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.crystonalHead, 1), new Object[] {"xxx", "sss", "s s", 'x', DivineRPG.arlemite, 's', Item.ingotIron});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.crystonalBody, 1), new Object[] {"xsx", "sxs", " s ", 'x', DivineRPG.arlemite, 's', Item.ingotIron});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.crystonalLegs, 1), new Object[] {"sss", "x x", "y y", 'x', DivineRPG.arlemite, 's', Item.ingotIron, 'y', DivineRPG.shadowBar});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.crystonalBoots, 1), new Object[] {"s s", "x x", 'x', DivineRPG.arlemite, 's', Item.ingotIron});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.krakenHead, 1), new Object[] {"xxx", "xxx", "x x", 'x', DivineRPG.krakenSkin});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.krakenBody, 1), new Object[] {"xxx", "xxx", " x ", 'x', DivineRPG.krakenSkin});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.krakenLegs, 1), new Object[] {"xxx", "x x", "x x", 'x', DivineRPG.krakenSkin});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.krakenBoots, 1), new Object[] {"x x", "x x", 'x', DivineRPG.krakenSkin});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.infernoHead, 1), new Object[] {"xxx", "xxx", "x x", 'x', DivineRPG.moltenStone});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.infernoBody, 1), new Object[] {"xxx", "xxx", " x ", 'x', DivineRPG.moltenStone});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.infernoLegs, 1), new Object[] {"xxx", "x x", "x x", 'x', DivineRPG.moltenStone});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.infernoBoots, 1), new Object[] {"x x", "x x", 'x', DivineRPG.moltenStone});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.bedrockHead, 1), new Object[] {"xxx", "x x", 'x', Block.bedrock});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.bedrockBody, 1), new Object[] {"x x", "xxx", "xxx", 'x', Block.bedrock});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.bedrockLegs, 1), new Object[] {"xxx", "x x", "x x", 'x', Block.bedrock});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.bedrockBoots, 1), new Object[] {"x x", "x x", 'x', Block.bedrock});
        //GameRegistry.addRecipe(new ItemStack(DivineRPG.enderBody, 1), new Object[]{"xxx", "yzy", "yyy", 'x', DivineRPG.empoweredEnderPearl, 'y', DivineRPG.enderDust, 'z', pearlOfDarkness});
        //GameRegistry.addRecipe(new ItemStack(DivineRPG.enderHead, 1), new Object[]{"xzx", "yyy", "y y", 'x', DivineRPG.empoweredEnderPearl, 'y', DivineRPG.enderDust, 'z', pearlOfDarkness});
        //GameRegistry.addRecipe(new ItemStack(DivineRPG.enderLegs, 1), new Object[]{"xyx", "x x", "y y", 'x', DivineRPG.enderDust, 'y', DivineRPG.eyeOfStrength});
        //GameRegistry.addRecipe(new ItemStack(DivineRPG.enderBoots, 1), new Object[]{"y x", "x y", 'x', DivineRPG.pearlOfDarkness, 'y', DivineRPG.eyeOfStrength});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.plasmaHead, 1), new Object[] {"xxx", "xxx", "x x", 'x', DivineRPG.rupee});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.plasmaBody, 1), new Object[] {"xxx", "xxx", " x ", 'x', DivineRPG.rupee});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.plasmaLegs, 1), new Object[] {"xxx", "x x", "x x", 'x', DivineRPG.rupee});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.plasmaBoots, 1), new Object[] {"x x", "x x", 'x', DivineRPG.rupee});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.realmiteHead, 1), new Object[] {"xxx", "xxx", "x x", 'x', DivineRPG.realmiteIngot});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.realmiteBody, 1), new Object[] {"xxx", "xxx", " x ", 'x', DivineRPG.realmiteIngot});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.realmiteLegs, 1), new Object[] {"xxx", "x x", "x x", 'x', DivineRPG.realmiteIngot});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.realmiteBoots, 1), new Object[] {"x x", "x x", 'x', DivineRPG.realmiteIngot});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.eliteRealmiteHead, 1), new Object[] {"xxx", "xxx", "x x", 'x', DivineRPG.realmite});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.eliteRealmiteBody, 1), new Object[] {"xxx", "xxx", " x ", 'x', DivineRPG.realmite});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.eliteRealmiteLegs, 1), new Object[] {"xxx", "x x", "x x", 'x', DivineRPG.realmite});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.eliteRealmiteBoots, 1), new Object[] {"x x", "x x", 'x', DivineRPG.realmite});
        //GameRegistry.addRecipe(new ItemStack(DivineRPG.aquastriveHead, 1), new Object[]{"xxx", "xxx", "x x", 'x', DivineRPG.corruptedAquaBall});
        //GameRegistry.addRecipe(new ItemStack(DivineRPG.aquastriveBody, 1), new Object[]{"xxx", "xxx", " x ", 'x', DivineRPG.corruptedAquaBall});
        //GameRegistry.addRecipe(new ItemStack(DivineRPG.aquastriveLegs, 1), new Object[]{"xxx", "x x", "x x", 'x', DivineRPG.corruptedAquaBall});
        //GameRegistry.addRecipe(new ItemStack(DivineRPG.aquastriveBoots, 1), new Object[]{"x x", "x x", 'x', DivineRPG.corruptedAquaBall});
        //GameRegistry.setInGameHook(this, true, false);
        //Tools
        GameRegistry.addRecipe(new ItemStack(DivineRPG.enderSword, 1), new Object[] {" x ", " x ", " y ", 'x', DivineRPG.legendaryEnderEye, 'y', DivineRPG.shadowBar});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.enderSwordDark, 1), new Object[] {DivineRPG.enderSword, DivineRPG.blackCrystallon});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.enderSwordBlue, 1), new Object[] {DivineRPG.enderSword, DivineRPG.blueCrystallon});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.enderSwordRed, 1), new Object[] {DivineRPG.enderSword, DivineRPG.redCrystallon});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.enderSwordGreen, 1), new Object[] {DivineRPG.enderSword, DivineRPG.greenCrystallon});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.enderSwordYellow, 1), new Object[] {DivineRPG.enderSword, DivineRPG.yellowCrystallon});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.dalmorSaber, 1), new Object[] {" x ", " x ", " y ", 'x', DivineRPG.purpleBlaze, 'y', DivineRPG.glowingGem});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.gognisahr, 1), new Object[] {"x x", "xxx", " x ", 'x', DivineRPG.realmiteIngot});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.namkormira, 1), new Object[] {"x x", "yyy", " y ", 'x', DivineRPG.glowingGem, 'y', DivineRPG.netheriteBar});
        //GameRegistry.addRecipe(new ItemStack(DivineRPG.rejuvenator, 1), new Object[]{"yxy", " x ", " z ", 'x', DivineRPG.crystallon, 'y', DivineRPG.healingStone, 'z', Item.stick});
        //GameRegistry.addRecipe(new ItemStack(DivineRPG.aquaventavor, 1), new Object[]{"yxy", " x ", " z ", 'x', DivineRPG.aquaBall, 'y', DivineRPG.healingStone, 'z', Item.stick});
        //GameRegistry.addRecipe(new ItemStack(DivineRPG.judgement, 1), new Object[]{"zxz", "zxz", "zyz", 'x', DivineRPG.aquaBall, 'y', Item.stick, 'z', healingStone});
        //GameRegistry.addRecipe(new ItemStack(DivineRPG.victor, 1), new Object[]{"wxw", "yxw", "mzm", 'x', DivineRPG.aquaBall, 'y', DivineRPG.healingStone, 'w', crystallon, 'm', realmite, 'z', Item.stick});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.infernoSword, 1), new Object[] {"xyx", "xyx", "xzx", 'x', Item.blazePowder, 'y', Block.oreRedstone, 'z', Item.stick});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.bedrockSword, 1), new Object[] {" y ", " y ", " x ", 'x', Item.stick, 'y', Block.bedrock});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.realmiteSword, 1), new Object[] {" y ", " y ", " x ", 'x', Item.stick, 'y', DivineRPG.realmite});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.arlemiteStabber, 1), new Object[] {" y ", " y ", " x ", 'x', Item.stick, 'y', DivineRPG.arlemite});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.rupeeSword, 1), new Object[] {" y ", " y ", " x ", 'x', Item.stick, 'y', DivineRPG.rupee});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.slimeSword, 1), new Object[] {"yxy", "yxy", "yxy", 'y', Item.slimeBall, 'x', Item.swordDiamond});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.furyMaul, 1), new Object[] {"yxy", "xxx", "yxy", 'x', Block.bedrock, 'y', Block.oreDiamond});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.bedrockMaul, 1), new Object[] {" x ", "xyx", " x ", 'y', Block.bedrock, 'x', Block.bedrock});
        //GameRegistry.addRecipe(new ItemStack(DivineRPG.crystalleSpikeball, 1), new Object[]{"xyx", "y y", "xyx", 'y', Item.ingotIron, 'x', DivineRPG.arlemite});
        //GameRegistry.addRecipe(new ItemStack(DivineRPG.purpleBlazingSpikeball, 1), new Object[]{"xyx", "y y", "xyx", 'y', Item.ingotIron, 'x', DivineRPG.rupee});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.crystalSword, 1), new Object[] {" x ", " x ", " y ", 'x', DivineRPG.blueFireStone, 'y', DivineRPG.shadowBar});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.blazingCrystalleSword, 1), new Object[] {" x ", " z ", " y ", 'x', DivineRPG.glowingGem, 'y', Item.stick, 'z', DivineRPG.glowingGem});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.realmitePickaxe, 1), new Object[] {"xxx", " y ", " y ", 'x', DivineRPG.realmiteIngot, 'y', Item.stick});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.realmiteAxe, 1), new Object[] {"xx ", "xy ", " y ", 'x', DivineRPG.realmiteIngot, 'y', Item.stick});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.realmiteShovel, 1), new Object[] {" x ", " y ", " y ", 'x', DivineRPG.realmiteIngot, 'y', Item.stick});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.bedrockPickaxe, 1), new Object[] {"xxx", " y ", " y ", 'x', Block.bedrock, 'y', Item.stick});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.bedrockAxe, 1), new Object[] {"xx ", "xy ", " y ", 'x', Block.bedrock, 'y', Item.stick});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.bedrockShovel, 1), new Object[] {" x ", " y ", " y ", 'x', Block.bedrock, 'y', Item.stick});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.crystalPickaxe, 1), new Object[] {"xxx", " y ", " y ", 'x', DivineRPG.arlemite, 'y', Item.stick});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.crystalAxe, 1), new Object[] {"xx ", "xy ", " y ", 'x', DivineRPG.arlemite, 'y', Item.stick});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.crystalShovel, 1), new Object[] {" x ", " y ", " y ", 'x', DivineRPG.arlemite, 'y', Item.stick});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.crystalHoe, 1), new Object[] {"xx ", " y ", " y ", 'x', DivineRPG.arlemite, 'y', Item.stick});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.plasmaPickaxe, 1), new Object[] {"xxx", " y ", " y ", 'x', DivineRPG.rupee, 'y', Item.stick});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.plasmaAxe, 1), new Object[] {"xx ", "xy ", " y ", 'x', DivineRPG.rupee, 'y', Item.stick});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.plasmaShovel, 1), new Object[] {" x ", " y ", " y ", 'x', DivineRPG.rupee, 'y', Item.stick});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.plasmaHoe, 1), new Object[] {"xx ", " y ", " y ", 'x', DivineRPG.rupee, 'y', Item.stick});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.plasmaShicaxe, 1), new Object[] {DivineRPG.plasmaHoe, DivineRPG.plasmaShovel, DivineRPG.plasmaPickaxe, DivineRPG.plasmaAxe});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.crystalShicaxe, 1), new Object[] {DivineRPG.crystalHoe, DivineRPG.crystalShovel, DivineRPG.crystalPickaxe, DivineRPG.crystalAxe});
        //GameRegistry.addRecipe(new ItemStack(DivineRPG.dalmorBattleaxe, 1), new Object[]{"xxx", "xyx", " y ", 'x', DivineRPG.glowingGem, 'y', DivineRPG.shadowBar});
        //GameRegistry.addRecipe(new ItemStack(DivineRPG.dalmorScyth, 1), new Object[]{"xxx", " yy", "  y", 'x', DivineRPG.glowingGem, 'y', DivineRPG.shadowBar});
        //GameRegistry.addRecipe(new ItemStack(DivineRPG.woodHater, 1), new Object[]{"xyx", "xyx", " y ", 'x', DivineRPG.empoweredEnderPearl, 'y', DivineRPG.aquaticBlazeRod});
        //GameRegistry.addRecipe(new ItemStack(DivineRPG.hoeHater, 1), new Object[]{"xxy", "yzy", "yzy", 'x', DivineRPG.crystallon, 'y', DivineRPG.realmite, 'z', Item.stick});
        //GameRegistry.addRecipe(new ItemStack(DivineRPG.oreHater, 1), new Object[]{"xxx", "yzy", "yzy", 'x', DivineRPG.crystallon, 'y', DivineRPG.realmite, 'z', Item.stick});
        //GameRegistry.addRecipe(new ItemStack(DivineRPG.dirtHater, 1), new Object[]{"yxy", "yzy", "yzy", 'x', Item.magmaCream, 'y', DivineRPG.crystallon, 'z', Item.stick});
        //Foods
        GameRegistry.addRecipe(new ItemStack(DivineRPG.donut, 1), new Object[] {"xxx", "x x", "xxx", 'x', Item.wheat});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.pizzaDough, 1), new Object[] {"x x", "xxx", 'x', Item.wheat});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.bacon, 6), new Object[] {Item.porkRaw});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.waterMelon, 1), new Object[] {"xxx", "xxx", 'x', Item.melon});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.cheese, 1), new Object[] {"xxx", "xxx", "xxx", 'x', Item.bucketMilk});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.minipizza, 4), new Object[] {DivineRPG.whiteMushroom, DivineRPG.tomato, DivineRPG.pizzaDough, DivineRPG.cheese});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.dinner, 4), new Object[] {Item.bread, Item.chickenRaw, Item.bowlSoup, DivineRPG.whiteMushroom, DivineRPG.whiteMushroom});
        GameRegistry.addSmelting(Item.egg.itemID, new ItemStack(DivineRPG.boiledegg, 1), 0);
        //Blocks
        GameRegistry.addRecipe(new ItemStack(DivineRPG.obsidianblock, 1), new Object[] {"xxx", "xxx", "xxx", 'x', Block.obsidian});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.iceblock, 1, 0), new Object[] {"xxx", "xxx", "xxx", 'x', Block.ice});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.iceblock, 1, 1), new Object[] {"xxx", "xxx", "xxx", 'x', Item.flint});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.iceblock, 1, 2), new Object[] {"xxx", "xxx", "xxx", 'x', Block.gravel});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.iceblock, 1, 3), new Object[] {"xxx", "xxx", "xxx", 'x', Item.coal});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.iceblock, 1, 4), new Object[] {"xxx", "xxx", "xxx", 'x', Block.stone});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.iceblock, 1, 5), new Object[] {"xxx", "xxx", "xxx", 'x', Block.sand});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.iceblock, 1, 6), new Object[] {"xxx", "xxx", "xxx", 'x', Block.slowSand});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.iceblock, 1, 7), new Object[] {"xxx", "xxx", "xxx", 'x', Block.dirt});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.realmite, 1), new Object[] {"xxx", "xxx", "xxx", 'x', DivineRPG.realmiteIngot});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.bedrock, 1), new Object[] {"xxx", "xxx", "xxx", 'x', Block.bedrock});
        GameRegistry.addShapelessRecipe(new ItemStack(Block.obsidian, 9), new Object[] {DivineRPG.obsidianblock});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.steel, 1, 0), new Object[] {"xxx", "xyx", "xxx", 'x', Item.ingotIron, 'y', new ItemStack(Item.dyePowder, 1, 6)});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.steel, 1, 1), new Object[] {"xxx", "xyx", "xxx", 'x', Item.ingotIron, 'y', new ItemStack(Item.dyePowder, 1, 1)});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.steel, 1, 2), new Object[] {"xxx", "xyx", "xxx", 'x', Item.ingotIron, 'y', new ItemStack(Item.dyePowder, 1, 5)});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.steel, 1, 3), new Object[] {"xxx", "xyx", "xxx", 'x', Item.ingotIron, 'y', new ItemStack(Item.dyePowder, 1, 2)});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.steel, 1, 4), new Object[] {"xxx", "xyx", "xxx", 'x', Item.ingotIron, 'y', new ItemStack(Item.dyePowder, 1, 11)});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.steel, 1, 5), new Object[] {"xxx", "xyx", "xxx", 'x', Item.ingotIron, 'y', new ItemStack(Item.dyePowder, 1, 4)});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.steel, 1, 6), new Object[] {"xxx", "xyx", "xxx", 'x', Item.ingotIron, 'y', new ItemStack(Item.dyePowder, 1, 15)});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.steel, 1, 7), new Object[] {"xxx", "xyx", "xxx", 'x', Item.ingotIron, 'y', new ItemStack(Item.dyePowder, 1, 0)});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.steel, 1, 8), new Object[] {"xxx", "xyx", "xxx", 'x', Item.ingotIron, 'y', new ItemStack(Item.dyePowder, 1, 14)});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.steel, 1, 9), new Object[] {"xxx", "xyx", "xxx", 'x', Item.ingotIron, 'y', new ItemStack(Item.dyePowder, 1, 13)});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.steel, 1, 11), new Object[] {"xxx", "y y", "xxx", 'x', Block.planks, 'y', Block.wood});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.steel, 1, 12), new Object[] {"xyx", "yxy", "xyx", 'x', new ItemStack(Block.planks, 1, 0), 'y', new ItemStack(Block.planks, 1, 1)});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.milkstone, 4), new Object[] {Block.stone, Block.stone, Block.stone, Item.bucketMilk});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.darkstone, 10), new Object[] {Block.obsidian, Block.glowStone});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.netherrack, 1), new Object[] {"xxx", "xxx", "xxx", 'x', Block.netherrack});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.redstonebricks, 4), new Object[] {Block.stoneBrick, Block.stoneBrick, Block.stoneBrick, Item.redstone});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.greenbricks, 4), new Object[] {Block.stoneBrick, Block.stoneBrick, Block.stoneBrick, new ItemStack(Item.dyePowder, 1, 2)});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.pinkbricks, 4), new Object[] {Block.stoneBrick, Block.stoneBrick, Block.stoneBrick, new ItemStack(Item.dyePowder, 1, 9)});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.purplebricks, 4), new Object[] {Block.stoneBrick, Block.stoneBrick, Block.stoneBrick, new ItemStack(Item.dyePowder, 1, 5)});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.lapisbricks, 4), new Object[] {Block.stoneBrick, Block.stoneBrick, Block.stoneBrick, new ItemStack(Item.dyePowder, 1, 4)});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.netheritebricks, 4), new Object[] {DivineRPG.netheriteBar});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.realmitebricks, 4), new Object[] {DivineRPG.realmiteIngot, DivineRPG.realmiteIngot, DivineRPG.realmiteIngot, DivineRPG.realmiteIngot, DivineRPG.realmiteIngot});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.goldbricks, 4), new Object[] {Block.stoneBrick, Block.stoneBrick, Block.stoneBrick, Item.ingotGold});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.ironbricks, 4), new Object[] {Block.stoneBrick, Block.stoneBrick, Block.stoneBrick, Item.ingotIron});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.darkbricks, 4), new Object[] {Block.stoneBrick, Block.stoneBrick, Block.stoneBrick, new ItemStack(Item.dyePowder, 1, 0)});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.milkstonebricks, 4), new Object[] {DivineRPG.milkstone, DivineRPG.milkstone, DivineRPG.milkstone});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.checker, 3, 0), new Object[] {"xyx", "yxy", "xyx",	'x', new ItemStack(Block.cloth, 1, 0), 'y', new ItemStack(Block.cloth, 1, 15)});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.redsand, 4), new Object[] {Block.sand, Block.sand, Block.sand, new ItemStack(Item.dyePowder, 1, 1)});
        GameRegistry.addSmelting(DivineRPG.redsand.blockID, new ItemStack(DivineRPG.redsandstone, 1), 0);
        GameRegistry.addRecipe(new ItemStack(DivineRPG.redsandstone1, 1), new Object[] {"xy ", 'x', DivineRPG.redsandstone, 'y', DivineRPG.chisel});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.redsandstone2, 1), new Object[] {"x y", 'x', DivineRPG.redsandstone, 'y', DivineRPG.chisel});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.eucalyptusPlanks, 4), new Object[] {DivineRPG.eucalyptus});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.stoneFence, 4), new Object[] {"xxx", "xxx", 'x', Block.cobblestone});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.woodFence, 4), new Object[] {"xxx", "xxx", 'x', Block.planks});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.fenceLightoff1, 4), new Object[] {"yyy", "yyy", 'y', new ItemStack(Item.dyePowder, 1, 4)});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.fenceLightoff, 4), new Object[] {"yyy", "yyy", 'y', Item.redstone});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.dyeblocks, 1, 0), new Object[] {"xxx", "xxx", "xxx", 'x', new ItemStack(Item.dyePowder, 1, 15)});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.dyeblocks, 1, 1), new Object[] {"xxx", "xxx", "xxx", 'x', new ItemStack(Item.dyePowder, 1, 14)});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.dyeblocks, 1, 2), new Object[] {"xxx", "xxx", "xxx", 'x', new ItemStack(Item.dyePowder, 1, 13)});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.dyeblocks, 1, 3), new Object[] {"xxx", "xxx", "xxx", 'x', new ItemStack(Item.dyePowder, 1, 12)});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.dyeblocks, 1, 4), new Object[] {"xxx", "xxx", "xxx", 'x', new ItemStack(Item.dyePowder, 1, 11)});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.dyeblocks, 1, 5), new Object[] {"xxx", "xxx", "xxx", 'x', new ItemStack(Item.dyePowder, 1, 10)});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.dyeblocks, 1, 6), new Object[] {"xxx", "xxx", "xxx", 'x', new ItemStack(Item.dyePowder, 1, 9)});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.dyeblocks, 1, 7), new Object[] {"xxx", "xxx", "xxx", 'x', new ItemStack(Item.dyePowder, 1, 8)});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.dyeblocks, 1, 8), new Object[] {"xxx", "xxx", "xxx", 'x', new ItemStack(Item.dyePowder, 1, 7)});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.dyeblocks, 1, 9), new Object[] {"xxx", "xxx", "xxx", 'x', new ItemStack(Item.dyePowder, 1, 6)});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.dyeblocks, 1, 10), new Object[] {"xxx", "xxx", "xxx", 'x', new ItemStack(Item.dyePowder, 1, 5)});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.dyeblocks, 1, 11), new Object[] {"xxx", "xxx", "xxx", 'x', new ItemStack(Item.dyePowder, 1, 3)});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.dyeblocks, 1, 12), new Object[] {"xxx", "xxx", "xxx", 'x', new ItemStack(Item.dyePowder, 1, 2)});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.dyeblocks, 1, 13), new Object[] {"xxx", "xxx", "xxx", 'x', new ItemStack(Item.dyePowder, 1, 1)});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.dyeblocks, 1, 14), new Object[] {"xxx", "xxx", "xxx", 'x', new ItemStack(Item.dyePowder, 1, 0)});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.clrdbricks, 4, 2), new Object[] {Block.brick, new ItemStack(Item.dyePowder, 1, 11)});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.clrdbricks, 4, 0), new Object[] {Block.brick, new ItemStack(Item.dyePowder, 1, 4)});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.clrdbricks, 4, 3), new Object[] {Block.brick, new ItemStack(Item.dyePowder, 1, 0)});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.clrdbricks, 4, 4), new Object[] {Block.brick, new ItemStack(Item.dyePowder, 1, 5)});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.clrdbricks, 4, 1), new Object[] {Block.brick, new ItemStack(Item.dyePowder, 1, 2)});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.empoweredBlocks, 1, 3), new Object[] {Block.planks, new ItemStack(Item.dyePowder, 1, 11)});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.empoweredBlocks, 1, 4), new Object[] {Block.planks, new ItemStack(Item.dyePowder, 1, 1)});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.empoweredBlocks, 1, 5), new Object[] {Block.planks, new ItemStack(Item.dyePowder, 1, 5)});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.empoweredBlocks, 1, 6), new Object[] {Block.planks, new ItemStack(Item.dyePowder, 1, 6)});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.empoweredBlocks, 1, 7), new Object[] {Block.planks, new ItemStack(Item.dyePowder, 1, 2)});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.empoweredBlocks, 1, 8), new Object[] {Block.planks, new ItemStack(Item.dyePowder, 1, 15)});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.slimelight, 1), new Object[] {"xxx", "xyx", "xxx", 'x', Item.ingotIron, 'y', Item.slimeBall});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.redstoneBlockOn, 1), new Object[] {"xxx", "xyx", "xxx", 'x', Item.redstone, 'y', Block.torchRedstoneActive});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.rupeelamp, 1), new Object[] {"xxx", "xyx", "xzx", 'x', Item.ingotIron, 'y', DivineRPG.rupee, 'z', Block.glowStone});
        //GameRegistry.addRecipe(new ItemStack(DivineRPG.purplelampoff, 1), new Object[]{"xxx", "xyx", "xzx", 'x', Item.ingotIron, 'y', new ItemStack(Item.dyePowder,1,5), 'z', Block.glowStone});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.aqualamp, 1), new Object[] {"xxx", "xyx", "xxx", 'x', Item.ingotIron, 'y', Item.bucketWater});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.blaziclamp, 1), new Object[] {"xxx", "xyx", "xxx", 'x', Item.ingotIron, 'y', Item.blazeRod});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.drakenlamp, 1), new Object[] {"xxx", "zyz", "xxx", 'x', Item.ingotIron, 'y', Item.bucketLava, 'z', Block.blockGold});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.arlemitelamp, 1), new Object[] {"xxx", "xyx", "xzx", 'x', Item.ingotIron, 'y', DivineRPG.arlemite, 'z', Block.glowStone});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.enderlamp, 1), new Object[] {"xxx", "xyx", "xxx", 'x', Item.ingotIron, 'y', Item.eyeOfEnder});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.krakenlamp, 1), new Object[] {"xxx", "xyx", "xxx", 'x', Item.ingotIron, 'y', DivineRPG.krakenSkin});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.lavalamp, 1), new Object[] {"xxx", "xyx", "xxx", 'x', Item.ingotIron, 'y', Item.bucketLava});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.milkylamp, 1), new Object[] {"xxx", "xyx", "xxx", 'x', Item.ingotIron, 'y', Item.bucketMilk});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.glowingstaircase, 1), new Object[] {"  x", " xx", "xxx", 'x', Item.lightStoneDust});
        //GameRegistry.addRecipe(new ItemStack(DivineRPG.infernoblock, 1), new Object[]{"xyx", "yxy", "xyx", 'x', Item.blazePowder, 'y', Item.redstone});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.bluetorch, 1), new Object[] {" y ", "xxx", 'x', DivineRPG.aquaticBlazeRod, 'y', Item.stick});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.bluecrystalline, 1), new Object[] {"xxx", "xyx", "xxx", 'x', Item.ingotIron, 'y', Item.diamond});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.redcrystalline, 1), new Object[] {Block.glowStone, DivineRPG.moltenStone});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.bluecrystalline, 1), new Object[] {Block.glowStone, DivineRPG.blueFireStone});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.miniBricks, 4, 4), new Object[] {Block.stoneBrick, Block.stoneBrick, Block.stoneBrick, Block.stoneBrick, Block.stoneBrick, Block.stoneBrick, Block.stoneBrick, Block.stoneBrick, Block.stoneBrick});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.miniBricks, 1, 0), new Object[] {new ItemStack(DivineRPG.miniBricks, 1, 4), DivineRPG.rupee});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.miniBricks, 1, 1), new Object[] {new ItemStack(DivineRPG.miniBricks, 1, 4), DivineRPG.realmite});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.miniBricks, 1, 2), new Object[] {new ItemStack(DivineRPG.miniBricks, 1, 4), DivineRPG.arlemite});
        //GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.miniBricks, 1, 3), new Object[]{new ItemStack(DivineRPG.miniBricks, 1, 4), plasmon});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.miniBricks, 1, 5), new Object[] {new ItemStack(DivineRPG.miniBricks, 1, 4), DivineRPG.glowingGem});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.miniBricks, 1, 6), new Object[] {new ItemStack(DivineRPG.miniBricks, 1, 4), DivineRPG.netheriteBar});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.miniBricks, 1, 8), new Object[] {new ItemStack(DivineRPG.miniBricks, 1, 4), Block.bedrock});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.spiderpumpkin, 1), new Object[] {"xxx", "xyx", "xxx", 'x', Item.silk, 'y', Block.pumpkin});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.enderpumpkin, 1), new Object[] {"xxx", "xyx", "xxx", 'x', Item.enderPearl, 'y', Block.pumpkin});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.creeperpumpkin, 1), new Object[] {"xxx", "xyx", "xxx", 'x', Item.gunpowder, 'y', Block.pumpkin});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.skeletonpumpkin, 1), new Object[] {"xxx", "xyx", "xxx", 'x', Item.bone, 'y', Block.pumpkin});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.blazepumpkin, 1), new Object[] {"xxx", "xyx", "xxx", 'x', Item.blazeRod, 'y', Block.pumpkin});
        //GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.arlemiteEssence, 2), new Object[]{arlemitebricks, arlemite});
        //GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.crystal, 1), new Object[]{crystalle});
        //GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.crystalliteWood, 1), new Object[]{crystalle, Block.wood});
        //GameRegistry.addRecipe(new ItemStack(DivineRPG.rupeestone, 1), new Object[] {"yxy", "xyx", "xyx", 'y', Item.ingotIron, 'x', DivineRPG.rupee});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.rainbowWool, 1), new Object[] {new ItemStack(Block.cloth, 1, 1), new ItemStack(Block.cloth, 1, 14), new ItemStack(Block.cloth, 1, 4), new ItemStack(Block.cloth, 1, 5), new ItemStack(Block.cloth, 1, 9), new ItemStack(Block.cloth, 1, 11), new ItemStack(Block.cloth, 1, 10)});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.lavabricks, 4), new Object[] {Block.stoneBrick, Block.stoneBrick, Block.stoneBrick, Item.bucketLava});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.waterstone, 4), new Object[] {Block.stone, Block.stone, Block.stone, Item.bucketWater});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.darkstairs, 4), new Object[] {"  x", " xx", "xxx", 'x', DivineRPG.darkbricks,});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.arlemitestairs, 4), new Object[] {"  x", " xx", "xxx", 'x', DivineRPG.arlemitebricks,});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.ironstairs, 4), new Object[] {"  x", " xx", "xxx", 'x', DivineRPG.ironbricks,});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.goldstairs, 4), new Object[] {"  x", " xx", "xxx", 'x', DivineRPG.goldbricks,});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.sandstairs, 4), new Object[] {"  x", " xx", "xxx", 'x', Block.sand,});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.redstonestairs, 4), new Object[] {"  x", " xx", "xxx", 'x', DivineRPG.redstonebricks,});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.purplebrickstairs, 4), new Object[] {"  x", " xx", "xxx", 'x', DivineRPG.purplebricks,});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.milkstonestairs, 4), new Object[] {"  x", " xx", "xxx", 'x', DivineRPG.milkstone,});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.milkstonebricksstairs, 4), new Object[] {"  x", " xx", "xxx", 'x', DivineRPG.milkstonebricks,});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.lapisstairs, 4), new Object[] {"  x", " xx", "xxx", 'x', DivineRPG.lapisbricks,});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.greenbricksstairs, 4), new Object[] {"  x", " xx", "xxx", 'x', DivineRPG.greenbricks,});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.aquatonicbricks, 4), new Object[] {DivineRPG.aquaBall, Block.stoneBrick, Block.stoneBrick, Block.stoneBrick});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.arlemitebricks, 10), new Object[] {"xyx", "yxy", "xyx", 'x', DivineRPG.arlemite, 'y', Block.stoneBrick});
        //GameRegistry.addRecipe(new ItemStack(DivineRPG.accelleron, 15), new Object[] {"xxx", "xyx", "xxx", 'x', Item.diamond, 'y', Block.torchRedstoneActive});
        //GameRegistry.addRecipe(new ItemStack(DivineRPG.accelleraunch, 1), new Object[] {"xxx", "xyx", "xxx", 'x', Item.enderPearl, 'y', DivineRPG.accelleron});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.darkplate, 1), new Object[] {"xx", 'x', DivineRPG.darkbricks,});
        //Items
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.krakenSkin, 1), new Object[] {DivineRPG.krakenScale, DivineRPG.krakenScale});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.aquaticBlazeRod, 1), new Object[] {Item.blazeRod, DivineRPG.aquaBall});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.aquaBall, 1), new Object[] {"wsw", "wkw", "wsw", 'w', Item.bucketWater, 's', Item.slimeBall, 'k', DivineRPG.krakenSkin});
        //GameRegistry.addRecipe(new ItemStack(DivineRPG.crystallon, 1), new Object[]{"ccc", " c ", "ccc", 'c', crystalle});
        //GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.crystatite, 1), new Object[]{crystallon, crystalle});
        //GameRegistry.addRecipe(new ItemStack(DivineRPG.plasmon, 1), new Object[]{"ccc", "ccc", "ccc", 'c', crystatite});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.chisel, 2), new Object[] {" x ", " y ", 'y', Item.stick, 'x', Item.ingotIron});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.healingStone, 1), new Object[] {Item.magmaCream, DivineRPG.purpleBlaze, DivineRPG.glowingGem});
        //GameRegistry.addRecipe(new ItemStack(DivineRPG.empoweredEnderPearl, 1), new Object[]{"eee", "eee", "eee", 'e', Item.enderPearl});
        //GameRegistry.addRecipe(new ItemStack(DivineRPG.empoweredEnderEye, 1), new Object[]{"eee", "eee", "eee", 'e', Item.eyeOfEnder});
        //GameRegistry.addRecipe(new ItemStack(DivineRPG.pearlOfDarkness, 1), new Object[]{"eee", "ebe", "eee", 'e', empoweredEnderPearl, 'b', Block.bedrock});
        //GameRegistry.addRecipe(new ItemStack(DivineRPG.eyeOfStrength, 1), new Object[]{"eee", "ebe", "eee", 'e', empoweredEnderEye, 'b', Block.bedrock});
        //GameRegistry.addRecipe(new ItemStack(DivineRPG.enderDust, 1), new Object[]{" x ", "xxx", "xxx", 'x', DivineRPG.enderStone});
        //GameRegistry.addRecipe(new ItemStack(DivineRPG.legendaryEnderEye, 1), new Object[]{"xxx", "xxx", "xxx", 'x', DivineRPG.eyeOfStrength});
        //GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.corruptedAquaBall, 1), new Object[]{aquaBall, empoweredEnderPearl, empoweredEnderEye});
        //GameRegistry.addRecipe(new ItemStack(DivineRPG.realmiteEye, 1), new Object[]{"xxx", "xcx", "xxx", 'x', DivineRPG.realmiteIngot, 'c', empoweredEnderEye});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.netheriteChunk, 1), new Object[] {" x ", "xxx", " x ", 'x', DivineRPG.netheriteBar});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.shadowBar, 1), new Object[] {DivineRPG.arlemite, DivineRPG.rupee});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.blackCrystallon, 1), new Object[] {"xxx", "xcx", "xxx", 'x', DivineRPG.shadowBar, 'c', Item.diamond});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.blueCrystallon, 1), new Object[] {"xxx", "xcx", "xxx", 'x', DivineRPG.rupee, 'c', Item.diamond});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.yellowCrystallon, 1), new Object[] {"xxx", "xcx", "xxx", 'x', DivineRPG.realmiteIngot, 'c', Item.diamond});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.greenCrystallon, 1), new Object[] {"xxx", "xcx", "xxx", 'x', DivineRPG.arlemite, 'c', Item.diamond});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.redCrystallon, 1), new Object[] {"xxx", "xcx", "xxx", 'x', DivineRPG.netheriteChunk, 'c', Item.diamond});
        //GameRegistry.addRecipe(new ItemStack(DivineRPG.eliteEmpoweredRealmiteEye, 1), new Object[]{"xxx", "xcx", "xxx", 'x', DivineRPG.realmite, 'c', eyeOfStrength});
        //2.0
        GameRegistry.addRecipe(new ItemStack(DivineRPG.mailStrom, 1), new Object[] {"xxx", "xyx", "xxx", 'x', DivineRPG.purpleBlaze, 'y', Item.book});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.shuriken, 4), new Object[] {Item.ingotIron});
        //GameRegistry.addRecipe(new ItemStack(DivineRPG.ghastCannon, 1), new Object[]{"xxxx", " y y", "   y", "   y", 'x', DivineRPG.hellStoneIngot, 'y', DivineRPG.shadowBar});
        //GameRegistry.addRecipe(new ItemStack(DivineRPG.frostCannon, 1), new Object[]{"xxxx", " xxy", " y y", "   y", 'x', DivineRPG.iceStone, 'y', DivineRPG.shadowBar});
        //GameRegistry.addRecipe(new ItemStack(DivineRPG.soundOfMusic, 1), new Object[]{"xxxx", "xyyx", "xyx ", "xx", 'x', DivineRPG.purpleBlaze, 'y', Item.silk});
        //GameRegistry.addRecipe(new ItemStack(DivineRPG.divinesword, 1), new Object[]{" xx ", " xx ", "yxxy", " xx ", 'x', DivineRPG.divineStone, 'y', DivineRPG.yellowShard});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.vialStorm, 4), new Object[] {DivineRPG.shuriken, DivineRPG.shuriken, DivineRPG.shuriken, DivineRPG.shuriken, DivineRPG.greenShard});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.shadowBow, 1), new Object[] {" xy", "x y", " xy", 'x', DivineRPG.shadowBar, 'y', Item.silk});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.infernoBow, 1), new Object[] {" xy", "x y", " xy", 'x', DivineRPG.moltenStone, 'y', Item.blazePowder});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.poisonBow, 1), new Object[] {" xy", "x y", " xy", 'x', DivineRPG.jungleStone, 'y', Item.silk});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.bluefirebow, 1), new Object[] {" xy", "x y", " xy", 'x', DivineRPG.aquaticBlazeRod, 'y', DivineRPG.blueFireStone});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.hellStoneIngot, 1), new Object[] {DivineRPG.shadowBar, DivineRPG.netheriteChunk});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.jungleStone, 1), new Object[] {"xxx", "xxx", "xxx", 'x', DivineRPG.greenShard});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.divineStone, 1), new Object[] {"xxx", "xxx", "xxx", 'x', DivineRPG.yellowShard});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.moltenStone, 1), new Object[] {"xxx", "xxx", "xxx", 'x', DivineRPG.redShard});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.shadowStone, 1), new Object[] {"xxx", "xxx", "xxx", 'x', DivineRPG.shadowBar});
        //GameRegistry.addRecipe(new ItemStack(DivineRPG.moltenFurnaceIdle, 1), new Object[]{"xxx", "x x", "xxx", 'x', DivineRPG.hellStoneIngot});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.spikes, 1), new Object[] {"x x", " x ", "x x", 'x', Item.ingotIron});
        //GameRegistry.addRecipe(new ItemStack(DivineRPG.elevantium, 1), new Object[] {"xxx", "xyx", "xxx", 'x', Item.eyeOfEnder, 'y', DivineRPG.accelleron});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.divinePickaxe, 1), new Object[] {"xxx", " y ", " y ", 'x', DivineRPG.divineStone, 'y', DivineRPG.shadowBar});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.divineAxe, 1), new Object[] {"xx ", "xy ", " y ", 'x', DivineRPG.divineStone, 'y', DivineRPG.shadowBar});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.divineShovel, 1), new Object[] {" x ", " y ", " y ", 'x', DivineRPG.divineStone, 'y', DivineRPG.shadowBar});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.tomatoSeeds, 4), new Object[] {DivineRPG.tomato});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.whiteMushroomSeeds, 4), new Object[] {DivineRPG.whiteMushroom});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.shadowHead, 1), new Object[] {"xxx", "x x", 'x', DivineRPG.shadowStone});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.shadowBody, 1), new Object[] {"xxx", "xxx", " x ", 'x', DivineRPG.shadowStone});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.shadowLegs, 1), new Object[] {"xxx", "x x", "x x", 'x', DivineRPG.shadowStone});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.shadowBoots, 1), new Object[] {"x x", "x x", 'x', DivineRPG.shadowStone});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.divineHead, 1), new Object[] {"xxx", "xxx", "x x", 'x', DivineRPG.divineStone});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.divineBody, 1), new Object[] {"xxx", "xxx", " x ", 'x', DivineRPG.divineStone});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.divineLegs, 1), new Object[] {"xxx", "x x", "x x", 'x', DivineRPG.divineStone});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.divineBoots, 1), new Object[] {"x x", "x x", 'x', DivineRPG.divineStone});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.angelicHead, 1), new Object[] {"yyy", "xxx", "x x", 'x', DivineRPG.iceStone, 'y', DivineRPG.blueFireStone});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.angelicBody, 1), new Object[] {"yyy", "xxx", " x ", 'x', DivineRPG.iceStone, 'y', DivineRPG.blueFireStone});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.angelicLegs, 1), new Object[] {"yyy", "x x", "x x", 'x', DivineRPG.iceStone, 'y', DivineRPG.blueFireStone});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.angelicBoots, 1), new Object[] {"y y", "x x", 'x', DivineRPG.iceStone, 'y', DivineRPG.blueFireStone});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.watcherSpawn, 1), new Object[] {" x ", "zyz", " z ", 'y', DivineRPG.watcherEye, 'x', DivineRPG.hellStoneIngot, 'z', DivineRPG.moltenStone});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.ayeracoSpawner, 1), new Object[] {" x ", "zyz", " z ", 'y', Item.eyeOfEnder, 'x', DivineRPG.hellStoneIngot, 'z', DivineRPG.enderStone});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.mysteriousClock, 1), new Object[] {" x ", "zyz", " z ", 'x', DivineRPG.hellStoneIngot, 'y', Item.pocketSundial, 'z', DivineRPG.corruptedStone});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.enderStone, 1), new Object[] {"xxx", "xxx", "xxx", 'x', DivineRPG.purpleShard});
        GameRegistry.addSmelting(DivineRPG.realmiteore.blockID, new ItemStack(DivineRPG.realmiteIngot, 1), 0.7F);
        GameRegistry.addSmelting(DivineRPG.bloodGemOre.blockID, new ItemStack(DivineRPG.glowingGem, 1), 1.0F);
        GameRegistry.addSmelting(DivineRPG.arlemiteore.blockID, new ItemStack(DivineRPG.arlemite, 1), 3.0F);
        GameRegistry.addSmelting(DivineRPG.rupeeore.blockID, new ItemStack(DivineRPG.rupee, 1), 3.0F);
        GameRegistry.addSmelting(DivineRPG.netheriteore.blockID, new ItemStack(DivineRPG.netheriteBar, 1), 1.0F);
        GameRegistry.addSmelting(DivineRPG.serenityOre.blockID, new ItemStack(DivineRPG.serenityFragments, 1), 1.0F);
        GameRegistry.addSmelting(DivineRPG.azuriteOre.blockID, new ItemStack(DivineRPG.azuriteFragments, 1), 1.0F);
        GameRegistry.addSmelting(DivineRPG.energyOre.blockID, new ItemStack(DivineRPG.energyFragments, 1), 1.0F);
        GameRegistry.addSmelting(DivineRPG.mythilOre.blockID, new ItemStack(DivineRPG.mythrilFragments, 1), 1.0F);
        GameRegistry.addSmelting(DivineRPG.denseOre.blockID, new ItemStack(DivineRPG.denseFragments, 1), 1.0F);
        GameRegistry.addSmelting(DivineRPG.serenityFragments.itemID, new ItemStack(DivineRPG.draviteSparkles, 1), 1.0F);
        GameRegistry.addRecipe(new ItemStack(DivineRPG.realmiteLamp, 1), new Object[] {"xxx", "xyx", "xzx", 'x', Item.ingotIron, 'y', DivineRPG.realmiteIngot, 'z', Block.glowStone});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.diamondLamp, 1), new Object[] {"xxx", "xyx", "xzx", 'x', Item.ingotIron, 'y', Item.diamond, 'z', Block.glowStone});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.goldenLamp, 1), new Object[] {"xxx", "xyx", "xzx", 'x', Item.ingotIron, 'y', Item.ingotGold, 'z', Block.glowStone});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.redStoneOreLamp, 1), new Object[] {"xxx", "xyx", "xzx", 'x', Item.ingotIron, 'y', Item.redstone, 'z', Block.glowStone});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.lapizLamp, 1), new Object[] {"xxx", "xyx", "xzx", 'x', Item.ingotIron, 'y', new ItemStack(Item.dyePowder, 1, 4), 'z', Block.glowStone});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.netheriteLamp, 1), new Object[] {"xxx", "xyx", "xzx", 'x', Item.ingotIron, 'y', DivineRPG.netheriteBar, 'z', Block.glowStone});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.greenTorch, 4), new Object[] {" x ", " y ", 'x', DivineRPG.serenityFragments, 'y', Item.stick});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.serenityChest, 1), new Object[] {"xxx", "x x", "xxx", 'x', DivineRPG.serenityFragments});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.energyRail, 4), new Object[] {"x x", "xxx", "x x", 'x', DivineRPG.energyFragments});
        //GameRegistry.addRecipe(new ItemStack(DivineRPG.energyCrystalRailsCurve, 4), new Object[]{"xxx", "x  ", "x x", 'x', DivineRPG.energyCrystalFragments});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.redWood, 2), new Object[] {new ItemStack(Item.dyePowder, 1, 1), Block.wood});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.purpleWood, 2), new Object[] {new ItemStack(Item.dyePowder, 1, 5), Block.wood});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.greenWood, 2), new Object[] {new ItemStack(Item.dyePowder, 1, 2), Block.wood});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.yellowWood, 2), new Object[] {new ItemStack(Item.dyePowder, 1, 11), Block.wood});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.whiteWood, 2), new Object[] {new ItemStack(Item.dyePowder, 1, 15), Block.wood});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.blueWood, 2), new Object[] {new ItemStack(Item.dyePowder, 1, 4), Block.wood});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.stoneFence, 2), new Object[] {"xxx", "xxx", 'x', DivineRPG.darkbricks});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.woodFence, 2), new Object[] {"xxx", "xxx", 'x', Block.wood});
        //GameRegistry.addRecipe(new ItemStack(DivineRPG.bloodFence, 2), new Object[]{"xxx", "yyy", 'x', Item.redstone, 'y', Block.wood});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.empoweredBlock, 1), new Object[] {"xxx", "xyx", "xxx", 'x', Item.coal, 'y', Item.eyeOfEnder});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.lightStone, 1), new Object[] {"xxx", "xxx", "xxx", 'x', Block.glowStone});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.purplestone, 1), new Object[] {"xxx", "xyx", "xxx", 'x', new ItemStack(Item.dyePowder, 1, 4), 'y', DivineRPG.redstoneBlockOn});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.clrdvane, 4, 0), new Object[] {"xxx", "xyx", "xxx", 'x', new ItemStack(Item.dyePowder, 1, 9), 'y', DivineRPG.empoweredBlock});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.clrdvane, 4, 1), new Object[] {"xxx", "xyx", "xxx", 'x', new ItemStack(Item.dyePowder, 1, 4), 'y', DivineRPG.empoweredBlock});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.clrdvane, 4, 3), new Object[] {"xxx", "xyx", "xxx", 'x', new ItemStack(Item.dyePowder, 1, 14), 'y', DivineRPG.empoweredBlock});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.clrdvane, 4, 4), new Object[] {"xxx", "xyx", "xxx", 'x', new ItemStack(Item.dyePowder, 1, 5), 'y', DivineRPG.empoweredBlock});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.clrdvane, 4, 2), new Object[] {"xxx", "xyx", "xxx", 'x', new ItemStack(Item.dyePowder, 1, 11), 'y', DivineRPG.empoweredBlock});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.empoweredBlocks, 5, 14), new Object[] {"xxx", "xxx", "xxx", 'x', new ItemStack(Block.cloth, 1, 14)});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.empoweredBlocks, 5, 10), new Object[] {"xxx", "xxx", "xxx", 'x', new ItemStack(Block.cloth, 1, 1)});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.empoweredBlocks, 5, 9), new Object[] {"xxx", "xxx", "xxx", 'x', new ItemStack(Block.cloth, 1, 11)});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.empoweredBlocks, 5, 11), new Object[] {"xxx", "xxx", "xxx", 'x', new ItemStack(Block.cloth, 1, 4)});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.empoweredBlocks, 5, 12), new Object[] {"xxx", "xxx", "xxx", 'x', new ItemStack(Block.cloth, 1, 10)});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.empoweredBlocks, 5, 13), new Object[] {"xxx", "xxx", "xxx", 'x', new ItemStack(Block.cloth, 1, 13)});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.steel, 5, 13), new Object[] {"xxx", "xyx", "xxx", 'x', new ItemStack(Block.cloth, 1, 14), 'y', new ItemStack(Block.cloth, 1, 4)});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.mud, 5), new Object[] {"xxx", "xyx", "xxx", 'x', Block.dirt, 'y', Item.bucketWater});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.yellowCrystalline, 2), new Object[] {Block.glowStone, DivineRPG.divineStone});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.greenCrystalline, 2), new Object[] {Block.glowStone, DivineRPG.jungleStone});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.orangeCrystalline, 2), new Object[] {Block.glowStone, DivineRPG.iceStone});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.purpleCrystalline, 2), new Object[] {Block.glowStone, DivineRPG.enderStone});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.diamondBricks, 4), new Object[] {Item.diamond, Block.stoneBrick, Block.stoneBrick, Block.stoneBrick});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.enderBricks, 4), new Object[] {Item.enderPearl, Block.stoneBrick, Block.stoneBrick, Block.stoneBrick});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.netheriteBlock, 1), new Object[] {"xxx", "xxx", "xxx", 'x', DivineRPG.netheriteBar});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.arlemiteBlock, 1), new Object[] {"xxx", "xxx", "xxx", 'x', DivineRPG.arlemite});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.rupeeBlock, 1), new Object[] {"xxx", "xxx", "xxx", 'x', DivineRPG.rupee});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.serenityBlock, 1), new Object[] {"xxx", "xxx", "xxx", 'x', DivineRPG.serenityFragments});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.azuriteBlock, 1), new Object[] {"xxx", "xxx", "xxx", 'x', DivineRPG.azuriteFragments});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.energyBlock, 1), new Object[] {"xxx", "xxx", "xxx", 'x', DivineRPG.energyFragments});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.mythilBlock, 1), new Object[] {"xxx", "xxx", "xxx", 'x', DivineRPG.mythrilFragments});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.denseBlock, 1), new Object[] {"xxx", "xxx", "xxx", 'x', DivineRPG.denseFragments});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.zombiePumpkin, 1), new Object[] {"xxx", "xyx", "xxx", 'y', Block.pumpkin, 'x', Item.rottenFlesh});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.iceManPumpkin, 1), new Object[] {"xxx", "xyx", "xxx", 'y', Block.pumpkin, 'x', DivineRPG.blueShard});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.cyclopsPumpkin, 1), new Object[] {"xxx", "xyx", "xxx", 'y', Block.pumpkin, 'x', Item.ingotGold});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.ghastPumpkin, 1), new Object[] {"xxx", "xyx", "xxx", 'y', Block.pumpkin, 'x', Item.ghastTear});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.frostPumpkin, 1), new Object[] {"xxx", "xyx", "xxx", 'y', Block.pumpkin, 'x', DivineRPG.iceStone});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.enderWatcherPumpkin, 1), new Object[] {"xxx", "xyx", "xxx", 'y', Block.pumpkin, 'x', DivineRPG.purpleShard});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.jungleSpiderPumpkin, 1), new Object[] {"xxx", "xyx", "xxx", 'y', Block.pumpkin, 'x', DivineRPG.greenShard});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.hellSpiderPumpkin, 1), new Object[] {"xxx", "xyx", "xxx", 'y', Block.pumpkin, 'x', DivineRPG.redShard});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.glassWhite, 2), new Object[] {new ItemStack(Item.dyePowder, 1, 15), Block.glass});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.glassOrange, 2), new Object[] {new ItemStack(Item.dyePowder, 1, 14), Block.glass});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.glassLightPurple, 2), new Object[] {new ItemStack(Item.dyePowder, 1, 13), Block.glass});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.glassLightBlue, 2), new Object[] {new ItemStack(Item.dyePowder, 1, 12), Block.glass});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.glassYellow, 2), new Object[] {new ItemStack(Item.dyePowder, 1, 11), Block.glass});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.glassLimeGreen, 2), new Object[] {new ItemStack(Item.dyePowder, 1, 10), Block.glass});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.glassPink, 2), new Object[] {new ItemStack(Item.dyePowder, 1, 9), Block.glass});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.glassGray, 2), new Object[] {new ItemStack(Item.dyePowder, 1, 8), Block.glass});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.glassLightGray, 2), new Object[] {new ItemStack(Item.dyePowder, 1, 7), Block.glass});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.glassTeal, 2), new Object[] {new ItemStack(Item.dyePowder, 1, 6), Block.glass});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.glassBlue, 2), new Object[] {new ItemStack(Item.dyePowder, 1, 4), Block.glass});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.glassPurple, 2), new Object[] {new ItemStack(Item.dyePowder, 1, 5), Block.glass});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.glassBrown, 2), new Object[] {new ItemStack(Item.dyePowder, 1, 3), Block.glass});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.glassDirtyGreen, 2), new Object[] {new ItemStack(Item.dyePowder, 1, 2), Block.glass});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.glassRed, 2), new Object[] {new ItemStack(Item.dyePowder, 1, 1), Block.glass});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.glassBlack, 2), new Object[] {new ItemStack(Item.dyePowder, 1, 0), Block.glass});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.paneBlack, 16), new Object[] {"xxx", "xxx", 'x', DivineRPG.glassBlack});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.paneRed, 16), new Object[] {"xxx", "xxx", 'x', DivineRPG.glassRed});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.paneDirtyGreen, 16), new Object[] {"xxx", "xxx", 'x', DivineRPG.glassDirtyGreen});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.paneBrown, 16), new Object[] {"xxx", "xxx", 'x', DivineRPG.glassBrown});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.panePurple, 16), new Object[] {"xxx", "xxx", 'x', DivineRPG.glassPurple});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.paneBlue, 16), new Object[] {"xxx", "xxx", 'x', DivineRPG.glassBlue});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.paneTeal, 16), new Object[] {"xxx", "xxx", 'x', DivineRPG.glassTeal});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.paneLightGray, 16), new Object[] {"xxx", "xxx", 'x', DivineRPG.glassLightGray});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.paneGray, 16), new Object[] {"xxx", "xxx", 'x', DivineRPG.glassGray});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.panePink, 16), new Object[] {"xxx", "xxx", 'x', DivineRPG.glassPink});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.paneLimeGreen, 16), new Object[] {"xxx", "xxx", 'x', DivineRPG.glassLimeGreen});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.paneYellow, 16), new Object[] {"xxx", "xxx", 'x', DivineRPG.glassYellow});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.paneLightBlue, 16), new Object[] {"xxx", "xxx", 'x', DivineRPG.glassLightBlue});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.paneLightPurple, 16), new Object[] {"xxx", "xxx", 'x', DivineRPG.glassLightPurple});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.paneOrange, 16), new Object[] {"xxx", "xxx", 'x', DivineRPG.glassOrange});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.paneWhite, 16), new Object[] {"xxx", "xxx", 'x', DivineRPG.glassWhite});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.divineRock, 1), new Object[] {DivineRPG.yellowShard, Block.stone});
        GameRegistry.addSmelting(Block.pumpkin.blockID, new ItemStack(DivineRPG.pumpkinPie, 1), 0);
        GameRegistry.addSmelting(DivineRPG.empoweredMeatRaw.itemID, new ItemStack(DivineRPG.empoweredMeatCooked, 1), 0);
        
        GameRegistry.addRecipe(new ItemStack(DivineRPG.twilightClock, 1), new Object[] {"xxx", "xxx", "xxx", 'x', Item.pocketSundial});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.spawnBase, 1), new Object[] {DivineRPG.mythrilSoul, DivineRPG.mythrilSoul, DivineRPG.mythrilSoul, DivineRPG.mythrilSoul, DivineRPG.mythrilSoul});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.spawnVamacheron, 1), new Object[] {DivineRPG.spawnBase, DivineRPG.denseSoul, DivineRPG.denseSoul, DivineRPG.denseSoul, DivineRPG.denseSoul});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.spawnKAROT, 1), new Object[] {DivineRPG.spawnBase, DivineRPG.energyCrystalSoul, DivineRPG.denseSoul, DivineRPG.denseSoul, DivineRPG.mythrilSoul});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.spawnReyvor, 1), new Object[] {DivineRPG.spawnBase, DivineRPG.denseSoul, DivineRPG.denseSoul, DivineRPG.serenitySoul, DivineRPG.azuriteSoul});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.spawnDensos, 1), new Object[] {DivineRPG.spawnBase, DivineRPG.energyCrystalSoul, DivineRPG.denseSoul, DivineRPG.azuriteSoul, DivineRPG.mythrilSoul});
        //GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.spawnDex, 1), new Object[] {spawnBase, mythrilSoul, denseSoul, energyCrystalSoul, denseSoul});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.spawnMamormeter, 1), new Object[] {"XXX", "XYX", "XXX", 'x', DivineRPG.purpleBlaze, 'y', DivineRPG.infernoSword});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.spawnZichile, 1), new Object[] {DivineRPG.spawnBase, DivineRPG.serenitySoul, DivineRPG.denseSoul, DivineRPG.serenitySoul, DivineRPG.azuriteSoul});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.spawnTwilightDemon, 1), new Object[] {DivineRPG.spawnBase, DivineRPG.denseSoul, DivineRPG.denseSoul, DivineRPG.azuriteSoul, DivineRPG.mythrilSoul});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.spawnSoulFiend, 1), new Object[] {DivineRPG.spawnBase, DivineRPG.energyCrystalSoul, DivineRPG.mythrilSoul, DivineRPG.azuriteSoul, DivineRPG.serenitySoul});
//        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.twilightEssence, 1), new Object[] {dropReyvor, dropVamacheron, dropTwilightDemon, dropDensos, dropMamormeter, dropZichile, dropSoulFiend, dropKAROT, dropDex});
//        GameRegistry.addRecipe(new ItemStack(DivineRPG.pureTwilightEssence, 1), new Object[] {"xyx", 'x', DivineRPG.twilightEssence, 'y', DivineRPG.ultimaStonePlus});
//        GameRegistry.addRecipe(new ItemStack(DivineRPG.goldFury, 1), new Object[] {"y y", "x x", "xxx", 'y', DivineRPG.orichalcum , 'x', DivineRPG.orichalcumPlus});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.iceThrower, 1), new Object[] {" y ", "yyy", " y ", 'y', DivineRPG.azuriteChunk});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.fireThrower, 1), new Object[] {" y ", "yyy", " y ", 'y', DivineRPG.serenityChunk});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.serenadeStriker, 1), new Object[] {"y  ", "yyy", "  y", 'y', Item.diamond});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.serenadeHealth, 1), new Object[] {"y  ", "yyy", "  y", 'y', DivineRPG.netheriteChunk});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.seranadeDeath, 1), new Object[] {"y  ", "yyy", "  y", 'y', DivineRPG.shadowBar});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.growthSerenade, 1), new Object[] {"y  ", "yyy", "  y", 'y', DivineRPG.arlemite});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.serenityBlade, 1), new Object[] {" y ", " y ", " x ", 'y', DivineRPG.serenityChunk, 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.serenityBlitz, 1), new Object[] {"y y", "y y", "yyy", 'y', DivineRPG.serenityChunk});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.serenityPickaxe, 1), new Object[] {"yyy", " x ", " x ", 'y', DivineRPG.serenityChunk, 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.serenityAxe, 1), new Object[] {"yy ", "yx ", " x ", 'y', DivineRPG.serenityChunk, 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.serenityShovel, 1), new Object[] {" y ", " x ", " x ", 'y', DivineRPG.serenityChunk, 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.serenityBow, 1), new Object[] {" yx", "y x", " yx", 'y', DivineRPG.serenityChunk, 'x', Item.silk});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.serenityPhaser, 1), new Object[] {" y ", "yyy", " x ", 'y', DivineRPG.serenityChunk, 'x', Item.stick});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.serenitySlicer, 40), new Object[] {DivineRPG.serenityGem});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.serenityHead, 1), new Object[] {"yyy", "yyy", "y y", 'y', DivineRPG.serenityChunk});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.serenityBody, 1), new Object[] {"yyy", "yyy", " y ", 'y', DivineRPG.serenityChunk});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.serenityLegs, 1), new Object[] {"yyy", "y y", "y y", 'y', DivineRPG.serenityChunk});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.serenityBoots, 1), new Object[] {"y y", "y y", 'y', DivineRPG.serenityChunk});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.serenityChunk, 1), new Object[] {"yyy", "y y", "y y", 'y', DivineRPG.serenityGem});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.serenityGem, 1), new Object[] {"yyy", 'y', DivineRPG.serenityFragments});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.azuriteBlade, 1), new Object[] {" y ", " y ", " x ", 'y', DivineRPG.azuriteChunk, 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.azuriteBlitz, 1), new Object[] {"y y", "y y", "yyy", 'y', DivineRPG.azuriteChunk});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.azuritePickaxe, 1), new Object[] {"yyy", " x ", " x ", 'y', DivineRPG.azuriteChunk, 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.azuriteAxe, 1), new Object[] {"yy ", "yx ", " x ", 'y', DivineRPG.azuriteChunk, 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.azuriteShovel, 1), new Object[] {" y ", " x ", " x ", 'y', DivineRPG.azuriteChunk, 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.azuriteBow, 1), new Object[] {" yx", "y x", " yx", 'y', DivineRPG.azuriteChunk, 'x', Item.silk});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.azuritePhaser, 1), new Object[] {" y ", "yyy", " x ", 'y', DivineRPG.azuriteChunk, 'x', Item.stick});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.azuriteSlicer, 40), new Object[] {DivineRPG.azuriteGem});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.azuriteHead, 1), new Object[] {"yyy", "yyy", "y y", 'y', DivineRPG.azuriteChunk});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.azuriteBody, 1), new Object[] {"yyy", "yyy", " y ", 'y', DivineRPG.azuriteChunk});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.azuriteLegs, 1), new Object[] {"yyy", "y y", "y y", 'y', DivineRPG.azuriteChunk});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.azuriteBoots, 1), new Object[] {"y y", "y y", 'y', DivineRPG.azuriteChunk});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.azuriteChunk, 1), new Object[] {"yyy", "y y", "y y", 'y', DivineRPG.azuriteGem});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.azuriteGem, 1), new Object[] {"yyy", 'y', DivineRPG.azuriteFragments});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.energyBlade, 1), new Object[] {" y ", " y ", " x ", 'y', DivineRPG.energyChunk, 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.energyBlitz, 1), new Object[] {"y y", "y y", "yyy", 'y', DivineRPG.energyChunk});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.energyPickaxe, 1), new Object[] {"yyy", " x ", " x ", 'y', DivineRPG.energyChunk, 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.energyAxe, 1), new Object[] {"yy ", "yx ", " x ", 'y', DivineRPG.energyChunk, 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.energyShovel, 1), new Object[] {" y ", " x ", " x ", 'y', DivineRPG.energyChunk, 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.energyBow, 1), new Object[] {" yx", "y x", " yx", 'y', DivineRPG.energyChunk, 'x', Item.silk});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.energyPhaser, 1), new Object[] {" y ", "yyy", " x ", 'y', DivineRPG.energyChunk, 'x', Item.stick});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.energyCrystalSlicer, 40), new Object[] {DivineRPG.energyGem});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.energyCrystalHead, 1), new Object[] {"yyy", "yyy", "y y", 'y', DivineRPG.energyChunk});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.energyCrystalBody, 1), new Object[] {"yyy", "yyy", " y ", 'y', DivineRPG.energyChunk});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.energyCrystalLegs, 1), new Object[] {"yyy", "y y", "y y", 'y', DivineRPG.energyChunk});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.energyCrystalBoots, 1), new Object[] {"y y", "y y", 'y', DivineRPG.energyChunk});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.energyChunk, 1), new Object[] {"yyy", "y y", "y y", 'y', DivineRPG.energyGem});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.energyGem, 1), new Object[] {"yyy", 'y', DivineRPG.energyFragments});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.mythrilBlade, 1), new Object[] {" y ", " y ", " x ", 'y', DivineRPG.mythrilChunk, 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.mythrilBlitz, 1), new Object[] {"y y", "y y", "yyy", 'y', DivineRPG.mythrilChunk});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.mythrilPickaxe, 1), new Object[] {"yyy", " x ", " x ", 'y', DivineRPG.mythrilChunk, 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.mythrilAxe, 1), new Object[] {"yy ", "yx ", " x ", 'y', DivineRPG.mythrilChunk, 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.mythrilShovel, 1), new Object[] {" y ", " x ", " x ", 'y', DivineRPG.mythrilChunk, 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.mythrilBow, 1), new Object[] {" yx", "y x", " yx", 'y', DivineRPG.mythrilChunk, 'x', Item.silk});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.mythrilPhaser, 1), new Object[] {" y ", "yyy", " x ", 'y', DivineRPG.mythrilChunk, 'x', Item.stick});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.mythrilSlicer, 40), new Object[] {DivineRPG.mythrilGem});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.mythrilHead, 1), new Object[] {"yyy", "yyy", "y y", 'y', DivineRPG.mythrilChunk});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.mythrilBody, 1), new Object[] {"yyy", "yyy", " y ", 'y', DivineRPG.mythrilChunk});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.mythrilLegs, 1), new Object[] {"yyy", "y y", "y y", 'y', DivineRPG.mythrilChunk});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.mythrilBoots, 1), new Object[] {"y y", "y y", 'y', DivineRPG.mythrilChunk});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.mythrilChunk, 1), new Object[] {"yyy", "y y", "y y", 'y', DivineRPG.mythrilGem});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.mythrilGem, 1), new Object[] {"yyy", 'y', DivineRPG.mythrilFragments});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.denseBlade, 1), new Object[] {" y ", " y ", " x ", 'y', DivineRPG.denseChunk, 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.denseBlitz, 1), new Object[] {"y y", "y y", "yyy", 'y', DivineRPG.denseChunk});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.densePickaxe, 1), new Object[] {"yyy", " x ", " x ", 'y', DivineRPG.denseChunk, 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.denseAxe, 1), new Object[] {"yy ", "yx ", " x ", 'y', DivineRPG.denseChunk, 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.denseShovel, 1), new Object[] {" y ", " x ", " x ", 'y', DivineRPG.denseChunk, 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.denseBow, 1), new Object[] {" yx", "y x", " yx", 'y', DivineRPG.denseChunk, 'x', Item.silk});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.densePhaser, 1), new Object[] {" y ", "yyy", " x ", 'y', DivineRPG.denseChunk, 'x', Item.stick});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.denseSlicer, 40), new Object[] {DivineRPG.denseGem});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.denseHead, 1), new Object[] {"yyy", "yyy", "y y", 'y', DivineRPG.denseChunk});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.denseBody, 1), new Object[] {"yyy", "yyy", " y ", 'y', DivineRPG.denseChunk});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.denseLegs, 1), new Object[] {"yyy", "y y", "y y", 'y', DivineRPG.denseChunk});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.denseBoots, 1), new Object[] {"y y", "y y", 'y', DivineRPG.denseChunk});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.denseChunk, 1), new Object[] {"yyy", "y y", "y y", 'y', DivineRPG.denseGem});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.denseGem, 1), new Object[] {"yyy", 'y', DivineRPG.denseFragments});
//        GameRegistry.addRecipe(new ItemStack(DivineRPG.twilightBlade, 1), new Object[] {" y ", " y ", " x ", 'y', DivineRPG.pureTwilightEssence, 'x', Item.stick});
//        GameRegistry.addRecipe(new ItemStack(DivineRPG.twilightBlitz, 1), new Object[] {"y y", "y y", "yyy", 'y', DivineRPG.pureTwilightEssence});
//        GameRegistry.addRecipe(new ItemStack(DivineRPG.twilightPickaxe, 1), new Object[] {"yyy", " x ", " x ", 'y', DivineRPG.pureTwilightEssence, 'x', Item.stick});
//        GameRegistry.addRecipe(new ItemStack(DivineRPG.twilightAxe, 1), new Object[] {"yy ", "yx ", " x ", 'y', DivineRPG.pureTwilightEssence, 'x', Item.stick});
//        GameRegistry.addRecipe(new ItemStack(DivineRPG.twilightShovel, 1), new Object[] {" y ", " x ", " x ", 'y', DivineRPG.pureTwilightEssence, 'x', Item.stick});
//        GameRegistry.addRecipe(new ItemStack(DivineRPG.twilightBow, 1), new Object[] {" yx", "y x", " yx", 'y', DivineRPG.pureTwilightEssence, 'x', Item.silk});
//        GameRegistry.addRecipe(new ItemStack(DivineRPG.twilightPhaser, 1), new Object[] {" y ", "yyy", " x ", 'y', DivineRPG.pureTwilightEssence, 'x', Item.stick});
//        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.twilightSlicer, 80), new Object[] {pureTwilightEssence});
//        GameRegistry.addRecipe(new ItemStack(DivineRPG.twilightHead, 1), new Object[] {"yyy", "yyy", "y y", 'y', DivineRPG.pureTwilightEssence});
//        GameRegistry.addRecipe(new ItemStack(DivineRPG.twilightBody, 1), new Object[] {"yyy", "yyy", " y ", 'y', DivineRPG.pureTwilightEssence});
//        GameRegistry.addRecipe(new ItemStack(DivineRPG.twilightLegs, 1), new Object[] {"yyy", "y y", "y y", 'y', DivineRPG.pureTwilightEssence});
//        GameRegistry.addRecipe(new ItemStack(DivineRPG.twilightBoots, 1), new Object[] {"y y", "y y", 'y', DivineRPG.pureTwilightEssence});
//        GameRegistry.addRecipe(new ItemStack(DivineRPG.ultimaBlade, 1), new Object[] {" y ", " y ", " x ", 'y', DivineRPG.ultimaStone, 'x', Item.stick});
//        GameRegistry.addRecipe(new ItemStack(DivineRPG.ultimaBlitz, 1), new Object[] {"y y", "y y", "yyy", 'y', DivineRPG.ultimaStone});
//        GameRegistry.addRecipe(new ItemStack(DivineRPG.ultimaBow, 1), new Object[] {" yx", "y x", " yx", 'y', DivineRPG.ultimaStone, 'x', Item.silk});
//        GameRegistry.addRecipe(new ItemStack(DivineRPG.ultimaPhaser, 1), new Object[] {" y ", "yyy", " x ", 'y', DivineRPG.ultimaStone, 'x', Item.stick});
//        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.ultimaSlicer, 20), new Object[] {ultimaStone});
//        GameRegistry.addRecipe(new ItemStack(DivineRPG.ultimaHead, 1), new Object[] {"yyy", "yyy", "y y", 'y', DivineRPG.ultimaStone});
//        GameRegistry.addRecipe(new ItemStack(DivineRPG.ultimaBody, 1), new Object[] {"yyy", "yyy", " y ", 'y', DivineRPG.ultimaStone});
//        GameRegistry.addRecipe(new ItemStack(DivineRPG.ultimaLegs, 1), new Object[] {"yyy", "y y", "y y", 'y', DivineRPG.ultimaStone});
//        GameRegistry.addRecipe(new ItemStack(DivineRPG.ultimaBoots, 1), new Object[] {"y y", "y y", 'y', DivineRPG.ultimaStone});
//        GameRegistry.addRecipe(new ItemStack(DivineRPG.ultimaStone, 1), new Object[] {"yyy", "xxx", "xxx", 'y', DivineRPG.orichalcum, 'x', DivineRPG.orichalcumPlus});
//        GameRegistry.addRecipe(new ItemStack(DivineRPG.ultimaStonePlus, 1), new Object[] {"yyy", "yyy", "yyy", 'y', DivineRPG.ultimaStone});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.empoweredBlocks, 4, 3), new Object[] {DivineRPG.yellowWood});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.empoweredBlocks, 4, 4), new Object[] {DivineRPG.redWood});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.empoweredBlocks, 4, 6), new Object[] {DivineRPG.blueWood});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.empoweredBlocks, 4, 5), new Object[] {DivineRPG.purpleWood});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.empoweredBlocks, 4, 8), new Object[] {DivineRPG.whiteWood});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.frostCannon, 1), new Object[] {"x x", "x x", "yyy", 'y', DivineRPG.iceStone, 'x', DivineRPG.shadowBar});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.ghastCannon, 1), new Object[] {"x x", "x x", "yyy", 'y', DivineRPG.hellStoneIngot, 'x', DivineRPG.shadowBar});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.soundOfMusic, 1), new Object[] {"yyy", "yxy", "yyy", 'y', DivineRPG.purpleBlaze, 'x', Item.silk});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.divinesword, 1), new Object[] {" y ", "yyy", " x ", 'y', DivineRPG.divineStone, 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.poisonSaber, 1), new Object[] {" y ", "zyz", "zxz", 'y', DivineRPG.jungleStone, 'x', Item.stick, 'z', DivineRPG.shadowBar});
        GameRegistry.addRecipe(new ItemStack(Block.bedrock, 1), new Object[] {"yyy", "yxy ", "yyy", 'y', Block.obsidian, 'x', DivineRPG.rupeeBlock});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.krakenScale, 1), new Object[] {"y y", "y y", "yyy", 'y', new ItemStack(Item.dyePowder, 1, 0)});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.redsandstairs, 4), new Object[] {"  x", " xx", "xxx", 'x', DivineRPG.redsand});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.skeletonChest, 1), new Object[] {"yyy", "y y", "yyy", 'y', Item.bone});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.deadbridge, 5), new Object[] {"yyy", "y y", "yyy", 'y', Item.lightStoneDust});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.skullTorch, 4), new Object[] {"x", "y", 'y', Item.bone, 'x', Item.coal});
        DivineRPG.RemoveRecipe(new ItemStack(Item.helmetDiamond));
        DivineRPG.RemoveRecipe(new ItemStack(Item.plateDiamond));
        DivineRPG.RemoveRecipe(new ItemStack(Item.legsDiamond));
        DivineRPG.RemoveRecipe(new ItemStack(Item.bootsDiamond));
        GameRegistry.addRecipe(new ItemStack(DivineRPG.diamondHead, 1), new Object[] {"xxx", "x x", 'x', Item.diamond});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.diamondBody, 1), new Object[] {"x x", "xxx", "xxx", 'x', Item.diamond});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.diamondLegs, 1), new Object[] {"xxx", "x x", "x x", 'x', Item.diamond});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.diamondBoots, 1), new Object[] {"x x", "x x", 'x', Item.diamond});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.serenityDust, 9), new Object[] {DivineRPG.serenityFragments});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.azuriteDust, 9), new Object[] {DivineRPG.azuriteFragments});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.mythrilDust, 9), new Object[] {DivineRPG.mythrilFragments});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.energyDust, 9), new Object[] {DivineRPG.energyFragments});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.denseDust, 9), new Object[] {DivineRPG.denseFragments});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.homeTeleporter, 1), new Object[] {"zzz", "zyz", "zzz", 'z', Item.enderPearl, 'y', Item.diamond});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.hotSpike, 1), new Object[] {"y y", " y ", "y y", 'y', DivineRPG.netheriteBar });
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.musicBox, 1), new Object[] {DivineRPG.corruptedStone, Block.jukebox});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.corruptedPickaxe, 1), new Object[] {"yyy", " x ", " x ", 'y', DivineRPG.corruptedStone , 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.corruptedShovel, 1), new Object[] {" y ", " x ", " x ", 'y', DivineRPG.corruptedStone , 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.corruptedAxe, 1), new Object[] {"yy ", "yx ", " x ", 'y', DivineRPG.corruptedStone , 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.corruptedMaul, 1), new Object[] {"yyy", "yxy", " x ", 'y', DivineRPG.corruptedStone , 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.deathBringer, 1), new Object[] {" y ", "yxy", " x ", 'y', DivineRPG.corruptedStone , 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.superEnchantMentTable, 1), new Object[] {"yyy", "xxx", "xxx", 'y', DivineRPG.corruptedStone , 'x', DivineRPG.darkstone});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.corruptedStone, 1), new Object[] {"yyy", "yyy", "yyy", 'y', DivineRPG.corruptedShards});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.musicBox, 1), new Object[] {DivineRPG.corruptedStone, Block.jukebox, Block.dirt});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.musicBox2, 1), new Object[] {DivineRPG.corruptedStone, Block.jukebox, DivineRPG.twilightStone});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.musicBox3, 1), new Object[] {DivineRPG.corruptedStone, Block.jukebox, Item.snowball});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.musicBox4, 1), new Object[] {DivineRPG.corruptedStone, Block.jukebox, Block.sand});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.musicBox5, 1), new Object[] {DivineRPG.corruptedStone, Block.jukebox, Block.netherrack});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.enderHead, 1), new Object[] {"yyy", "yyy", "y y", 'y', DivineRPG.enderStone});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.enderBody, 1), new Object[] {"yyy", "yyy", " y ", 'y', DivineRPG.enderStone});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.enderBoots, 1), new Object[] {"y y", "y y", 'y', DivineRPG.enderStone});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.enderLegs, 1), new Object[] {"yyy", "y y", "y y", 'y', DivineRPG.enderStone});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.legendaryEnderEye, 1), new Object[] {"yyy", "yyy", "yyy", 'y', DivineRPG.enderStone});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.iceStone, 1), new Object[] {"yyy", "yyy", "yyy", 'y', DivineRPG.blueShard});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.aquastriveHead, 1), new Object[] {"yyy", "yyy", "y y", 'y', DivineRPG.aquaticIngot});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.aquastriveBody, 1), new Object[] {"yyy", "yyy", " y ", 'y', DivineRPG.aquaticIngot});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.aquastriveBoots, 1), new Object[] {"y y", "y y", 'y', DivineRPG.aquaticIngot});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.aquastriveLegs, 1), new Object[] {"yyy", "y y", "y y", 'y', DivineRPG.aquaticIngot});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.moltenSword, 1), new Object[] {" y ", " y ", " x ", 'y', DivineRPG.moltenStone, 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.frostSword, 1), new Object[] {" y ", " y ", " x ", 'y', DivineRPG.iceStone, 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.enderBow, 1), new Object[] {" xz", "y z", " xz", 'x', DivineRPG.enderStone, 'y', DivineRPG.watcherEye, 'z', Item.silk});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.corruptCannon, 1), new Object[] {"yyy", "x x", 'y', DivineRPG.corruptedStone, 'x', Item.stick});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.corruptBullet, 16), new Object[] {DivineRPG.corruptedShards});
        
        GameRegistry.addRecipe(new ItemStack(DivineRPG.arcanaPortalFrame, 12), new Object[]{" x ", "yyy", " x ", 'x', DivineRPG.blueFireStone, 'y', Block.blockSteel});
        
        GameRegistry.addRecipe(new ItemStack(DivineRPG.stainedGlass, 1), new Object[] { "y  ", " x ", "   ", Character.valueOf('x'), Block.glass, Character.valueOf('y'), DivineRPG.marsineItem });
        GameRegistry.addRecipe(new ItemStack(DivineRPG.stainedGlass1, 1), new Object[] { " y ", " x ", "   ", Character.valueOf('x'), Block.glass, Character.valueOf('y'), DivineRPG.marsineItem });
        GameRegistry.addRecipe(new ItemStack(DivineRPG.stainedGlass2, 1), new Object[] { "   y", " x ", "   ", Character.valueOf('x'), Block.glass, Character.valueOf('y'), DivineRPG.marsineItem });
        GameRegistry.addRecipe(new ItemStack(DivineRPG.stainedGlass3, 1), new Object[] { "   ", "yx ", "   ", Character.valueOf('x'), Block.glass, Character.valueOf('y'), DivineRPG.marsineItem });
        GameRegistry.addRecipe(new ItemStack(DivineRPG.stainedGlass4, 1), new Object[] { "   ", " xy", "   ", Character.valueOf('x'), Block.glass, Character.valueOf('y'), DivineRPG.marsineItem });
        GameRegistry.addRecipe(new ItemStack(DivineRPG.stainedGlass5, 1), new Object[] { "   ", " x ", "y  ", Character.valueOf('x'), Block.glass, Character.valueOf('y'), DivineRPG.marsineItem });
        GameRegistry.addRecipe(new ItemStack(DivineRPG.stainedGlass6, 1), new Object[] { "   ", " x ", " y ", Character.valueOf('x'), Block.glass, Character.valueOf('y'), DivineRPG.marsineItem });
        GameRegistry.addRecipe(new ItemStack(DivineRPG.stainedGlass7, 1), new Object[] { "   ", " x ", "  y", Character.valueOf('x'), Block.glass, Character.valueOf('y'), DivineRPG.marsineItem });
    
        GameRegistry.addRecipe(new ItemStack(DivineRPG.azuriteArrow, 4), new Object[]{" y ", " x ", " z ", 'y', DivineRPG.azuriteFragments, 'x', Item.stick, 'z', Item.feather });
        GameRegistry.addRecipe(new ItemStack(DivineRPG.furyArrow, 4), new Object[]{" y ", " x ", " z ", 'y', DivineRPG.denseFragments, 'x', Item.stick, 'z', Item.feather });
        GameRegistry.addRecipe(new ItemStack(DivineRPG.ironHead, 1), new Object[] {"xxx", "x x", 'x', Item.ingotIron});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.ironBody, 1), new Object[] {"x x", "xxx", "xxx", 'x', Item.ingotIron});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.ironLegs, 1), new Object[] {"xxx", "x x", "x x", 'x', Item.ingotIron});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.ironBoots, 1), new Object[] {"x x", "x x", 'x', Item.ingotIron});
        GameRegistry.addRecipe(new ItemStack(DivineRPG.flamingFury, 1), new Object[] {"zxz", "zxz", "zyz", 'z', DivineRPG.infernoSword, 'x', DivineRPG.furyFire, 'y', DivineRPG.shadowBar});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.enderLegsBlue, 1), new Object[]{DivineRPG.enderLegs, DivineRPG.blueCrystallon});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.enderBodyBlue, 1), new Object[]{DivineRPG.enderBody, DivineRPG.blueCrystallon});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.enderHeadBlue, 1), new Object[]{DivineRPG.enderHead, DivineRPG.blueCrystallon});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.enderBootsBlue, 1), new Object[]{DivineRPG.enderBoots, DivineRPG.blueCrystallon});

        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.enderLegsRed, 1), new Object[]{DivineRPG.enderLegs, DivineRPG.redCrystallon});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.enderBodyRed, 1), new Object[]{DivineRPG.enderBody, DivineRPG.redCrystallon});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.enderHeadRed, 1), new Object[]{DivineRPG.enderHead, DivineRPG.redCrystallon});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.enderBootsRed, 1), new Object[]{DivineRPG.enderBoots, DivineRPG.redCrystallon});


        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.enderLegsYellow, 1), new Object[]{DivineRPG.enderLegs, DivineRPG.yellowCrystallon});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.enderBodyYellow, 1), new Object[]{DivineRPG.enderBody, DivineRPG.yellowCrystallon});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.enderHeadYellow, 1), new Object[]{DivineRPG.enderHead, DivineRPG.yellowCrystallon});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.enderBootsYellow, 1), new Object[]{DivineRPG.enderBoots, DivineRPG.yellowCrystallon});


        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.enderLegsBlack, 1), new Object[]{DivineRPG.enderLegs, DivineRPG.blackCrystallon});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.enderBodyBlack, 1), new Object[]{DivineRPG.enderBody, DivineRPG.blackCrystallon});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.enderHeadBlack, 1), new Object[]{DivineRPG.enderHead, DivineRPG.blackCrystallon});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.enderBootsBlack, 1), new Object[]{DivineRPG.enderBoots, DivineRPG.blackCrystallon});


        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.enderLegsGreen, 1), new Object[]{DivineRPG.enderLegs, DivineRPG.greenCrystallon});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.enderBodyGreen, 1), new Object[]{DivineRPG.enderBody, DivineRPG.greenCrystallon});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.enderHeadGreen, 1), new Object[]{DivineRPG.enderHead, DivineRPG.greenCrystallon});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.enderBootsGreen, 1), new Object[]{DivineRPG.enderBoots, DivineRPG.greenCrystallon});
        
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.plasmaLegsBlue, 1), new Object[]{DivineRPG.plasmaLegs, DivineRPG.blueCrystallon});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.plasmaBodyBlue, 1), new Object[]{DivineRPG.plasmaBody, DivineRPG.blueCrystallon});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.plasmaHeadBlue, 1), new Object[]{DivineRPG.plasmaHead, DivineRPG.blueCrystallon});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.plasmaBootsBlue, 1), new Object[]{DivineRPG.plasmaBoots, DivineRPG.blueCrystallon});

        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.plasmaLegsRed, 1), new Object[]{DivineRPG.plasmaLegs, DivineRPG.redCrystallon});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.plasmaBodyRed, 1), new Object[]{DivineRPG.plasmaBody, DivineRPG.redCrystallon});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.plasmaHeadRed, 1), new Object[]{DivineRPG.plasmaHead, DivineRPG.redCrystallon});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.plasmaBootsRed, 1), new Object[]{DivineRPG.plasmaBoots, DivineRPG.redCrystallon});


        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.plasmaLegsYellow, 1), new Object[]{DivineRPG.plasmaLegs, DivineRPG.yellowCrystallon});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.plasmaBodyYellow, 1), new Object[]{DivineRPG.plasmaBody, DivineRPG.yellowCrystallon});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.plasmaHeadYellow, 1), new Object[]{DivineRPG.plasmaHead, DivineRPG.yellowCrystallon});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.plasmaBootsYellow, 1), new Object[]{DivineRPG.plasmaBoots, DivineRPG.yellowCrystallon});


        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.plasmaLegsBlack, 1), new Object[]{DivineRPG.plasmaLegs, DivineRPG.blackCrystallon});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.plasmaBodyBlack, 1), new Object[]{DivineRPG.plasmaBody, DivineRPG.blackCrystallon});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.plasmaHeadBlack, 1), new Object[]{DivineRPG.plasmaHead, DivineRPG.blackCrystallon});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.plasmaBootsBlack, 1), new Object[]{DivineRPG.plasmaBoots, DivineRPG.blackCrystallon});


        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.plasmaLegsGreen, 1), new Object[]{DivineRPG.plasmaLegs, DivineRPG.greenCrystallon});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.plasmaBodyGreen, 1), new Object[]{DivineRPG.plasmaBody, DivineRPG.greenCrystallon});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.plasmaHeadGreen, 1), new Object[]{DivineRPG.plasmaHead, DivineRPG.greenCrystallon});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.plasmaBootsGreen, 1), new Object[]{DivineRPG.plasmaBoots, DivineRPG.greenCrystallon});
        
        GameRegistry.addShapelessRecipe(new ItemStack(Block.stone, 9), new Object[]{new ItemStack(DivineRPG.iceblock, 1, 4)});
        GameRegistry.addShapelessRecipe(new ItemStack(Block.slowSand, 9), new Object[]{new ItemStack(DivineRPG.iceblock, 1, 6)});
        GameRegistry.addShapelessRecipe(new ItemStack(Block.ice, 9), new Object[]{new ItemStack(DivineRPG.iceblock, 1, 0)});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.rupee, 9), new Object[]{DivineRPG.rupeeBlock});
        GameRegistry.addShapelessRecipe(new ItemStack(Block.sand, 9), new Object[]{ new ItemStack(DivineRPG.iceblock, 1, 5)});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.netheriteBar, 9), new Object[]{DivineRPG.netheriteBlock});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.arlemite, 9), new Object[]{DivineRPG.arlemiteBlock});
        GameRegistry.addShapelessRecipe(new ItemStack(Block.obsidian, 9), new Object[]{DivineRPG.obsidianblock});
        GameRegistry.addShapelessRecipe(new ItemStack(Item.flint, 9), new Object[]{new ItemStack(DivineRPG.iceblock, 1, 1)});
        GameRegistry.addShapelessRecipe(new ItemStack(Block.dirt, 9), new Object[]{new ItemStack(DivineRPG.iceblock, 1, 7)});
        GameRegistry.addShapelessRecipe(new ItemStack(Block.gravel, 9), new Object[]{new ItemStack(DivineRPG.iceblock, 1, 2)});
        GameRegistry.addShapelessRecipe(new ItemStack(Item.coal, 9), new Object[]{new ItemStack(DivineRPG.iceblock, 1, 3)});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.realmiteIngot, 9), new Object[]{DivineRPG.realmite});
        
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.serenityFragments, 1), new Object[]{DivineRPG.serenitySoul});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.azuriteFragments, 1), new Object[]{DivineRPG.azuriteSoul});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.energyFragments, 1), new Object[]{DivineRPG.energyCrystalSoul});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.mythrilFragments, 1), new Object[]{DivineRPG.mythrilSoul});
        GameRegistry.addShapelessRecipe(new ItemStack(DivineRPG.denseFragments, 1), new Object[]{DivineRPG.denseSoul});
	}

}