package xolova.divinerpg.utils.helpers.block;

import net.minecraft.block.Block;
import net.minecraft.block.BlockGlass;
import net.minecraft.block.material.Material;
import xolova.divinerpg.blocks.vethea.BlockAcid;
import xolova.divinerpg.blocks.vethea.BlockBacterialAcid;
import xolova.divinerpg.blocks.vethea.BlockBarredDoor;
import xolova.divinerpg.blocks.vethea.BlockDreamLamp;
import xolova.divinerpg.blocks.vethea.BlockDreamgrass;
import xolova.divinerpg.blocks.vethea.BlockDreamwood;
import xolova.divinerpg.blocks.vethea.BlockDreamwoodLeaves;
import xolova.divinerpg.blocks.vethea.BlockHelioticBeam;
import xolova.divinerpg.blocks.vethea.BlockInfusionTable;
import xolova.divinerpg.blocks.vethea.BlockKarosAltar;
import xolova.divinerpg.blocks.vethea.BlockKarosCannon;
import xolova.divinerpg.blocks.vethea.BlockKarosHeatTileGreen;
import xolova.divinerpg.blocks.vethea.BlockKarosHeatTileRed;
import xolova.divinerpg.blocks.vethea.BlockLunicAcid;
import xolova.divinerpg.blocks.vethea.BlockLunicAltar;
import xolova.divinerpg.blocks.vethea.BlockPurpleFire;
import xolova.divinerpg.blocks.vethea.BlockRaglokAltar;
import xolova.divinerpg.blocks.vethea.BlockShimmer;
import xolova.divinerpg.blocks.vethea.BlockVetheaPlant;
import xolova.divinerpg.blocks.vethea.BlockWeedwoodVine;
import xolova.divinerpg.blocks.vethea.BlockWreckAltar;
import xolova.divinerpg.utils.helpers.config.VetheaConfigHelper;
import xolova.divinerpg.utils.helpers.gui.CreativeTabHelper;

public class VetheaBlockHelper 
{
	public static Block vetheaPortal;
    public static Block dreamstone;
    public static Block dreamgrass;
    public static Block dreamdirt;
    public static Block dreamwood;
    public static Block dreamwoodLeaves;
    public static Block dreambricks;
    public static Block dreambricks2;
    public static Block lunastone;
    public static Block lunabricks;
    public static Block metalCaging;
    public static Block dreamlamp;
    public static Block dreamlampOn;
    public static Block weedwoodVine;
    public static Block blossomingWeedwoodVine;
    public static Block cryptWall;
    public static Block smoothGlass;
    public static Block villageLamp;
    public static Block infusionTable;
    public static Block cellLamp;
    public static Block barredDoor;
    public static Block firecrystal;
    public static Block firelight;
    public static Block hyrewood;
    public static Block mintwoodLeaves;
    public static Block firewall;
    public static Block karosHeatTileRed;
    public static Block karosHeatTileGreen;
    public static BlockKarosCannon karosCannon;
    public static BlockHelioticBeam helioticBeam;
    public static Block cryptFloor;
    public static Block firewood;
    public static Block bacterialAcid;
    public static Block blockAcid;
    public static Block hallWall;
    public static Block wreckAltar;
    public static Block raglokAltar;
    public static Block karosAltar;
    public static Block lunicAltar;
    public static Block hiveWall;
    public static Block quadroticAltar;
    public static Block everstone;
    public static Block lunicAcid;
    public static Block firewoodLeaves;
    public static Block hyrewoodLeaves;
    public static Block gemtopGreen;
    public static Block gemtopPurple;
    public static Block greenDulah;
    public static Block yellowDulah;
    public static Block mintwood;
    public static Block lightFirewoodLeaves;
    public static Block cracklespike;
    public static Block fernite;
    public static Block bulatobe;
    public static Block shineGrass;
    public static Block shimmer;
    public static Block dreamglow;
    public static Block hyrewoodVine;
    public static Block chamberWall;
    public static Block chamberWall1;
    public static Block chamberWall2;
    public static Block darkEverstone;
    public static Block whiteEverstone;
    public static Block karosBricks;
    public static Block karosBricks2;
    public static Block hungerstone1;
    public static Block hungerstone2;
    public static Block biphronSpawner;
    public static Block gorgosionSpawner;
    public static Block duoSpawner;
    public static Block twinsSpawner;
    public static Block vermenousSpawner;
    public static Block dreamwreckerSpawner;
    public static Block lorgaSpawner;
    public static Block purpleFire;
	
    public static void initBlocks()
	{
    	dreamstone = new Block(VetheaConfigHelper.dreamstoneID, 9, Material.rock).setUnlocalizedName("dreamstone").setHardness(1F).setResistance(1F).setCreativeTab(CreativeTabHelper.tabBlocks);
        dreamdirt = new Block(VetheaConfigHelper.dreamdirtID, 11, Material.ground).setUnlocalizedName("dreamdirt").setHardness(1F).setResistance(1F).setCreativeTab(CreativeTabHelper.tabBlocks);
        dreamgrass = new BlockDreamgrass(VetheaConfigHelper.dreamgrassID).setUnlocalizedName("dreamgrass").setHardness(1F).setResistance(1F).setCreativeTab(CreativeTabHelper.tabBlocks);
        dreamwood = new BlockDreamwood(VetheaConfigHelper.dreamwoodID).setUnlocalizedName("dreamwood").setHardness(1F).setResistance(1F).setCreativeTab(CreativeTabHelper.tabBlocks);
        dreamwoodLeaves = new BlockDreamwoodLeaves(VetheaConfigHelper.dreamwoodLeavesID, 14).setUnlocalizedName("dreamwoodLeaves").setHardness(1F).setCreativeTab(CreativeTabHelper.tabBlocks);
        dreambricks = new Block(VetheaConfigHelper.dreambricksID, 25, Material.rock).setUnlocalizedName("dreambricks").setHardness(1F).setResistance(1F).setCreativeTab(CreativeTabHelper.tabBlocks);
        lunastone = new Block(VetheaConfigHelper.lunastoneID, 27, Material.rock).setBlockUnbreakable().setUnlocalizedName("lunastone").setHardness(1F).setResistance(1F).setCreativeTab(CreativeTabHelper.tabBlocks);
        lunabricks = new Block(VetheaConfigHelper.lunabricksID, 28, Material.rock).setBlockUnbreakable().setUnlocalizedName("lunabricks").setHardness(1F).setResistance(1F).setCreativeTab(CreativeTabHelper.tabBlocks);
        metalCaging = new Block(VetheaConfigHelper.metalCagingID, 29, Material.rock).setUnlocalizedName("metalCaging").setHardness(1F).setResistance(1F).setCreativeTab(CreativeTabHelper.tabBlocks);
        dreamlampOn = new BlockDreamLamp(VetheaConfigHelper.dreamlampOnID, 30, Material.glass, true).setBlockUnbreakable().setUnlocalizedName("dreamlampOn").setHardness(1F).setResistance(1F);
        dreamlamp = new BlockDreamLamp(VetheaConfigHelper.dreamlampID, 31, Material.glass, false).setBlockUnbreakable().setUnlocalizedName("dreamlamp").setHardness(1F).setStepSound(Block.soundGlassFootstep).setResistance(1F).setCreativeTab(CreativeTabHelper.tabBlocks);
        weedwoodVine = new BlockWeedwoodVine(VetheaConfigHelper.weedwoodVineID, 41).setUnlocalizedName("weedwoodVine").setHardness(1F).setResistance(1F).setCreativeTab(CreativeTabHelper.tabBlocks);
        blossomingWeedwoodVine = new BlockWeedwoodVine(VetheaConfigHelper.blossomingWeedwoodVineID, 42).setUnlocalizedName("blossomingWeedwoodVine").setHardness(1F).setResistance(1F).setCreativeTab(CreativeTabHelper.tabBlocks);
        cryptWall = new Block(VetheaConfigHelper.cryptWallID, 43, Material.rock).setBlockUnbreakable().setUnlocalizedName("cryptWall").setHardness(1F).setResistance(1F).setCreativeTab(CreativeTabHelper.tabBlocks);
        smoothGlass = new BlockGlass(VetheaConfigHelper.smoothGlassID, 44, Material.glass, true).setStepSound(Block.soundGlassFootstep).setUnlocalizedName("smoothGlass").setHardness(1F).setCreativeTab(CreativeTabHelper.tabBlocks);
        villageLamp = new Block(VetheaConfigHelper.villageLampID, 45, Material.glass).setUnlocalizedName("villageLamp").setLightValue(1.0F).setStepSound(Block.soundGlassFootstep).setHardness(1F).setCreativeTab(CreativeTabHelper.tabBlocks);
        cellLamp = new Block(VetheaConfigHelper.cellLampID, 57, Material.glass).setUnlocalizedName("cellLamp").setLightValue(1.0F).setStepSound(Block.soundGlassFootstep).setHardness(1F).setCreativeTab(CreativeTabHelper.tabBlocks);
        barredDoor = new BlockBarredDoor(VetheaConfigHelper.barredDoorID, Material.iron, 58).setUnlocalizedName("barredDoor").setHardness(1F).setResistance(1F).setCreativeTab(CreativeTabHelper.tabBlocks);
        firecrystal = new Block(VetheaConfigHelper.firecrystalID, 60, Material.glass).setLightValue(0.7F).setUnlocalizedName("firecrystal").setStepSound(Block.soundGlassFootstep).setHardness(1F).setCreativeTab(CreativeTabHelper.tabBlocks);
        firelight = new Block(VetheaConfigHelper.firelightID, 60, Material.glass).setUnlocalizedName("firelight").setLightValue(1.0F).setStepSound(Block.soundGlassFootstep).setHardness(1F).setResistance(1.0F).setCreativeTab(CreativeTabHelper.tabBlocks);
        hyrewood = new BlockDreamwood(VetheaConfigHelper.hyrewoodID).setUnlocalizedName("hyrewood").setHardness(1F).setResistance(1F).setCreativeTab(CreativeTabHelper.tabBlocks);
        mintwoodLeaves = new BlockDreamwoodLeaves(mintwoodLeavesID, 63).setUnlocalizedName("mintwoodLeaves").setHardness(1F).setCreativeTab(CreativeTabHelper.tabBlocks);
        firewall = new Block(VetheaConfigHelper.firewallID, 73, Material.rock).setUnlocalizedName("firewall").setHardness(1F).setResistance(1F).setCreativeTab(CreativeTabHelper.tabBlocks);
        karosHeatTileGreen = new BlockKarosHeatTileGreen(VetheaConfigHelper.karosHeatTileGreenID, false, 75).setBlockUnbreakable().setUnlocalizedName("karosHeatTileGreen").setHardness(1F).setCreativeTab(CreativeTabHelper.tabBlocks);
        karosHeatTileRed = new BlockKarosHeatTileRed(VetheaConfigHelper.karosHeatTileRedID, true, 74).setBlockUnbreakable().setUnlocalizedName("karosHeatTileRed").setHardness(1F).setCreativeTab(CreativeTabHelper.tabBlocks);
        firewood = new BlockDreamwood(VetheaConfigHelper.firewoodID).setUnlocalizedName("firewood").setHardness(1F).setResistance(1F).setCreativeTab(CreativeTabHelper.tabBlocks);
        bacterialAcid = new BlockBacterialAcid(VetheaConfigHelper.bacterialAcidID, 105).setUnlocalizedName("bacterialAcid").setHardness(1F).setResistance(1F).setCreativeTab(CreativeTabHelper.tabBlocks);
        blockAcid = new BlockAcid(VetheaConfigHelper.blockAcidID, 108).setUnlocalizedName("blockAcid").setHardness(1F).setResistance(1F).setCreativeTab(CreativeTabHelper.tabBlocks);
        everstone = new Block(VetheaConfigHelper.everstoneID, 140, Material.rock).setBlockUnbreakable().setUnlocalizedName("everstone").setHardness(1F).setResistance(1F).setCreativeTab(CreativeTabHelper.tabBlocks);
        lunicAcid = new BlockLunicAcid(VetheaConfigHelper.lunicAcidID, 141).setUnlocalizedName("lunicAcid").setHardness(1F).setResistance(1F).setCreativeTab(CreativeTabHelper.tabBlocks);
        firewoodLeaves = new BlockDreamwoodLeaves(VetheaConfigHelper.firewoodLeavesID, 142).setUnlocalizedName("firewoodLeaves").setHardness(1F).setCreativeTab(CreativeTabHelper.tabBlocks);
        hyrewoodLeaves = new BlockDreamwoodLeaves(VetheaConfigHelper.hyrewoodLeavesID, 143).setUnlocalizedName("hyrewoodLeaves").setHardness(1F).setCreativeTab(CreativeTabHelper.tabBlocks);
        gemtopGreen = new BlockVetheaPlant(VetheaConfigHelper.gemtopGreenID, 153).setUnlocalizedName("gemtopGreen").setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(tabHerb);
        gemtopPurple = new BlockVetheaPlant(VetheaConfigHelper.gemtopPurpleID, 154).setUnlocalizedName("gemtopPurple").setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(tabHerb);
        yellowDulah = new BlockVetheaPlant(VetheaConfigHelper.yellowDulahID, 155).setUnlocalizedName("yellowDulah").setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(tabHerb);
        greenDulah = new BlockVetheaPlant(VetheaConfigHelper.greenDulahID, 156).setUnlocalizedName("greenDulah").setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(tabHerb);
        mintwood = new BlockDreamwood(VetheaConfigHelper.mintwoodID).setUnlocalizedName("mint").setHardness(1F).setResistance(1F).setCreativeTab(CreativeTabHelper.tabBlocks);
        lightFirewoodLeaves = new BlockDreamwoodLeaves(VetheaConfigHelper.lightFirewoodLeavesID, 158).setUnlocalizedName("lightFirewoodLeaves").setHardness(1F).setCreativeTab(CreativeTabHelper.tabBlocks);
        cracklespike = new BlockVetheaPlant(VetheaConfigHelper.cracklespikeID, 169).setUnlocalizedName("cracklespike").setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(tabHerb);
        fernite = new BlockVetheaPlant(VetheaConfigHelper.ferniteID, 170).setUnlocalizedName("fernite").setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(tabHerb);
        bulatobe = new BlockVetheaPlant(VetheaConfigHelper.bulatobeID, 171).setUnlocalizedName("bulatobe").setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(tabHerb);
        shineGrass = new BlockVetheaPlant(VetheaConfigHelper.shineGrassID, 172).setUnlocalizedName("shineGrass").setLightValue(0.4F).setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(tabHerb);
        shimmer = new BlockShimmer(VetheaConfigHelper.shimmerID, 173).setLightValue(0.4F).setUnlocalizedName("shimmer").setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(tabHerb);
        hiveWall = new Block(VetheaConfigHelper.hiveWallID, 127, Material.glass).setLightValue(0.533F).setUnlocalizedName("dreamlampOn").setHardness(1F).setResistance(1F).setCreativeTab(CreativeTabHelper.tabBlocks);
        dreamglow = new BlockShimmer(VetheaConfigHelper.dreamglowID, 174).setLightValue(0.4F).setUnlocalizedName("dreamglow").setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(tabHerb);
        hyrewoodVine = new BlockWeedwoodVine(VetheaConfigHelper.hyrewoodVineID, 175).setUnlocalizedName("hyrewoodVine").setHardness(1F).setResistance(1F).setCreativeTab(CreativeTabHelper.tabBlocks);
        dreambricks2 = new Block(VetheaConfigHelper.dreambricks2ID, 26, Material.rock).setUnlocalizedName("dreambricks").setHardness(1F).setResistance(1F).setCreativeTab(CreativeTabHelper.tabBlocks);
        chamberWall = new Block(VetheaConfigHelper.chamberWallID, 91, Material.rock).setBlockUnbreakable().setUnlocalizedName("chamberWall").setHardness(1F).setResistance(1F).setCreativeTab(CreativeTabHelper.tabBlocks);
        chamberWall1 = new Block(VetheaConfigHelper.chamberWall1ID, 92, Material.rock).setBlockUnbreakable().setUnlocalizedName("chamberWall1").setHardness(1F).setResistance(1F).setCreativeTab(CreativeTabHelper.tabBlocks);
        chamberWall2 = new Block(VetheaConfigHelper.chamberWall2ID, 93, Material.rock).setBlockUnbreakable().setUnlocalizedName("chamberWall2").setHardness(1F).setResistance(1F).setCreativeTab(CreativeTabHelper.tabBlocks);
        whiteEverstone = new Block(VetheaConfigHelper.whiteEverstoneID, 139, Material.rock).setBlockUnbreakable().setUnlocalizedName("whiteEverstone").setHardness(1F).setResistance(1F).setCreativeTab(CreativeTabHelper.tabBlocks);
        darkEverstone = new Block(VetheaConfigHelper.darkEverstoneID, 138, Material.rock).setBlockUnbreakable().setUnlocalizedName("darkEverstone").setHardness(1F).setResistance(1F).setCreativeTab(CreativeTabHelper.tabBlocks);
        wreckAltar = new BlockWreckAltar(VetheaConfigHelper.wreckAltarID).setUnlocalizedName("wreckAltar").setBlockUnbreakable().setResistance(999F).setCreativeTab(CreativeTabHelper.tabBlocks);
        raglokAltar = new BlockRaglokAltar(VetheaConfigHelper.raglokAltarID).setUnlocalizedName("raglokAltar").setBlockUnbreakable().setResistance(999F).setCreativeTab(CreativeTabHelper.tabBlocks);
        karosAltar = new BlockKarosAltar(VetheaConfigHelper.karosAltarID).setUnlocalizedName("karosAltar").setBlockUnbreakable().setResistance(999F).setCreativeTab(CreativeTabHelper.tabBlocks);
        lunicAltar = new BlockLunicAltar(VetheaConfigHelper.lunicAltarID).setUnlocalizedName("lunicAltar").setBlockUnbreakable().setResistance(999F).setCreativeTab(CreativeTabHelper.tabBlocks);
        quadroticAltar = new Block(VetheaConfigHelper.quadroticAltarID, 137, Material.rock).setUnlocalizedName("quadroticAltar").setBlockUnbreakable().setResistance(999F).setCreativeTab(CreativeTabHelper.tabBlocks);
        infusionTable = new BlockInfusionTable(VetheaConfigHelper.infusionTableID).setBlockUnbreakable().setUnlocalizedName("infusionTable").setBlockUnbreakable().setResistance(999F).setCreativeTab(CreativeTabHelper.tabBlocks);
        hungerstone1 = new Block(VetheaConfigHelper.hungerstone1ID, 106, Material.rock).setUnlocalizedName("hungerstone1").setHardness(1F).setResistance(1F).setCreativeTab(CreativeTabHelper.tabBlocks);
        hungerstone2 = new Block(VetheaConfigHelper.hungerstone2ID, 107, Material.rock).setUnlocalizedName("hungerstone2").setHardness(1F).setResistance(1F).setCreativeTab(CreativeTabHelper.tabBlocks);
        cryptFloor = new Block(VetheaConfigHelper.cryptFloorID, 79, Material.rock).setBlockUnbreakable().setUnlocalizedName("cryptFloor").setHardness(1F).setResistance(1F).setCreativeTab(CreativeTabHelper.tabBlocks);
        hallWall = new Block(VetheaConfigHelper.hallWallID, 109, Material.rock).setBlockUnbreakable().setUnlocalizedName("hallWall").setHardness(1F).setResistance(1F).setCreativeTab(CreativeTabHelper.tabBlocks);
        karosBricks = new Block(VetheaConfigHelper.karosBricksID, 94, Material.rock).setBlockUnbreakable().setUnlocalizedName("karosBricks").setHardness(1F).setResistance(1F).setCreativeTab(CreativeTabHelper.tabBlocks);
        karosBricks2 = new Block(VetheaConfigHelper.karosBricks2ID, 95, Material.rock).setBlockUnbreakable().setUnlocalizedName("karosBricks2").setHardness(1F).setResistance(1F).setCreativeTab(CreativeTabHelper.tabBlocks);
        helioticBeam = (BlockHelioticBeam) new BlockHelioticBeam(VetheaConfigHelper.helioticBeamID).setUnlocalizedName("helioticBeam").setHardness(1F).setResistance(1F).setCreativeTab(CreativeTabHelper.tabBlocks);
        karosCannon = (BlockKarosCannon) new BlockKarosCannon(VetheaConfigHelper.karosCannonID, 76, Material.rock).setBlockUnbreakable().setUnlocalizedName("karosCannon").setHardness(1F).setResistance(1F).setCreativeTab(tabUtility).setRequiresSelfNotify();
        purpleFire = new BlockPurpleFire(VetheaConfigHelper.purpleFireID, 94).setUnlocalizedName("purpleFire").setCreativeTab(CreativeTabHelper.tabBlocks);
	}
}
