package net.divinerpg.utils.helpers.block;

import net.divinerpg.blocks.core.BlockDivinePortal;
import net.divinerpg.blocks.core.DivineGrass;
import net.divinerpg.blocks.vethea.BlockAcid;
import net.divinerpg.blocks.vethea.BlockBacterialAcid;
import net.divinerpg.blocks.vethea.BlockBarredDoor;
import net.divinerpg.blocks.vethea.BlockDreamLamp;
import net.divinerpg.blocks.vethea.BlockDreamwood;
import net.divinerpg.blocks.vethea.BlockDreamwoodLeaves;
import net.divinerpg.blocks.vethea.BlockHelioticBeam;
import net.divinerpg.blocks.vethea.BlockInfusionTable;
import net.divinerpg.blocks.vethea.BlockKarosAltar;
import net.divinerpg.blocks.vethea.BlockKarosCannon;
import net.divinerpg.blocks.vethea.BlockKarosHeatTileGreen;
import net.divinerpg.blocks.vethea.BlockKarosHeatTileRed;
import net.divinerpg.blocks.vethea.BlockLunicAcid;
import net.divinerpg.blocks.vethea.BlockLunicAltar;
import net.divinerpg.blocks.vethea.BlockPurpleFire;
import net.divinerpg.blocks.vethea.BlockRaglokAltar;
import net.divinerpg.blocks.vethea.BlockShimmer;
import net.divinerpg.blocks.vethea.BlockSmoothGlass;
import net.divinerpg.blocks.vethea.BlockVethea;
import net.divinerpg.blocks.vethea.BlockVetheaMetalCage;
import net.divinerpg.blocks.vethea.BlockVetheaPlant;
import net.divinerpg.blocks.vethea.BlockWeedwoodVine;
import net.divinerpg.blocks.vethea.BlockWreckAltar;
import net.divinerpg.blocks.vethea.tileentities.TileEntityDreamLamp;
import net.divinerpg.blocks.vethea.tileentities.TileEntityInfusionTable;
import net.divinerpg.utils.helpers.config.VetheaConfigHelper;
import net.divinerpg.utils.helpers.gui.DivineTabs;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.common.registry.LanguageRegistry;

public class VetheaBlockHelper 
{
	public static Block vetheaPortal;
    public static Block dreamstone;
    public static Block dreamgrass;
    public static Block dreamdirt;
    public static Block dreamwood;
    public static Block dreamwoodLeaves;
    public static Block dreambricks;
    public static Block dreambricks2;
    public static Block lunastone;
    public static Block lunabricks;
    public static Block metalCaging;
    public static Block dreamlamp;
    public static Block dreamlampOn;
    public static Block weedwoodVine;
    public static Block blossomingWeedwoodVine;
    public static Block cryptWall;
    public static Block smoothGlass;
    public static Block villageLamp;
    public static Block infusionTable;
    public static Block cellLamp;
    public static Block barredDoor;
    public static Block firecrystal;
    public static Block firelight;
    public static Block hyrewood;
    public static Block mintwoodLeaves;
    public static Block firewall;
    public static Block karosHeatTileRed;
    public static Block karosHeatTileGreen;
    public static BlockKarosCannon karosCannon;
    public static BlockHelioticBeam helioticBeam;
    public static Block cryptFloor;
    public static Block firewood;
    public static Block bacterialAcid;
    public static Block blockAcid;
    public static Block hallWall;
    public static Block wreckAltar;
    public static Block raglokAltar;
    public static Block karosAltar;
    public static Block lunicAltar;
    public static Block hiveWall;
    public static Block quadroticAltar;
    public static Block everstone;
    public static Block lunicAcid;
    public static Block firewoodLeaves;
    public static Block hyrewoodLeaves;
    public static Block gemtopGreen;
    public static Block gemtopPurple;
    public static Block greenDulah;
    public static Block yellowDulah;
    public static Block mintwood;
    public static Block lightFirewoodLeaves;
    public static Block cracklespike;
    public static Block fernite;
    public static Block bulatobe;
    public static Block shineGrass;
    public static Block shimmer;
    public static Block dreamglow;
    public static Block hyrewoodVine;
    public static Block chamberWall1;
    public static Block chamberWall2;
    public static Block chamberWall3;
    public static Block darkEverstone;
    public static Block whiteEverstone;
    public static Block karosBricks;
    public static Block karosBricks2;
    public static Block hungerstone1;
    public static Block hungerstone2;
    public static Block biphronSpawner;
    public static Block gorgosionSpawner;
    public static Block duoSpawner;
    public static Block twinsSpawner;
    public static Block vermenousSpawner;
    public static Block dreamwreckerSpawner;
    public static Block lorgaSpawner;
    public static Block purpleFire;
    
    public static Block moonBulbBase;
	
    public static void initBlocks()
	{
    	vetheaPortal = new BlockDivinePortal(VetheaConfigHelper.vetheaPortalID).func_111022_d("VetheaPortal").setUnlocalizedName("Vethea Portal").setCreativeTab(DivineTabs.tabBlocks);
    	dreamstone = new BlockVethea(VetheaConfigHelper.dreamstoneID, 9, Material.rock).func_111022_d("DreamStone").setUnlocalizedName("dreamstone").setHardness(1F).setResistance(1F).setCreativeTab(DivineTabs.tabBlocks);
        dreamdirt = new BlockVethea(VetheaConfigHelper.dreamdirtID, 11, Material.ground).func_111022_d("DreamGrass_Bottom").setUnlocalizedName("dreamdirt").setHardness(1F).setResistance(1F).setCreativeTab(DivineTabs.tabBlocks);
        dreamgrass = new DivineGrass(VetheaConfigHelper.dreamgrassID, dreamdirt).func_111022_d("DreamGrass").setUnlocalizedName("dreamgrass").setHardness(1F).setResistance(1F).setCreativeTab(DivineTabs.tabBlocks);
        dreamwood = new BlockDreamwood(VetheaConfigHelper.dreamwoodID).func_111022_d("DreamWood").setUnlocalizedName("dreamwood").setHardness(1F).setResistance(1F).setCreativeTab(DivineTabs.tabBlocks);
        dreamwoodLeaves = new BlockDreamwoodLeaves(VetheaConfigHelper.dreamwoodLeavesID).func_111022_d("DreamwoodLeaves").setUnlocalizedName("dreamwoodLeaves").setHardness(1F).setCreativeTab(DivineTabs.tabBlocks);
        dreambricks = new BlockVethea(VetheaConfigHelper.dreambricksID, 25, Material.rock).func_111022_d("DreamBricks1").setUnlocalizedName("dreambricks").setHardness(1F).setResistance(1F).setCreativeTab(DivineTabs.tabBlocks);
        dreambricks2 = new BlockVethea(VetheaConfigHelper.dreambricks2ID, 26, Material.rock).func_111022_d("DreamBricks2").setUnlocalizedName("dreambricks").setHardness(1F).setResistance(1F).setCreativeTab(DivineTabs.tabBlocks);
        lunastone = new BlockVethea(VetheaConfigHelper.lunastoneID, 27, Material.rock).setBlockUnbreakable().setUnlocalizedName("lunastone").setHardness(1F).setResistance(1F).setCreativeTab(DivineTabs.tabBlocks);//TODO get a texure
        lunabricks = new BlockVethea(VetheaConfigHelper.lunabricksID, 28, Material.rock).func_111022_d("LunaBrick").setBlockUnbreakable().setUnlocalizedName("lunabricks").setHardness(1F).setResistance(1F).setCreativeTab(DivineTabs.tabBlocks);
        metalCaging = new BlockVetheaMetalCage(VetheaConfigHelper.metalCagingID, 29, Material.rock).func_111022_d("MetalCaging").setUnlocalizedName("metalCaging").setHardness(1F).setResistance(1F).setCreativeTab(DivineTabs.tabBlocks);
        dreamlampOn = new BlockDreamLamp(VetheaConfigHelper.dreamlampOnID, 30, Material.glass, true).func_111022_d("DreamLamp_On").setBlockUnbreakable().setUnlocalizedName("dreamlampOn").setHardness(1F).setResistance(1F);
        dreamlamp = new BlockDreamLamp(VetheaConfigHelper.dreamlampID, 31, Material.glass, false).func_111022_d("DreamLamp_Off").setBlockUnbreakable().setUnlocalizedName("dreamlamp").setHardness(1F).setStepSound(Block.soundGlassFootstep).setResistance(1F).setCreativeTab(DivineTabs.tabBlocks);
        weedwoodVine = new BlockWeedwoodVine(VetheaConfigHelper.weedwoodVineID, 41).func_111022_d("WeedWoodVine").setUnlocalizedName("weedwoodVine").setHardness(1F).setResistance(1F).setCreativeTab(DivineTabs.tabBlocks);
        blossomingWeedwoodVine = new BlockWeedwoodVine(VetheaConfigHelper.blossomingWeedwoodVineID, 42).func_111022_d("WeedWoodVineBlossomed").setUnlocalizedName("blossomingWeedwoodVine").setHardness(1F).setResistance(1F).setCreativeTab(DivineTabs.tabBlocks);
        
        cryptWall = new BlockVethea(VetheaConfigHelper.cryptWallID, 43, Material.rock).setBlockUnbreakable().setUnlocalizedName("cryptWall").setHardness(1F).setResistance(1F).setCreativeTab(DivineTabs.tabBlocks);//TODO add Texture (no texture
        smoothGlass = new BlockSmoothGlass(VetheaConfigHelper.smoothGlassID, 44, Material.glass).func_111022_d("SmoothGlass").setStepSound(Block.soundGlassFootstep).setUnlocalizedName("smoothGlass").setHardness(1F).setCreativeTab(DivineTabs.tabBlocks);
        villageLamp = new BlockVethea(VetheaConfigHelper.villageLampID, 45, Material.glass).func_111022_d("VillageLamp").setUnlocalizedName("villageLamp").setLightValue(1.0F).setStepSound(Block.soundGlassFootstep).setHardness(1F).setCreativeTab(DivineTabs.tabBlocks);
        cellLamp = new BlockVethea(VetheaConfigHelper.cellLampID, 57, Material.glass).func_111022_d("CellLamp").setUnlocalizedName("cellLamp").setLightValue(1.0F).setStepSound(Block.soundGlassFootstep).setHardness(1F).setCreativeTab(DivineTabs.tabBlocks);
        barredDoor = new BlockBarredDoor(VetheaConfigHelper.barredDoorID, Material.iron).func_111022_d("BarredDoor").setUnlocalizedName("barredDoor").setHardness(1F).setResistance(1F).setCreativeTab(DivineTabs.tabBlocks);
        firecrystal = new BlockVethea(VetheaConfigHelper.firecrystalID, 60, Material.glass).func_111022_d("FireCrystal").setLightValue(0.7F).setUnlocalizedName("firecrystal").setStepSound(Block.soundGlassFootstep).setHardness(1F).setCreativeTab(DivineTabs.tabBlocks);
        firelight = new BlockVethea(VetheaConfigHelper.firelightID, 60, Material.glass).func_111022_d("FireLight").setUnlocalizedName("firelight").setLightValue(1.0F).setStepSound(Block.soundGlassFootstep).setHardness(1F).setResistance(1.0F).setCreativeTab(DivineTabs.tabBlocks);
        firewood = new BlockDreamwood(VetheaConfigHelper.firewoodID).setUnlocalizedName("firewood").func_111022_d("FireWood").setHardness(1F).setResistance(1F).setCreativeTab(DivineTabs.tabBlocks);
        firewoodLeaves = new BlockDreamwoodLeaves(VetheaConfigHelper.firewoodLeavesID).func_111022_d("FireWoodLeaves").setUnlocalizedName("firewoodLeaves").setHardness(1F).setCreativeTab(DivineTabs.tabBlocks);
        firewall = new BlockVethea(VetheaConfigHelper.firewallID, 73, Material.rock).func_111022_d("FireWall").setUnlocalizedName("firewall").setHardness(1F).setResistance(1F).setCreativeTab(DivineTabs.tabBlocks);
        hyrewood = new BlockDreamwood(VetheaConfigHelper.hyrewoodID).func_111022_d("HyreWood").setUnlocalizedName("hyrewood").setHardness(1F).setResistance(1F).setCreativeTab(DivineTabs.tabBlocks);
        mintwoodLeaves = new BlockDreamwoodLeaves(VetheaConfigHelper.mintwoodLeavesID).func_111022_d("MintWoodLeaves").setUnlocalizedName("mintwoodLeaves").setHardness(1F).setCreativeTab(DivineTabs.tabBlocks);
        karosHeatTileGreen = new BlockKarosHeatTileGreen(VetheaConfigHelper.karosHeatTileGreenID, false).func_111022_d("KarosHeatTile1").setBlockUnbreakable().setUnlocalizedName("karosHeatTileGreen").setHardness(1F).setCreativeTab(DivineTabs.tabBlocks);
        karosHeatTileRed = new BlockKarosHeatTileRed(VetheaConfigHelper.karosHeatTileRedID, true).func_111022_d("KarosHeatTile2").setBlockUnbreakable().setUnlocalizedName("karosHeatTileRed").setHardness(1F).setCreativeTab(DivineTabs.tabBlocks);
        bacterialAcid = new BlockBacterialAcid(VetheaConfigHelper.bacterialAcidID).setUnlocalizedName("bacterialAcid").setHardness(1F).setResistance(1F).setCreativeTab(DivineTabs.tabBlocks);
        blockAcid = new BlockAcid(VetheaConfigHelper.blockAcidID).setUnlocalizedName("blockAcid").setHardness(1F).setResistance(1F).setCreativeTab(DivineTabs.tabBlocks);
        everstone = new BlockVethea(VetheaConfigHelper.everstoneID, 140, Material.rock).func_111022_d("EverStone").setBlockUnbreakable().setUnlocalizedName("everstone").setHardness(1F).setResistance(1F).setCreativeTab(DivineTabs.tabBlocks);
        lunicAcid = new BlockLunicAcid(VetheaConfigHelper.lunicAcidID, 141).setUnlocalizedName("lunicAcid").setHardness(1F).setResistance(1F).setCreativeTab(DivineTabs.tabBlocks);
        hyrewoodLeaves = new BlockDreamwoodLeaves(VetheaConfigHelper.hyrewoodLeavesID).func_111022_d("HyreWoodLeaves").setUnlocalizedName("hyrewoodLeaves").setHardness(1F).setCreativeTab(DivineTabs.tabBlocks);
        gemtopGreen = new BlockVetheaPlant(VetheaConfigHelper.gemtopGreenID).setUnlocalizedName("gemtopGreen").setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(DivineTabs.tabHerb);
        gemtopPurple = new BlockVetheaPlant(VetheaConfigHelper.gemtopPurpleID).setUnlocalizedName("gemtopPurple").setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(DivineTabs.tabHerb);
        yellowDulah = new BlockVetheaPlant(VetheaConfigHelper.yellowDulahID).setUnlocalizedName("yellowDulah").setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(DivineTabs.tabHerb);
        greenDulah = new BlockVetheaPlant(VetheaConfigHelper.greenDulahID).setUnlocalizedName("greenDulah").setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(DivineTabs.tabHerb);
        mintwood = new BlockDreamwood(VetheaConfigHelper.mintwoodID).setUnlocalizedName("mint").func_111022_d("MintWood").setHardness(1F).setResistance(1F).setCreativeTab(DivineTabs.tabBlocks);
        lightFirewoodLeaves = new BlockDreamwoodLeaves(VetheaConfigHelper.lightFirewoodLeavesID).setUnlocalizedName("lightFirewoodLeaves").setHardness(1F).setCreativeTab(DivineTabs.tabBlocks);
        cracklespike = new BlockVetheaPlant(VetheaConfigHelper.cracklespikeID).func_111022_d("CrackleSpike").setUnlocalizedName("cracklespike").setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(DivineTabs.tabHerb);
        fernite = new BlockVetheaPlant(VetheaConfigHelper.ferniteID).setUnlocalizedName("fernite").setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(DivineTabs.tabHerb);
        bulatobe = new BlockVetheaPlant(VetheaConfigHelper.bulatobeID).setUnlocalizedName("bulatobe").setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(DivineTabs.tabHerb);
        shineGrass = new BlockVetheaPlant(VetheaConfigHelper.shineGrassID).setUnlocalizedName("shineGrass").setLightValue(0.4F).setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(DivineTabs.tabHerb);
        shimmer = new BlockShimmer(VetheaConfigHelper.shimmerID).setLightValue(0.4F).func_111022_d("Shimmer").setUnlocalizedName("shimmer").setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(DivineTabs.tabHerb);
        hiveWall = new BlockVethea(VetheaConfigHelper.hiveWallID, 127, Material.glass).setLightValue(0.533F).func_111022_d("HiveWalls").setUnlocalizedName("hiveWall").setHardness(1F).setResistance(1F).setCreativeTab(DivineTabs.tabBlocks);
        dreamglow = new BlockShimmer(VetheaConfigHelper.dreamglowID).setLightValue(0.4F).setUnlocalizedName("dreamglow").setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(DivineTabs.tabHerb);
        hyrewoodVine = new BlockWeedwoodVine(VetheaConfigHelper.hyrewoodVineID, 175).setUnlocalizedName("hyrewoodVine").setHardness(1F).setResistance(1F).setCreativeTab(DivineTabs.tabBlocks);
        
        chamberWall1 = new BlockVethea(VetheaConfigHelper.chamberWallID, 91, Material.rock).func_111022_d("ChamberWall1").setBlockUnbreakable().setUnlocalizedName("chamberWall").setHardness(1F).setResistance(1F).setCreativeTab(DivineTabs.tabBlocks);
        chamberWall2 = new BlockVethea(VetheaConfigHelper.chamberWall1ID, 92, Material.rock).func_111022_d("ChamberWall2").setBlockUnbreakable().setUnlocalizedName("chamberWall1").setHardness(1F).setResistance(1F).setCreativeTab(DivineTabs.tabBlocks);
        chamberWall3 = new BlockVethea(VetheaConfigHelper.chamberWall2ID, 93, Material.rock).func_111022_d("ChamberWall3").setBlockUnbreakable().setUnlocalizedName("chamberWall2").setHardness(1F).setResistance(1F).setCreativeTab(DivineTabs.tabBlocks);
        whiteEverstone = new BlockVethea(VetheaConfigHelper.whiteEverstoneID, 139, Material.rock).func_111022_d("WhiteEverstone").setBlockUnbreakable().setUnlocalizedName("whiteEverstone").setHardness(1F).setResistance(1F).setCreativeTab(DivineTabs.tabBlocks);
        darkEverstone = new BlockVethea(VetheaConfigHelper.darkEverstoneID, 138, Material.rock).func_111022_d("DarkEverstone").setBlockUnbreakable().setUnlocalizedName("darkEverstone").setHardness(1F).setResistance(1F).setCreativeTab(DivineTabs.tabBlocks);
        
        wreckAltar = new BlockWreckAltar(VetheaConfigHelper.wreckAltarID).func_111022_d("WreckAltar").setUnlocalizedName("wreckAltar").setBlockUnbreakable().setResistance(999F).setCreativeTab(DivineTabs.tabBlocks);
        raglokAltar = new BlockRaglokAltar(VetheaConfigHelper.raglokAltarID).func_111022_d("RaglokAltar").setUnlocalizedName("raglokAltar").setBlockUnbreakable().setResistance(999F).setCreativeTab(DivineTabs.tabBlocks);
        karosAltar = new BlockKarosAltar(VetheaConfigHelper.karosAltarID).func_111022_d("KarosAltar").setUnlocalizedName("karosAltar").setBlockUnbreakable().setResistance(999F).setCreativeTab(DivineTabs.tabBlocks);
        lunicAltar = new BlockLunicAltar(VetheaConfigHelper.lunicAltarID).func_111022_d("LunicAltar").setUnlocalizedName("lunicAltar").setBlockUnbreakable().setResistance(999F).setCreativeTab(DivineTabs.tabBlocks);
        quadroticAltar = new BlockVethea(VetheaConfigHelper.quadroticAltarID, 137, Material.rock).func_111022_d("QuadroticAltar").setUnlocalizedName("quadroticAltar").setBlockUnbreakable().setResistance(999F).setCreativeTab(DivineTabs.tabBlocks);
        
        infusionTable = new BlockInfusionTable(VetheaConfigHelper.infusionTableID).func_111022_d("InfusionTable").setBlockUnbreakable().setUnlocalizedName("infusionTable").setBlockUnbreakable().setResistance(999F).setCreativeTab(DivineTabs.tabBlocks);
        hungerstone1 = new BlockVethea(VetheaConfigHelper.hungerstone1ID, 106, Material.rock).func_111022_d("HungerStone1").setUnlocalizedName("hungerstone1").setHardness(1F).setResistance(1F).setCreativeTab(DivineTabs.tabBlocks);
        hungerstone2 = new BlockVethea(VetheaConfigHelper.hungerstone2ID, 107, Material.rock).func_111022_d("HungerStone2").setUnlocalizedName("hungerstone2").setHardness(1F).setResistance(1F).setCreativeTab(DivineTabs.tabBlocks);
        cryptFloor = new BlockVethea(VetheaConfigHelper.cryptFloorID, 79, Material.rock).func_111022_d("CryptFloor").setBlockUnbreakable().setUnlocalizedName("cryptFloor").setHardness(1F).setResistance(1F).setCreativeTab(DivineTabs.tabBlocks);
        hallWall = new BlockVethea(VetheaConfigHelper.hallWallID, 109, Material.rock).setBlockUnbreakable().setUnlocalizedName("hallWall").setHardness(1F).setResistance(1F).setCreativeTab(DivineTabs.tabBlocks);
        karosBricks = new BlockVethea(VetheaConfigHelper.karosBricksID, 94, Material.rock).func_111022_d("KarosBrick").setBlockUnbreakable().setUnlocalizedName("karosBricks").setHardness(1F).setResistance(1F).setCreativeTab(DivineTabs.tabBlocks);
        karosBricks2 = new BlockVethea(VetheaConfigHelper.karosBricks2ID, 95, Material.rock).setBlockUnbreakable().setUnlocalizedName("karosBricks2").setHardness(1F).setResistance(1F).setCreativeTab(DivineTabs.tabBlocks);
        helioticBeam = (BlockHelioticBeam) new BlockHelioticBeam(VetheaConfigHelper.helioticBeamID).func_111022_d("HeloticBeam").setUnlocalizedName("helioticBeam").setHardness(1F).setResistance(1F).setCreativeTab(DivineTabs.tabBlocks);
        karosCannon = (BlockKarosCannon) new BlockKarosCannon(VetheaConfigHelper.karosCannonID, Material.rock).setBlockUnbreakable().setUnlocalizedName("karosCannon").setHardness(1F).setResistance(1F).setCreativeTab(DivineTabs.tabUtility);
        purpleFire = new BlockPurpleFire(VetheaConfigHelper.purpleFireID).setUnlocalizedName("purpleFire").setCreativeTab(DivineTabs.tabBlocks);
	
        initGameRegistryBlocks();
        addNames();
	}
    
    public static void initGameRegistryBlocks()
	{
    	GameRegistry.registerBlock((Block)vetheaPortal, "vetheaPortal");
        GameRegistry.registerBlock(everstone, "everstone");
        GameRegistry.registerBlock(whiteEverstone, "whiteEverstone");
        GameRegistry.registerBlock(darkEverstone, "darkEverstone");
        GameRegistry.registerBlock(dreamgrass, "dreamgrass");
        GameRegistry.registerBlock(dreamdirt, "dreamdirt");
        GameRegistry.registerBlock(dreamlampOn, "dreamlampOn");
        GameRegistry.registerBlock(dreamlamp, "dreamlamp");
        GameRegistry.registerBlock(firecrystal, "firecrystal");
        GameRegistry.registerBlock(hiveWall, "hiveWall");
        GameRegistry.registerBlock(hyrewood, "hyrewood");
        GameRegistry.registerBlock(firewood, "firewood");
        GameRegistry.registerBlock(mintwood, "mintwood");
        GameRegistry.registerBlock(dreamwood, "dreamwood");
        GameRegistry.registerBlock(hyrewoodLeaves, "hyrewoodLeaves");
        GameRegistry.registerBlock(firewoodLeaves, "firewoodLeaves");
        GameRegistry.registerBlock(mintwoodLeaves, "mintwoodLeaves");
        GameRegistry.registerBlock(dreamwoodLeaves, "dreamwoodLeaves");
        GameRegistry.registerBlock(infusionTable, "infusionTable");
        GameRegistry.registerTileEntity(TileEntityInfusionTable.class, "TeInfusionTable");
        GameRegistry.registerTileEntity(TileEntityDreamLamp.class, "TeDreamLamp");
        GameRegistry.registerBlock(purpleFire, "PurpleFire");
        GameRegistry.registerBlock(karosCannon, "karosCannon");
        GameRegistry.registerBlock(dreambricks, "dreambricks");
        GameRegistry.registerBlock(dreambricks2, "dreambricks2");
        GameRegistry.registerBlock(lunastone, "lunastone");
        GameRegistry.registerBlock(lunabricks, "lunabricks");
        GameRegistry.registerBlock(metalCaging, "metalCaging");
        GameRegistry.registerBlock(cryptWall, "cryptWall");
        GameRegistry.registerBlock(smoothGlass, "smoothGlass");
        GameRegistry.registerBlock(villageLamp, "villageLamp");
        GameRegistry.registerBlock(cellLamp, "cellLamp");
        GameRegistry.registerBlock(barredDoor, "barredDoor");
        GameRegistry.registerBlock(firelight, "firelight");
        GameRegistry.registerBlock(firewall, "firewall");
        GameRegistry.registerBlock(karosHeatTileRed, "karosHeatTileRed");
        GameRegistry.registerBlock(karosHeatTileGreen, "karosHeatTileGreen");
        GameRegistry.registerBlock(helioticBeam, "helioticBeam");
        GameRegistry.registerBlock(cryptFloor, "cryptFloor");
        GameRegistry.registerBlock(chamberWall1, "chamberWall");
        GameRegistry.registerBlock(chamberWall2, "chamberWall1");
        GameRegistry.registerBlock(chamberWall3, "chamberWall2");
        
        GameRegistry.registerBlock(wreckAltar, "wreckAltar");
        GameRegistry.registerBlock(raglokAltar, "raglokAltar");
        GameRegistry.registerBlock(karosAltar, "karosAltar");
        GameRegistry.registerBlock(lunicAltar, "lunicAltar");
        GameRegistry.registerBlock(quadroticAltar, "quadroticAltar"); 
	}
    
    public static void addNames()
	{
    	LanguageRegistry.addName(dreamstone, "Dreamstone");
		LanguageRegistry.addName(dreamgrass, "Dream Grass");
		LanguageRegistry.addName(dreamdirt, "Dream Dirt");
		LanguageRegistry.addName(dreamwood, "Dreamwod");
		LanguageRegistry.addName(dreamwoodLeaves, "Dreamwood Leaves");
		LanguageRegistry.addName(dreambricks, "Dreambricks");
		LanguageRegistry.addName(dreambricks2, "Dreambricks");
		LanguageRegistry.addName(lunastone, "Lunastone");
		LanguageRegistry.addName(metalCaging, "Metal Caging");
		LanguageRegistry.addName(weedwoodVine, "Weedwood Vines");
		LanguageRegistry.addName(blossomingWeedwoodVine, "Blossoming Weedwood Vines");
		LanguageRegistry.addName(cryptWall, "Crypt Wall");
		LanguageRegistry.addName(smoothGlass, "Smooth Glass");
		LanguageRegistry.addName(villageLamp, "Altar Lamps");
		LanguageRegistry.addName(infusionTable, "Infusion Table");
		LanguageRegistry.addName(cellLamp, "Cell Lamp");
		LanguageRegistry.addName(barredDoor, "Barred Door");
		LanguageRegistry.addName(firecrystal, "Firecrystal");
		LanguageRegistry.addName(firelight, "Firelight");
		LanguageRegistry.addName(hyrewood, "Hyrewood");
		LanguageRegistry.addName(mintwoodLeaves, "Mintwood Leaves");
		LanguageRegistry.addName(firewall, "Firewall");
		LanguageRegistry.addName(karosHeatTileGreen, "Karos Heat Tile");
		LanguageRegistry.addName(karosHeatTileRed, "Karos Heat Tile");
		LanguageRegistry.addName(karosCannon, "Karos Cannon");
		LanguageRegistry.addName(helioticBeam, "Heliotic Beam");
		LanguageRegistry.addName(cryptFloor, "Crypt Floor");
		LanguageRegistry.addName(firewood, "Firewood");
		LanguageRegistry.addName(chamberWall1, "Chamber Wall");
		LanguageRegistry.addName(chamberWall2, "Chamber Wall");
		LanguageRegistry.addName(chamberWall3, "Chamber Wall");
		LanguageRegistry.addName(karosBricks, "Karos Bricks");
		LanguageRegistry.addName(karosBricks2, "Karos Bricks");
		LanguageRegistry.addName(bacterialAcid, "Bacterial Acid");
		LanguageRegistry.addName(hungerstone1, "Hungerstone");
		LanguageRegistry.addName(hungerstone2, "Hungerstone");
		LanguageRegistry.addName(blockAcid, "Acid");
		LanguageRegistry.addName(hallWall, "Hall Wall");
		LanguageRegistry.addName(wreckAltar, "Wreck Altar");
		LanguageRegistry.addName(raglokAltar, "Raglok Altar");
		LanguageRegistry.addName(karosAltar, "Karos Altar");
		LanguageRegistry.addName(lunicAltar, "Lunic Altar");
		LanguageRegistry.addName(quadroticAltar, "Quadrotic Altar");
		LanguageRegistry.addName(hiveWall, "Hive Walls");
		LanguageRegistry.addName(darkEverstone, "Dark Everstone");
		LanguageRegistry.addName(whiteEverstone, "White Everstone");
		LanguageRegistry.addName(everstone, "Everstone");
		LanguageRegistry.addName(lunicAcid, "Lunic Acid");
		LanguageRegistry.addName(firewoodLeaves, "Firewood Leaves");
		LanguageRegistry.addName(hyrewoodLeaves, "Hyrewood Leaves");
		LanguageRegistry.addName(gemtopGreen, "Green Gemtops");
		LanguageRegistry.addName(gemtopPurple, "Purple Gemtops");
		LanguageRegistry.addName(yellowDulah, "Yellow Dulahs");
		LanguageRegistry.addName(greenDulah, "Green Dulahs");
		LanguageRegistry.addName(mintwood, "Mintwood");
		LanguageRegistry.addName(lightFirewoodLeaves, "Light Firewood Leaves");
		LanguageRegistry.addName(cracklespike, "Crackle Spikes");
		LanguageRegistry.addName(fernite, "Fernites");
		LanguageRegistry.addName(bulatobe, "Bulbatobes");
		LanguageRegistry.addName(shineGrass, "Shine Grass");
		LanguageRegistry.addName(shimmer, "Shimmers");
		LanguageRegistry.addName(dreamglow, "Dream Glows");
		LanguageRegistry.addName(hyrewoodVine, "Hyrewood Vines");
	}
}
