package xolova.divinerpg.utils.helpers.recipe;

import net.minecraft.block.Block;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import xolova.divinerpg.DivineRPG;
import xolova.divinerpg.utils.helpers.block.ArcanaBlockHelper;
import xolova.divinerpg.utils.helpers.block.OverworldBlockHelper;
import xolova.divinerpg.utils.helpers.block.TwilightBlockHelper;
import xolova.divinerpg.utils.helpers.item.ArcanaItemHelper;
import xolova.divinerpg.utils.helpers.item.OverworldItemHelper;
import xolova.divinerpg.utils.helpers.item.TwilightItemHelper;
import xolova.divinerpg.utils.helpers.item.VetheaItemHelper;
import cpw.mods.fml.common.registry.GameRegistry;

public class ModRecipes {
	
	public static void init()
	{
		GameRegistry.addRecipe(new ItemStack(VetheaItemHelper.dreamPowder, 1), new Object[]{"xxx", "xyx", "xxx", 'x', TwilightItemHelper.AugiteFragments , 'y', Item.lightStoneDust});
		GameRegistry.addRecipe(new ItemStack(TwilightBlockHelper.DraviteLamp, 1), new Object[] { "xxx", "xyx", "xxx", 'y', TwilightItemHelper.DraviteFragments, 'x', Item.ingotIron });
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.aquaticTrident, 1), new Object[] {" y ", "yyy", " x ", 'y', OverworldItemHelper.aquaticStones , 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.aquaton, 1), new Object[] {"yyy", "yyy", " x ", 'y', OverworldItemHelper.aquaticStones , 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.hamreicher, 1), new Object[] {"yyy", "yyy", "yxy", 'y', OverworldItemHelper.aquaticStones , 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.crabClawCannon, 1), new Object[] {" y ", " y ", " x ", 'y', OverworldItemHelper.crabClaw , 'x', OverworldItemHelper.aquaticStones});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.sharkSword, 1), new Object[] {" y ", " y ", " x ", 'y', OverworldItemHelper.sharkFin , 'x', OverworldItemHelper.aquaticStones});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.bowheadCannon, 1), new Object[] {" y ", " y ", " x ", 'y', OverworldItemHelper.whaleFin , 'x', OverworldItemHelper.aquaticStones});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.oceanKnife, 1), new Object[] {" y ", " y ", " x ", 'y', OverworldItemHelper.aquaticStones , 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.dualClaw, 1), new Object[] {" y ", "xxx", " y ", 'y', OverworldItemHelper.crabClaw , 'x', OverworldItemHelper.aquaticStones});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.daggerOfBlood, 1), new Object[] {" y ", " x ", 'y', OverworldItemHelper.aquaticStones , 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.clawAnchor, 1), new Object[] {"yyy", "yxy", " x ", 'y', OverworldItemHelper.crabClaw , 'x', OverworldItemHelper.aquaticStones});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.bowheadAnchor, 1), new Object[] {"yyy", "yxy", " x ", 'y', OverworldItemHelper.whaleFin , 'x', OverworldItemHelper.aquaticStones});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.sharkAnchor, 1), new Object[] {"yyy", "yxy", " x ", 'y', OverworldItemHelper.sharkFin , 'x', OverworldItemHelper.aquaticStones});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.aquaticStones, 1), new Object[] {"xxx", "xxx", "xxx", 'x', OverworldItemHelper.aquaticShards});
        //Recipes
        //Armor
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.netheriteHelmet, 1), new Object[] {"xxx", "s s", "x x", 'x', OverworldItemHelper.netheriteChunk, 's', OverworldItemHelper.shadowBar});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.netheriteBody, 1), new Object[] {"xsx", "xsx", " x ", 'x', OverworldItemHelper.netheriteChunk, 's', OverworldItemHelper.shadowBar});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.netheriteLegs, 1), new Object[] {"sss", "x x", "s s", 'x', OverworldItemHelper.netheriteChunk, 's', OverworldItemHelper.shadowBar});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.netheriteBoots, 1), new Object[] {"s s", "x x", 'x', OverworldItemHelper.netheriteChunk, 's', OverworldItemHelper.shadowBar});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.crystonalHelmet, 1), new Object[] {"xxx", "sss", "s s", 'x', OverworldItemHelper.arlemite, 's', Item.ingotIron});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.crystonalBody, 1), new Object[] {"xsx", "sxs", " s ", 'x', OverworldItemHelper.arlemite, 's', Item.ingotIron});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.crystonalLegs, 1), new Object[] {"sss", "x x", "y y", 'x', OverworldItemHelper.arlemite, 's', Item.ingotIron, 'y', OverworldItemHelper.shadowBar});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.crystonalBoots, 1), new Object[] {"s s", "x x", 'x', OverworldItemHelper.arlemite, 's', Item.ingotIron});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.krakenHelmet, 1), new Object[] {"xxx", "x x", 'x', OverworldItemHelper.krakenSkin});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.krakenBody, 1), new Object[] {"x x", "xxx", "xxx", 'x', OverworldItemHelper.krakenSkin});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.krakenLegs, 1), new Object[] {"xxx", "x x", "x x", 'x', OverworldItemHelper.krakenSkin});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.krakenBoots, 1), new Object[] {"x x", "x x", 'x', OverworldItemHelper.krakenSkin});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.infernoHelmet, 1), new Object[] {"xxx", "x x", 'x', OverworldItemHelper.moltenStone});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.infernoBody, 1), new Object[] {"x x", "xxx", "xxx", 'x', OverworldItemHelper.moltenStone});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.infernoLegs, 1), new Object[] {"xxx", "x x", "x x", 'x', OverworldItemHelper.moltenStone});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.infernoBoots, 1), new Object[] {"x x", "x x", 'x', OverworldItemHelper.moltenStone});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.bedrockHelmet, 1), new Object[] {"xxx", "x x", 'x', Block.bedrock});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.bedrockBody, 1), new Object[] {"x x", "xxx", "xxx", 'x', Block.bedrock});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.bedrockLegs, 1), new Object[] {"xxx", "x x", "x x", 'x', Block.bedrock});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.bedrockBoots, 1), new Object[] {"x x", "x x", 'x', Block.bedrock});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.plasmaHelmet, 1), new Object[] {"xxx", "x x", 'x', OverworldItemHelper.rupee});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.plasmaBody, 1), new Object[] {"x x", "xxx", "xxx", 'x', OverworldItemHelper.rupee});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.plasmaLegs, 1), new Object[] {"xxx", "x x", "x x", 'x', OverworldItemHelper.rupee});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.plasmaBoots, 1), new Object[] {"x x", "x x", 'x', OverworldItemHelper.rupee});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.realmiteHelmet, 1), new Object[] {"xxx", "x x", 'x', OverworldItemHelper.realmiteIngot});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.realmiteBody, 1), new Object[] {"x x", "xxx", "xxx", 'x', OverworldItemHelper.realmiteIngot});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.realmiteLegs, 1), new Object[] {"xxx", "x x", "x x", 'x', OverworldItemHelper.realmiteIngot});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.realmiteBoots, 1), new Object[] {"x x", "x x", 'x', OverworldItemHelper.realmiteIngot});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.eliteRealmiteHelmet, 1), new Object[] {"xxx", "x x", "  ", 'x', OverworldBlockHelper.realmiteBlock});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.eliteRealmiteBody, 1), new Object[] {"x x", "xxx", "xxx", 'x', OverworldBlockHelper.realmiteBlock});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.eliteRealmiteLegs, 1), new Object[] {"xxx", "x x", "x x", 'x', OverworldBlockHelper.realmiteBlock});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.eliteRealmiteBoots, 1), new Object[] {"x x", "x x", 'x', OverworldBlockHelper.realmiteBlock});
        //Tools
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.enderSword, 1), new Object[] {" x ", " x ", " y ", 'x', OverworldItemHelper.legendaryEnderEye, 'y', OverworldItemHelper.shadowBar});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.Pavalence, 1), new Object[] {"x x", "xxx", " x ", 'x', OverworldItemHelper.realmiteIngot});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.namkormira, 1), new Object[] {"x x", "yyy", " y ", 'x', OverworldItemHelper.glowingGem, 'y', OverworldItemHelper.netheriteBar});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.infernoSword, 1), new Object[] {"xyx", "xyx", "xzx", 'x', Item.blazePowder, 'y', Block.oreRedstone, 'z', Item.stick});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.bedrockSword, 1), new Object[] {" y ", " y ", " x ", 'x', Item.stick, 'y', Block.bedrock});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.realmiteSword, 1), new Object[] {" y ", " y ", " x ", 'x', Item.stick, 'y', OverworldItemHelper.realmiteIngot});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.arlemiteStabber, 1), new Object[] {" y ", " y ", " x ", 'x', Item.stick, 'y', OverworldItemHelper.arlemite});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.rupeeSword, 1), new Object[] {" y ", " y ", " x ", 'x', Item.stick, 'y', OverworldItemHelper.rupee});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.slimeSword, 1), new Object[] {"yxy", "yxy", "yxy", 'y', Item.slimeBall, 'x', Item.swordDiamond});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.furyMaul, 1), new Object[] {"yxy", "xxx", "yxy", 'x', Block.bedrock, 'y', Block.oreDiamond});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.bedrockMaul, 1), new Object[] {" x ", "xyx", " x ", 'y', Block.bedrock, 'x', Block.bedrock});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.blazingCrystalleSword, 1), new Object[] {" x ", " z ", " y ", 'x', OverworldItemHelper.glowingGem, 'y', Item.stick, 'z', OverworldItemHelper.glowingGem});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.realmitePickaxe, 1), new Object[] {"xxx", " y ", " y ", 'x', OverworldItemHelper.realmiteIngot, 'y', Item.stick});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.realmiteAxe, 1), new Object[] {"xx ", "xy ", " y ", 'x', OverworldItemHelper.realmiteIngot, 'y', Item.stick});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.realmiteShovel, 1), new Object[] {" x ", " y ", " y ", 'x', OverworldItemHelper.realmiteIngot, 'y', Item.stick});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.bedrockPickaxe, 1), new Object[] {"xxx", " y ", " y ", 'x', Block.bedrock, 'y', Item.stick});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.bedrockAxe, 1), new Object[] {"xx ", "xy ", " y ", 'x', Block.bedrock, 'y', Item.stick});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.bedrockShovel, 1), new Object[] {" x ", " y ", " y ", 'x', Block.bedrock, 'y', Item.stick});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.crystalPickaxe, 1), new Object[] {"xxx", " y ", " y ", 'x', OverworldItemHelper.arlemite, 'y', Item.stick});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.crystalAxe, 1), new Object[] {"xx ", "xy ", " y ", 'x', OverworldItemHelper.arlemite, 'y', Item.stick});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.crystalShovel, 1), new Object[] {" x ", " y ", " y ", 'x', OverworldItemHelper.arlemite, 'y', Item.stick});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.crystalHoe, 1), new Object[] {"xx ", " y ", " y ", 'x', OverworldItemHelper.arlemite, 'y', Item.stick});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.plasmaPickaxe, 1), new Object[] {"xxx", " y ", " y ", 'x', OverworldItemHelper.rupee, 'y', Item.stick});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.plasmaAxe, 1), new Object[] {"xx ", "xy ", " y ", 'x', OverworldItemHelper.rupee, 'y', Item.stick});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.plasmaShovel, 1), new Object[] {" x ", " y ", " y ", 'x', OverworldItemHelper.rupee, 'y', Item.stick});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.plasmaHoe, 1), new Object[] {"xx ", " y ", " y ", 'x', OverworldItemHelper.rupee, 'y', Item.stick});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldItemHelper.plasmaShicaxe, 1), new Object[] {OverworldItemHelper.plasmaHoe, OverworldItemHelper.plasmaShovel, OverworldItemHelper.plasmaPickaxe, OverworldItemHelper.plasmaAxe});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldItemHelper.crystalShicaxe, 1), new Object[] {OverworldItemHelper.crystalHoe, OverworldItemHelper.crystalShovel, OverworldItemHelper.crystalPickaxe, OverworldItemHelper.crystalAxe});
        //Foods
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.donut, 1), new Object[] {"xxx", "x x", "xxx", 'x', Item.wheat});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.pizzaDough, 1), new Object[] {"x x", "xxx", 'x', Item.wheat});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldItemHelper.bacon, 6), new Object[] {Item.porkRaw});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.waterMelon, 1), new Object[] {"xxx", "xxx", 'x', Item.melon});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.cheese, 1), new Object[] {"xxx", "xxx", "xxx", 'x', Item.bucketMilk});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldItemHelper.minipizza, 4), new Object[] {OverworldItemHelper.whiteMushroom, OverworldItemHelper.tomato, OverworldItemHelper.pizzaDough, OverworldItemHelper.cheese});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldItemHelper.dinner, 4), new Object[] {Item.bread, Item.chickenRaw, Item.bowlSoup, OverworldItemHelper.whiteMushroom, OverworldItemHelper.whiteMushroom});
        GameRegistry.addSmelting(Item.egg.itemID, new ItemStack(OverworldItemHelper.boiledegg, 1), 0);
        //Blocks
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.obsidianBlock, 1), new Object[] {"xxx", "xxx", "xxx", 'x', Block.obsidian});
        //GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.iceblock, 1, 0), new Object[] {"xxx", "xxx", "xxx", 'x', Block.ice});
        //GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.iceblock, 1, 1), new Object[] {"xxx", "xxx", "xxx", 'x', Item.flint});
        //GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.iceblock, 1, 2), new Object[] {"xxx", "xxx", "xxx", 'x', Block.gravel});
        //GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.iceblock, 1, 3), new Object[] {"xxx", "xxx", "xxx", 'x', Item.coal});
        //GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.iceblock, 1, 4), new Object[] {"xxx", "xxx", "xxx", 'x', Block.stone});
        //GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.iceblock, 1, 5), new Object[] {"xxx", "xxx", "xxx", 'x', Block.sand});
        //GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.iceblock, 1, 6), new Object[] {"xxx", "xxx", "xxx", 'x', Block.slowSand});
        //GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.iceblock, 1, 7), new Object[] {"xxx", "xxx", "xxx", 'x', Block.dirt});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.realmiteBlock, 1), new Object[] {"xxx", "xxx", "xxx", 'x', OverworldItemHelper.realmiteIngot});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.bedrock, 1), new Object[] {"xxx", "xxx", "xxx", 'x', Block.bedrock});
        GameRegistry.addShapelessRecipe(new ItemStack(Block.obsidian, 9), new Object[] {OverworldBlockHelper.obsidianBlock});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.steel, 1, 0), new Object[] {"xxx", "xyx", "xxx", 'x', Item.ingotIron, 'y', new ItemStack(Item.dyePowder, 1, 6)});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.steel, 1, 1), new Object[] {"xxx", "xyx", "xxx", 'x', Item.ingotIron, 'y', new ItemStack(Item.dyePowder, 1, 1)});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.steel, 1, 2), new Object[] {"xxx", "xyx", "xxx", 'x', Item.ingotIron, 'y', new ItemStack(Item.dyePowder, 1, 5)});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.steel, 1, 3), new Object[] {"xxx", "xyx", "xxx", 'x', Item.ingotIron, 'y', new ItemStack(Item.dyePowder, 1, 2)});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.steel, 1, 4), new Object[] {"xxx", "xyx", "xxx", 'x', Item.ingotIron, 'y', new ItemStack(Item.dyePowder, 1, 11)});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.steel, 1, 5), new Object[] {"xxx", "xyx", "xxx", 'x', Item.ingotIron, 'y', new ItemStack(Item.dyePowder, 1, 4)});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.steel, 1, 6), new Object[] {"xxx", "xyx", "xxx", 'x', Item.ingotIron, 'y', new ItemStack(Item.dyePowder, 1, 15)});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.steel, 1, 7), new Object[] {"xxx", "xyx", "xxx", 'x', Item.ingotIron, 'y', new ItemStack(Item.dyePowder, 1, 0)});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.steel, 1, 8), new Object[] {"xxx", "xyx", "xxx", 'x', Item.ingotIron, 'y', new ItemStack(Item.dyePowder, 1, 14)});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.steel, 1, 9), new Object[] {"xxx", "xyx", "xxx", 'x', Item.ingotIron, 'y', new ItemStack(Item.dyePowder, 1, 13)});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.steel, 1, 11), new Object[] {"xxx", "y y", "xxx", 'x', Block.planks, 'y', Block.wood});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.steel, 1, 12), new Object[] {"xyx", "yxy", "xyx", 'x', new ItemStack(Block.planks, 1, 0), 'y', new ItemStack(Block.planks, 1, 1)});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.milkStone, 4), new Object[] {Block.stone, Block.stone, Block.stone, Item.bucketMilk});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.darkStone, 10), new Object[] {Block.obsidian, Block.glowStone});
        //GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.netherrack, 1), new Object[] {"xxx", "xxx", "xxx", 'x', Block.netherrack});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.redstonebricks, 4), new Object[] {Block.stoneBrick, Block.stoneBrick, Block.stoneBrick, Item.redstone});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.lapisbricks, 4), new Object[] {Block.stoneBrick, Block.stoneBrick, Block.stoneBrick, new ItemStack(Item.dyePowder, 1, 4)});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.netheritebricks, 4), new Object[] {OverworldItemHelper.netheriteBar});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.realmitebricks, 4), new Object[] {OverworldItemHelper.realmiteIngot, OverworldItemHelper.realmiteIngot, OverworldItemHelper.realmiteIngot, OverworldItemHelper.realmiteIngot, OverworldItemHelper.realmiteIngot});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.goldbricks, 4), new Object[] {Block.stoneBrick, Block.stoneBrick, Block.stoneBrick, Item.ingotGold});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.ironbricks, 4), new Object[] {Block.stoneBrick, Block.stoneBrick, Block.stoneBrick, Item.ingotIron});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.darkbricks, 4), new Object[] {Block.stoneBrick, Block.stoneBrick, Block.stoneBrick, new ItemStack(Item.dyePowder, 1, 0)});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.milkstonebricks, 4), new Object[] {OverworldBlockHelper.milkStone, OverworldBlockHelper.milkStone, OverworldBlockHelper.milkStone});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.checker, 3, 0), new Object[] {"xyx", "yxy", "xyx", 'x', new ItemStack(Block.cloth, 1, 0), 'y', new ItemStack(Block.cloth, 1, 15)});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.eucalyptusPlanks, 4), new Object[] {OverworldBlockHelper.eucalyptus});
        //GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.stoneFence, 4), new Object[] {"xxx", "xxx", 'x', Block.cobblestone});
        //GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.woodFence, 4), new Object[] {"xxx", "xxx", 'x', Block.planks});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.lightFenceBlue, 4), new Object[] {"yyy", "yyy", 'y', new ItemStack(Item.dyePowder, 1, 4)});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.lightFenceRed, 4), new Object[] {"yyy", "yyy", 'y', Item.redstone});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.dyeBlocks, 1, 0), new Object[] {"xxx", "xxx", "xxx", 'x', new ItemStack(Item.dyePowder, 1, 15)});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.dyeBlocks, 1, 1), new Object[] {"xxx", "xxx", "xxx", 'x', new ItemStack(Item.dyePowder, 1, 14)});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.dyeBlocks, 1, 2), new Object[] {"xxx", "xxx", "xxx", 'x', new ItemStack(Item.dyePowder, 1, 13)});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.dyeBlocks, 1, 3), new Object[] {"xxx", "xxx", "xxx", 'x', new ItemStack(Item.dyePowder, 1, 12)});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.dyeBlocks, 1, 4), new Object[] {"xxx", "xxx", "xxx", 'x', new ItemStack(Item.dyePowder, 1, 11)});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.dyeBlocks, 1, 5), new Object[] {"xxx", "xxx", "xxx", 'x', new ItemStack(Item.dyePowder, 1, 10)});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.dyeBlocks, 1, 6), new Object[] {"xxx", "xxx", "xxx", 'x', new ItemStack(Item.dyePowder, 1, 9)});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.dyeBlocks, 1, 7), new Object[] {"xxx", "xxx", "xxx", 'x', new ItemStack(Item.dyePowder, 1, 8)});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.dyeBlocks, 1, 8), new Object[] {"xxx", "xxx", "xxx", 'x', new ItemStack(Item.dyePowder, 1, 7)});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.dyeBlocks, 1, 9), new Object[] {"xxx", "xxx", "xxx", 'x', new ItemStack(Item.dyePowder, 1, 6)});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.dyeBlocks, 1, 10), new Object[] {"xxx", "xxx", "xxx", 'x', new ItemStack(Item.dyePowder, 1, 5)});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.dyeBlocks, 1, 11), new Object[] {"xxx", "xxx", "xxx", 'x', new ItemStack(Item.dyePowder, 1, 3)});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.dyeBlocks, 1, 12), new Object[] {"xxx", "xxx", "xxx", 'x', new ItemStack(Item.dyePowder, 1, 2)});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.dyeBlocks, 1, 13), new Object[] {"xxx", "xxx", "xxx", 'x', new ItemStack(Item.dyePowder, 1, 1)});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.dyeBlocks, 1, 14), new Object[] {"xxx", "xxx", "xxx", 'x', new ItemStack(Item.dyePowder, 1, 0)});
        //GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.clrdbricks, 4, 2), new Object[] {Block.brick, new ItemStack(Item.dyePowder, 1, 11)});
        //GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.clrdbricks, 4, 0), new Object[] {Block.brick, new ItemStack(Item.dyePowder, 1, 4)});
        //GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.clrdbricks, 4, 3), new Object[] {Block.brick, new ItemStack(Item.dyePowder, 1, 0)});
        //GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.clrdbricks, 4, 4), new Object[] {Block.brick, new ItemStack(Item.dyePowder, 1, 5)});
        //GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.clrdbricks, 4, 1), new Object[] {Block.brick, new ItemStack(Item.dyePowder, 1, 2)});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.DraviteBlade, 1), new Object[] {" y ", " y ", " x ", 'y', TwilightItemHelper.DraviteChunk, 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.DraviteBlitz, 1), new Object[] {"y y", "y y", "yyy", 'y', TwilightItemHelper.DraviteChunk});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.DravitePickaxe, 1), new Object[] {"yyy", " x ", " x ", 'y', TwilightItemHelper.DraviteChunk, 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.DraviteAxe, 1), new Object[] {"yy ", "yx ", " x ", 'y', TwilightItemHelper.DraviteChunk, 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.DraviteShovel, 1), new Object[] {" y ", " x ", " x ", 'y', TwilightItemHelper.DraviteChunk, 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.DraviteBow, 1), new Object[] {" yx", "y x", " yx", 'y', TwilightItemHelper.DraviteChunk, 'x', Item.silk});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.DravitePhaser, 1), new Object[] {" y ", "yyy", " x ", 'y', TwilightItemHelper.DraviteChunk, 'x', Item.stick});
        GameRegistry.addShapelessRecipe(new ItemStack(TwilightItemHelper.DraviteSlicer, 40), new Object[] {TwilightItemHelper.DraviteGem});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.DraviteHelmet, 1), new Object[] {"yyy", "y y", 'y', TwilightItemHelper.DraviteChunk});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.DraviteChest, 1), new Object[] {"y y", "yyy", "yyy", 'y', TwilightItemHelper.DraviteChunk});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.Dravitelegs, 1), new Object[] {"yyy", "y y", "y y", 'y', TwilightItemHelper.DraviteChunk});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.DraviteBoots, 1), new Object[] {"y y", "y y", 'y', TwilightItemHelper.DraviteChunk});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.DraviteChunk, 1), new Object[] {"yyy", "y y", "y y", 'y', TwilightItemHelper.DraviteGem});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.DraviteGem, 1), new Object[] {"yyy", 'y', TwilightItemHelper.DraviteFragments});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.AzuriteBlade, 1), new Object[] {" y ", " y ", " x ", 'y', TwilightItemHelper.AzuriteChunk, 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.AzuriteBlitz, 1), new Object[] {"y y", "y y", "yyy", 'y', TwilightItemHelper.AzuriteChunk});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.AzuritePickaxe, 1), new Object[] {"yyy", " x ", " x ", 'y', TwilightItemHelper.AzuriteChunk, 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.AzuriteAxe, 1), new Object[] {"yy ", "yx ", " x ", 'y', TwilightItemHelper.AzuriteChunk, 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.AzuriteShovel, 1), new Object[] {" y ", " x ", " x ", 'y', TwilightItemHelper.AzuriteChunk, 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.AzuriteBow, 1), new Object[] {" yx", "y x", " yx", 'y', TwilightItemHelper.AzuriteChunk, 'x', Item.silk});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.AzuritePhaser, 1), new Object[] {" y ", "yyy", " x ", 'y', TwilightItemHelper.AzuriteChunk, 'x', Item.stick});
        GameRegistry.addShapelessRecipe(new ItemStack(TwilightItemHelper.AzuriteSlicer, 40), new Object[] {TwilightItemHelper.AzuriteGem});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.AzuriteHelmet, 1), new Object[] {"yyy", "y y", 'y', TwilightItemHelper.AzuriteChunk});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.AzuriteChest, 1), new Object[] {"y y", "yyy", "yyy", 'y', TwilightItemHelper.AzuriteChunk});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.Azuritelegs, 1), new Object[] {"yyy", "y y", "y y", 'y', TwilightItemHelper.AzuriteChunk});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.AzuriteBoots, 1), new Object[] {"y y", "y y", 'y', TwilightItemHelper.AzuriteChunk});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.AzuriteChunk, 1), new Object[] {"yyy", "y y", "y y", 'y', TwilightItemHelper.AzuriteGem});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.AzuriteGem, 1), new Object[] {"yyy", 'y', TwilightItemHelper.AzuriteFragments});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.UviteBlade, 1), new Object[] {" y ", " y ", " x ", 'y', TwilightItemHelper.UviteChunk, 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.UviteBlitz, 1), new Object[] {"y y", "y y", "yyy", 'y', TwilightItemHelper.UviteChunk});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.UvitePickaxe, 1), new Object[] {"yyy", " x ", " x ", 'y', TwilightItemHelper.UviteChunk, 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.UviteAxe, 1), new Object[] {"yy ", "yx ", " x ", 'y', TwilightItemHelper.UviteChunk, 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.UviteShovel, 1), new Object[] {" y ", " x ", " x ", 'y', TwilightItemHelper.UviteChunk, 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.UviteBow, 1), new Object[] {" yx", "y x", " yx", 'y', TwilightItemHelper.UviteChunk, 'x', Item.silk});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.UvitePhaser, 1), new Object[] {" y ", "yyy", " x ", 'y', TwilightItemHelper.UviteChunk, 'x', Item.stick});
        GameRegistry.addShapelessRecipe(new ItemStack(TwilightItemHelper.UviteSlicer, 40), new Object[] {TwilightItemHelper.UviteGem});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.UviteHelmet, 1), new Object[] {"yyy", "y y", 'y', TwilightItemHelper.UviteChunk});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.UviteChest, 1), new Object[] {"y y", "yyy", "yyy", 'y', TwilightItemHelper.UviteChunk});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.Uvitelegs, 1), new Object[] {"yyy", "y y", "y y", 'y', TwilightItemHelper.UviteChunk});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.UviteBoots, 1), new Object[] {"y y", "y y", 'y', TwilightItemHelper.UviteChunk});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.UviteChunk, 1), new Object[] {"yyy", "y y", "y y", 'y', TwilightItemHelper.UviteGem});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.UviteGem, 1), new Object[] {"yyy", 'y', TwilightItemHelper.UviteFragments});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.MythrilBlade, 1), new Object[] {" y ", " y ", " x ", 'y', TwilightItemHelper.MythrilChunk, 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.MythrilBlitz, 1), new Object[] {"y y", "y y", "yyy", 'y', TwilightItemHelper.MythrilChunk});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.MythrilPickaxe, 1), new Object[] {"yyy", " x ", " x ", 'y', TwilightItemHelper.MythrilChunk, 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.MythrilAxe, 1), new Object[] {"yy ", "yx ", " x ", 'y', TwilightItemHelper.MythrilChunk, 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.MythrilShovel, 1), new Object[] {" y ", " x ", " x ", 'y', TwilightItemHelper.MythrilChunk, 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.MythrilBow, 1), new Object[] {" yx", "y x", " yx", 'y', TwilightItemHelper.MythrilChunk, 'x', Item.silk});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.MythrilPhaser, 1), new Object[] {" y ", "yyy", " x ", 'y', TwilightItemHelper.MythrilChunk, 'x', Item.stick});
        GameRegistry.addShapelessRecipe(new ItemStack(TwilightItemHelper.MythrilSlicer, 40), new Object[] {TwilightItemHelper.MythrilGem});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.MythrilHelmet, 1), new Object[] {"yyy", "y y", 'y', TwilightItemHelper.MythrilChunk});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.MythrilChest, 1), new Object[] {"y y", "yyy", "yyy", 'y', TwilightItemHelper.MythrilChunk});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.Mythrillegs, 1), new Object[] {"yyy", "y y", "y y", 'y', TwilightItemHelper.MythrilChunk});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.MythrilBoots, 1), new Object[] {"y y", "y y", 'y', TwilightItemHelper.MythrilChunk});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.MythrilChunk, 1), new Object[] {"yyy", "y y", "y y", 'y', TwilightItemHelper.MythrilGem});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.MythrilGem, 1), new Object[] {"yyy", 'y', TwilightItemHelper.MythrilFragments});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.AugiteBlade, 1), new Object[] {" y ", " y ", " x ", 'y', TwilightItemHelper.AugiteChunk, 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.AugiteBlitz, 1), new Object[] {"y y", "y y", "yyy", 'y', TwilightItemHelper.AugiteChunk});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.AugitePickaxe, 1), new Object[] {"yyy", " x ", " x ", 'y', TwilightItemHelper.AugiteChunk, 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.AugiteAxe, 1), new Object[] {"yy ", "yx ", " x ", 'y', TwilightItemHelper.AugiteChunk, 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.AugiteShovel, 1), new Object[] {" y ", " x ", " x ", 'y', TwilightItemHelper.AugiteChunk, 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.AugiteBow, 1), new Object[] {" yx", "y x", " yx", 'y', TwilightItemHelper.AugiteChunk, 'x', Item.silk});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.AugitePhaser, 1), new Object[] {" y ", "yyy", " x ", 'y', TwilightItemHelper.AugiteChunk, 'x', Item.stick});
        GameRegistry.addShapelessRecipe(new ItemStack(TwilightItemHelper.AugiteSlicer, 40), new Object[] {TwilightItemHelper.AugiteGem});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.AugiteHelmet, 1), new Object[] {"yyy", "y y", 'y', TwilightItemHelper.AugiteChunk});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.AugiteChest, 1), new Object[] {"y y", "yyy", "yyy", 'y', TwilightItemHelper.AugiteChunk});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.Augitelegs, 1), new Object[] {"yyy", "y y", "y y", 'y', TwilightItemHelper.AugiteChunk});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.AugiteBoots, 1), new Object[] {"y y", "y y", 'y', TwilightItemHelper.AugiteChunk});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.AugiteChunk, 1), new Object[] {"yyy", "y y", "y y", 'y', TwilightItemHelper.AugiteGem});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.AugiteGem, 1), new Object[] {"yyy", 'y', TwilightItemHelper.AugiteFragments});
        GameRegistry.addShapelessRecipe(new ItemStack(TwilightItemHelper.DraviteFragments, 1), new Object[]{TwilightItemHelper.DraviteSoul});
        GameRegistry.addShapelessRecipe(new ItemStack(TwilightItemHelper.AzuriteFragments, 1), new Object[]{TwilightItemHelper.AzuriteSoul});
        GameRegistry.addShapelessRecipe(new ItemStack(TwilightItemHelper.UviteFragments, 1), new Object[]{TwilightItemHelper.UviteSoul});
        GameRegistry.addShapelessRecipe(new ItemStack(TwilightItemHelper.MythrilFragments, 1), new Object[]{TwilightItemHelper.MythrilSoul});
        GameRegistry.addShapelessRecipe(new ItemStack(TwilightItemHelper.AugiteFragments, 1), new Object[]{TwilightItemHelper.AugiteSoul});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.slimeLight, 1), new Object[] {"xxx", "xyx", "xxx", 'x', Item.ingotIron, 'y', Item.slimeBall});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.rupeeLamp, 1), new Object[] {"xxx", "xyx", "xzx", 'x', Item.ingotIron, 'y', OverworldItemHelper.rupee, 'z', Block.glowStone});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.aquaLamp, 1), new Object[] {"xxx", "xyx", "xxx", 'x', Item.ingotIron, 'y', Item.bucketWater});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.blazicLamp, 1), new Object[] {"xxx", "xyx", "xxx", 'x', Item.ingotIron, 'y', Item.blazeRod});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.drakenLamp, 1), new Object[] {"xxx", "zyz", "xxx", 'x', Item.ingotIron, 'y', Item.bucketLava, 'z', Block.blockGold});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.arlemiteLamp, 1), new Object[] {"xxx", "xyx", "xzx", 'x', Item.ingotIron, 'y', OverworldItemHelper.arlemite, 'z', Block.glowStone});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.enderLamp, 1), new Object[] {"xxx", "xyx", "xxx", 'x', Item.ingotIron, 'y', Item.eyeOfEnder});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.krakenLamp, 1), new Object[] {"xxx", "xyx", "xxx", 'x', Item.ingotIron, 'y', OverworldItemHelper.krakenSkin});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.lavaLamp, 1), new Object[] {"xxx", "xyx", "xxx", 'x', Item.ingotIron, 'y', Item.bucketLava});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.milkyLamp, 1), new Object[] {"xxx", "xyx", "xxx", 'x', Item.ingotIron, 'y', Item.bucketMilk});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.glowingstaircase, 1), new Object[] {"  x", " xx", "xxx", 'x', Item.lightStoneDust});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.bluetorch, 1), new Object[] {" y ", "xxx", 'x', OverworldItemHelper.aquaticBlazeRod, 'y', Item.stick});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.bluecrystalline, 1), new Object[] {"xxx", "xyx", "xxx", 'x', Item.ingotIron, 'y', Item.diamond});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldItemHelper.redcrystalline, 1), new Object[] {Block.glowStone, OverworldItemHelper.moltenStone});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldItemHelper.bluecrystalline, 1), new Object[] {Block.glowStone, OverworldItemHelper.blueFireStone});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.miniBricks, 4, 4), new Object[] {Block.stoneBrick, Block.stoneBrick, Block.stoneBrick, Block.stoneBrick, Block.stoneBrick, Block.stoneBrick, Block.stoneBrick, Block.stoneBrick, Block.stoneBrick});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.miniBricks, 1, 0), new Object[] {new ItemStack(OverworldBlockHelper.miniBricks, 1, 4), OverworldItemHelper.rupee});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.miniBricks, 1, 1), new Object[] {new ItemStack(OverworldBlockHelper.miniBricks, 1, 4), OverworldItemHelper.realmite});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.miniBricks, 1, 2), new Object[] {new ItemStack(OverworldBlockHelper.miniBricks, 1, 4), OverworldItemHelper.arlemite});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.miniBricks, 1, 5), new Object[] {new ItemStack(OverworldBlockHelper.miniBricks, 1, 4), OverworldItemHelper.glowingGem});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.miniBricks, 1, 6), new Object[] {new ItemStack(OverworldBlockHelper.miniBricks, 1, 4), OverworldItemHelper.netheriteBar});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.miniBricks, 1, 8), new Object[] {new ItemStack(OverworldBlockHelper.miniBricks, 1, 4), Block.bedrock});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.spiderpumpkin, 1), new Object[] {"xxx", "xyx", "xxx", 'x', Item.silk, 'y', Block.pumpkin});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.enderpumpkin, 1), new Object[] {"xxx", "xyx", "xxx", 'x', Item.enderPearl, 'y', Block.pumpkin});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.creeperpumpkin, 1), new Object[] {"xxx", "xyx", "xxx", 'x', Item.gunpowder, 'y', Block.pumpkin});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.skeletonpumpkin, 1), new Object[] {"xxx", "xyx", "xxx", 'x', Item.bone, 'y', Block.pumpkin});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.blazepumpkin, 1), new Object[] {"xxx", "xyx", "xxx", 'x', Item.blazeRod, 'y', Block.pumpkin});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.rainbowWool, 1), new Object[] {new ItemStack(Block.cloth, 1, 1), new ItemStack(Block.cloth, 1, 14), new ItemStack(Block.cloth, 1, 4), new ItemStack(Block.cloth, 1, 5), new ItemStack(Block.cloth, 1, 9), new ItemStack(Block.cloth, 1, 11), new ItemStack(Block.cloth, 1, 10)});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.lavabricks, 4), new Object[] {Block.stoneBrick, Block.stoneBrick, Block.stoneBrick, Item.bucketLava});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.waterstone, 4), new Object[] {Block.stone, Block.stone, Block.stone, Item.bucketWater});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.darkstairs, 4), new Object[] {"  x", " xx", "xxx", 'x', OverworldBlockHelper.darkbricks,});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.arlemitestairs, 4), new Object[] {"  x", " xx", "xxx", 'x', OverworldBlockHelper.arlemitebricks,});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.ironstairs, 4), new Object[] {"  x", " xx", "xxx", 'x', OverworldBlockHelper.ironbricks,});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.goldstairs, 4), new Object[] {"  x", " xx", "xxx", 'x', OverworldBlockHelper.goldbricks,});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.sandstairs, 4), new Object[] {"  x", " xx", "xxx", 'x', Block.sand,});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.redstonestairs, 4), new Object[] {"  x", " xx", "xxx", 'x', OverworldBlockHelper.redstonebricks,});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.purplebrickstairs, 4), new Object[] {"  x", " xx", "xxx", 'x', OverworldBlockHelper.purplebricks,});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.milkstonestairs, 4), new Object[] {"  x", " xx", "xxx", 'x', OverworldBlockHelper.milkStone,});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.milkstonebricksstairs, 4), new Object[] {"  x", " xx", "xxx", 'x', OverworldBlockHelper.milkstonebricks,});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.lapisstairs, 4), new Object[] {"  x", " xx", "xxx", 'x', OverworldBlockHelper.lapisbricks,});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.greenbricksstairs, 4), new Object[] {"  x", " xx", "xxx", 'x', OverworldBlockHelper.greenbricks,});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.aquatonicbricks, 4), new Object[] {OverworldItemHelper.aquaBall, Block.stoneBrick, Block.stoneBrick, Block.stoneBrick});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.arlemitebricks, 10), new Object[] {"xyx", "yxy", "xyx", 'x', OverworldItemHelper.arlemite, 'y', Block.stoneBrick});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.darkplate, 1), new Object[] {"xx", 'x', OverworldBlockHelper.darkbricks,});
        //Items
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldItemHelper.krakenSkin, 1), new Object[] {OverworldItemHelper.krakenScale, OverworldItemHelper.krakenScale});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldItemHelper.aquaticBlazeRod, 1), new Object[] {Item.blazeRod, OverworldItemHelper.aquaBall});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.aquaBall, 1), new Object[] {"wsw", "wkw", "wsw", 'w', Item.bucketWater, 's', Item.slimeBall, 'k', OverworldItemHelper.krakenSkin});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.chisel, 2), new Object[] {" x ", " y ", 'y', Item.stick, 'x', Item.ingotIron});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldItemHelper.healingStone, 1), new Object[] {Item.magmaCream, OverworldItemHelper.purpleBlaze, OverworldItemHelper.glowingGem});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.netheriteChunk, 1), new Object[] {" x ", "xxx", " x ", 'x', OverworldItemHelper.netheriteBar});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldItemHelper.shadowBar, 1), new Object[] {OverworldItemHelper.arlemite, OverworldItemHelper.rupee});
        //2.0
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.mailStrom, 1), new Object[] {"xxx", "xyx", "xxx", 'x', OverworldItemHelper.purpleBlaze, 'y', Item.book});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldItemHelper.shuriken, 4), new Object[] {Item.ingotIron});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldItemHelper.vialStorm, 4), new Object[] {OverworldItemHelper.shuriken, OverworldItemHelper.shuriken, OverworldItemHelper.shuriken, OverworldItemHelper.shuriken, OverworldItemHelper.jungleShard});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.shadowBow, 1), new Object[] {" xy", "x y", " xy", 'x', OverworldItemHelper.shadowBar, 'y', Item.silk});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.infernoBow, 1), new Object[] {" xy", "x y", " xy", 'x', OverworldItemHelper.moltenStone, 'y', Item.blazePowder});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.poisonBow, 1), new Object[] {" xy", "x y", " xy", 'x', OverworldItemHelper.jungleStone, 'y', Item.silk});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.bluefirebow, 1), new Object[] {" xy", "x y", " xy", 'x', OverworldItemHelper.aquaticBlazeRod, 'y', OverworldItemHelper.blueFireStone});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldItemHelper.hellStoneIngot, 1), new Object[] {OverworldItemHelper.shadowBar, OverworldItemHelper.netheriteChunk});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.jungleStone, 1), new Object[] {"xxx", "xxx", "xxx", 'x', OverworldItemHelper.jungleShard});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.divineStone, 1), new Object[] {"xxx", "xxx", "xxx", 'x', OverworldItemHelper.divineShard});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.moltenStone, 1), new Object[] {"xxx", "xxx", "xxx", 'x', OverworldItemHelper.moltenShard});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.shadowStone, 1), new Object[] {"xxx", "xxx", "xxx", 'x', OverworldItemHelper.shadowBar});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.spikes, 1), new Object[] {"x x", " x ", "x x", 'x', Item.ingotIron});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.DivinePickaxe, 1), new Object[] {"xxx", " y ", " y ", 'x', OverworldItemHelper.divineStone, 'y', OverworldItemHelper.shadowBar});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.DivineAxe, 1), new Object[] {"xx ", "xy ", " y ", 'x', OverworldItemHelper.divineStone, 'y', OverworldItemHelper.shadowBar});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.DivineShovel, 1), new Object[] {" x ", " y ", " y ", 'x', OverworldItemHelper.divineStone, 'y', OverworldItemHelper.shadowBar});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldItemHelper.tomatoSeeds, 4), new Object[] {OverworldItemHelper.tomato});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldItemHelper.whiteMushroomSeeds, 4), new Object[] {OverworldItemHelper.whiteMushroom});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.shadowHelmet, 1), new Object[] {"xxx", "x x", 'x', OverworldItemHelper.shadowStone});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.shadowBody, 1), new Object[] {"x x", "xxx", "xxx", 'x', OverworldItemHelper.shadowStone});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.shadowLegs, 1), new Object[] {"xxx", "x x", "x x", 'x', OverworldItemHelper.shadowStone});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.shadowBoots, 1), new Object[] {"x x", "x x", 'x', OverworldItemHelper.shadowStone});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.divineHelm, 1), new Object[] {"xxx", "x x", 'x', OverworldItemHelper.divineStone});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.divineBody, 1), new Object[] {"x x", "xxx", "xxx", 'x', OverworldItemHelper.divineStone});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.divineLegs, 1), new Object[] {"xxx", "x x", "x x", 'x', OverworldItemHelper.divineStone});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.divineBoots, 1), new Object[] {"x x", "x x", 'x', OverworldItemHelper.divineStone});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.angelicHelmet, 1), new Object[] {"yyy", "x x", 'x', OverworldItemHelper.iceStone, 'y', OverworldItemHelper.blueFireStone});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.angelicBody, 1), new Object[] {"y y", "yyy", "xxx", 'x', OverworldItemHelper.iceStone, 'y', OverworldItemHelper.blueFireStone});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.angelicLegs, 1), new Object[] {"yyy", "x x", "x x", 'x', OverworldItemHelper.iceStone, 'y', OverworldItemHelper.blueFireStone});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.angelicBoots, 1), new Object[] {"y y", "x x", 'x', OverworldItemHelper.iceStone, 'y', OverworldItemHelper.blueFireStone});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.watcherSpawn, 1), new Object[] {" x ", "zyz", " z ", 'y', OverworldItemHelper.watcherEye, 'x', OverworldItemHelper.hellStoneIngot, 'z', OverworldItemHelper.moltenStone});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.ayeracoSpawner, 1), new Object[] {" x ", "zyz", " z ", 'y', Item.eyeOfEnder, 'x', OverworldItemHelper.hellStoneIngot, 'z', OverworldItemHelper.enderStone});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.mysteriousClock, 1), new Object[] {" x ", "zyz", " z ", 'x', OverworldItemHelper.hellStoneIngot, 'y', Item.pocketSundial, 'z', OverworldItemHelper.corruptedStone});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.enderStone, 1), new Object[] {"xxx", "xxx", "xxx", 'x', OverworldItemHelper.enderShard});
        GameRegistry.addSmelting(OverworldBlockHelper.realmiteore.blockID, new ItemStack(OverworldItemHelper.realmiteIngot, 1), 0.7F);
        GameRegistry.addSmelting(OverworldBlockHelper.bloodGemOre.blockID, new ItemStack(OverworldItemHelper.glowingGem, 1), 1.0F);
        GameRegistry.addSmelting(OverworldBlockHelper.arlemiteore.blockID, new ItemStack(OverworldItemHelper.arlemite, 1), 3.0F);
        GameRegistry.addSmelting(OverworldBlockHelper.rupeeore.blockID, new ItemStack(OverworldItemHelper.rupee, 1), 3.0F);
        GameRegistry.addSmelting(OverworldBlockHelper.netheriteore.blockID, new ItemStack(OverworldItemHelper.netheriteBar, 1), 1.0F);
        GameRegistry.addSmelting(TwilightBlockHelper.DraviteOre.blockID, new ItemStack(TwilightItemHelper.DraviteFragments, 1), 1.0F);
        GameRegistry.addSmelting(TwilightBlockHelper.AzuriteOre.blockID, new ItemStack(TwilightItemHelper.AzuriteFragments, 1), 1.0F);
        GameRegistry.addSmelting(TwilightBlockHelper.UviteOre.blockID, new ItemStack(TwilightItemHelper.UviteFragments, 1), 1.0F);
        GameRegistry.addSmelting(TwilightBlockHelper.MythrilOre.blockID, new ItemStack(TwilightItemHelper.MythrilFragments, 1), 1.0F);
        GameRegistry.addSmelting(TwilightBlockHelper.AugiteOre.blockID, new ItemStack(TwilightItemHelper.AugiteFragments, 1), 1.0F);
        GameRegistry.addSmelting(TwilightItemHelper.DraviteFragments.itemID, new ItemStack(TwilightItemHelper.DraviteSparkles, 1), 1.0F);
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.realmiteLamp, 1), new Object[] {"xxx", "xyx", "xzx", 'x', Item.ingotIron, 'y', OverworldItemHelper.realmiteIngot, 'z', Block.glowStone});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.diamondLamp, 1), new Object[] {"xxx", "xyx", "xzx", 'x', Item.ingotIron, 'y', Item.diamond, 'z', Block.glowStone});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.goldenLamp, 1), new Object[] {"xxx", "xyx", "xzx", 'x', Item.ingotIron, 'y', Item.ingotGold, 'z', Block.glowStone});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.redstoneOreLamp, 1), new Object[] {"xxx", "xyx", "xzx", 'x', Item.ingotIron, 'y', Item.redstone, 'z', Block.glowStone});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.lapizLamp, 1), new Object[] {"xxx", "xyx", "xzx", 'x', Item.ingotIron, 'y', new ItemStack(Item.dyePowder, 1, 4), 'z', Block.glowStone});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.netheriteLamp, 1), new Object[] {"xxx", "xyx", "xzx", 'x', Item.ingotIron, 'y', OverworldItemHelper.netheriteBar, 'z', Block.glowStone});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.greenTorch, 4), new Object[] {" x ", " y ", 'x', TwilightItemHelper.DraviteFragments, 'y', Item.stick});
        GameRegistry.addRecipe(new ItemStack(TwilightBlockHelper.DraviteChest, 1), new Object[] {"xxx", "x x", "xxx", 'x', TwilightItemHelper.DraviteFragments});
        GameRegistry.addRecipe(new ItemStack(TwilightBlockHelper.UviteRail, 4), new Object[] {"x x", "xxx", "x x", 'x', TwilightItemHelper.UviteFragments});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.redWood, 2), new Object[] {new ItemStack(Item.dyePowder, 1, 1), Block.wood});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.purpleWood, 2), new Object[] {new ItemStack(Item.dyePowder, 1, 5), Block.wood});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.greenWood, 2), new Object[] {new ItemStack(Item.dyePowder, 1, 2), Block.wood});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.yellowWood, 2), new Object[] {new ItemStack(Item.dyePowder, 1, 11), Block.wood});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.whiteWood, 2), new Object[] {new ItemStack(Item.dyePowder, 1, 15), Block.wood});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.blueWood, 2), new Object[] {new ItemStack(Item.dyePowder, 1, 4), Block.wood});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.stoneFence, 2), new Object[] {"xxx", "xxx", 'x', OverworldBlockHelper.darkbricks});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.woodFence, 2), new Object[] {"xxx", "xxx", 'x', Block.wood});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.lightStone, 1), new Object[] {"xxx", "xxx", "xxx", 'x', Block.glowStone});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.purplestone, 1), new Object[] {"xxx", "xyx", "xxx", 'x', new ItemStack(Item.dyePowder, 1, 4), 'y', OverworldBlockHelper.redstoneBlockOn});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.steel, 5, 13), new Object[] {"xxx", "xyx", "xxx", 'x', new ItemStack(Block.cloth, 1, 14), 'y', new ItemStack(Block.cloth, 1, 4)});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.mud, 5), new Object[] {"xxx", "xyx", "xxx", 'x', Block.dirt, 'y', Item.bucketWater});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.yellowCrystalline, 2), new Object[] {Block.glowStone, OverworldItemHelper.divineStone});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.greenCrystalline, 2), new Object[] {Block.glowStone, OverworldItemHelper.jungleStone});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.orangeCrystalline, 2), new Object[] {Block.glowStone, OverworldItemHelper.iceStone});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.purpleCrystalline, 2), new Object[] {Block.glowStone, OverworldItemHelper.enderStone});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.diamondBricks, 4), new Object[] {Item.diamond, Block.stoneBrick, Block.stoneBrick, Block.stoneBrick});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.enderBricks, 4), new Object[] {Item.enderPearl, Block.stoneBrick, Block.stoneBrick, Block.stoneBrick});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.netheriteBlock, 1), new Object[] {"xxx", "xxx", "xxx", 'x', OverworldItemHelper.netheriteBar});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.arlemiteBlock, 1), new Object[] {"xxx", "xxx", "xxx", 'x', OverworldItemHelper.arlemite});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.rupeeBlock, 1), new Object[] {"xxx", "xxx", "xxx", 'x', OverworldItemHelper.rupee});
        GameRegistry.addRecipe(new ItemStack(TwilightBlockHelper.DraviteBlock, 1), new Object[] {"xxx", "xxx", "xxx", 'x', TwilightItemHelper.DraviteFragments});
        GameRegistry.addRecipe(new ItemStack(TwilightBlockHelper.AzuriteBlock, 1), new Object[] {"xxx", "xxx", "xxx", 'x', TwilightItemHelper.AzuriteFragments});
        GameRegistry.addRecipe(new ItemStack(TwilightBlockHelper.UviteBlock, 1), new Object[] {"xxx", "xxx", "xxx", 'x', TwilightItemHelper.UviteFragments});
        GameRegistry.addRecipe(new ItemStack(TwilightBlockHelper.MythrilBlock, 1), new Object[] {"xxx", "xxx", "xxx", 'x', TwilightItemHelper.MythrilFragments});
        GameRegistry.addRecipe(new ItemStack(TwilightBlockHelper.AugiteBlock, 1), new Object[] {"xxx", "xxx", "xxx", 'x', TwilightItemHelper.AugiteFragments});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.zombiePumpkin, 1), new Object[] {"xxx", "xyx", "xxx", 'y', Block.pumpkin, 'x', Item.rottenFlesh});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.iceManPumpkin, 1), new Object[] {"xxx", "xyx", "xxx", 'y', Block.pumpkin, 'x', OverworldItemHelper.iceShard});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.cyclopsPumpkin, 1), new Object[] {"xxx", "xyx", "xxx", 'y', Block.pumpkin, 'x', Item.ingotGold});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.ghastPumpkin, 1), new Object[] {"xxx", "xyx", "xxx", 'y', Block.pumpkin, 'x', Item.ghastTear});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.frostPumpkin, 1), new Object[] {"xxx", "xyx", "xxx", 'y', Block.pumpkin, 'x', OverworldItemHelper.iceStone});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.enderWatcherPumpkin, 1), new Object[] {"xxx", "xyx", "xxx", 'y', Block.pumpkin, 'x', OverworldItemHelper.enderShard});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.jungleSpiderPumpkin, 1), new Object[] {"xxx", "xyx", "xxx", 'y', Block.pumpkin, 'x', OverworldItemHelper.jungleShard});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.hellSpiderPumpkin, 1), new Object[] {"xxx", "xyx", "xxx", 'y', Block.pumpkin, 'x', OverworldItemHelper.moltenShard});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.glassWhite, 2), new Object[] {new ItemStack(Item.dyePowder, 1, 15), Block.glass});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.glassOrange, 2), new Object[] {new ItemStack(Item.dyePowder, 1, 14), Block.glass});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.glassLightPurple, 2), new Object[] {new ItemStack(Item.dyePowder, 1, 13), Block.glass});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.glassLightBlue, 2), new Object[] {new ItemStack(Item.dyePowder, 1, 12), Block.glass});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.glassYellow, 2), new Object[] {new ItemStack(Item.dyePowder, 1, 11), Block.glass});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.glassLimeGreen, 2), new Object[] {new ItemStack(Item.dyePowder, 1, 10), Block.glass});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.glassPink, 2), new Object[] {new ItemStack(Item.dyePowder, 1, 9), Block.glass});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.glassGray, 2), new Object[] {new ItemStack(Item.dyePowder, 1, 8), Block.glass});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.glassLightGray, 2), new Object[] {new ItemStack(Item.dyePowder, 1, 7), Block.glass});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.glassTeal, 2), new Object[] {new ItemStack(Item.dyePowder, 1, 6), Block.glass});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.glassBlue, 2), new Object[] {new ItemStack(Item.dyePowder, 1, 4), Block.glass});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.glassPurple, 2), new Object[] {new ItemStack(Item.dyePowder, 1, 5), Block.glass});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.glassBrown, 2), new Object[] {new ItemStack(Item.dyePowder, 1, 3), Block.glass});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.glassDirtyGreen, 2), new Object[] {new ItemStack(Item.dyePowder, 1, 2), Block.glass});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.glassRed, 2), new Object[] {new ItemStack(Item.dyePowder, 1, 1), Block.glass});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.glassBlack, 2), new Object[] {new ItemStack(Item.dyePowder, 1, 0), Block.glass});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.paneBlack, 16), new Object[] {"xxx", "xxx", 'x', OverworldBlockHelper.glassBlack});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.paneRed, 16), new Object[] {"xxx", "xxx", 'x', OverworldBlockHelper.glassRed});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.paneDirtyGreen, 16), new Object[] {"xxx", "xxx", 'x', OverworldBlockHelper.glassDirtyGreen});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.paneBrown, 16), new Object[] {"xxx", "xxx", 'x', OverworldBlockHelper.glassBrown});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.panePurple, 16), new Object[] {"xxx", "xxx", 'x', OverworldBlockHelper.glassPurple});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.paneBlue, 16), new Object[] {"xxx", "xxx", 'x', OverworldBlockHelper.glassBlue});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.paneTeal, 16), new Object[] {"xxx", "xxx", 'x', OverworldBlockHelper.glassTeal});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.paneLightGray, 16), new Object[] {"xxx", "xxx", 'x', OverworldBlockHelper.glassLightGray});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.paneGray, 16), new Object[] {"xxx", "xxx", 'x', OverworldBlockHelper.glassGray});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.panePink, 16), new Object[] {"xxx", "xxx", 'x', OverworldBlockHelper.glassPink});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.paneLimeGreen, 16), new Object[] {"xxx", "xxx", 'x', OverworldBlockHelper.glassLimeGreen});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.paneYellow, 16), new Object[] {"xxx", "xxx", 'x', OverworldBlockHelper.glassYellow});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.paneLightBlue, 16), new Object[] {"xxx", "xxx", 'x', OverworldBlockHelper.glassLightBlue});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.paneLightPurple, 16), new Object[] {"xxx", "xxx", 'x', OverworldBlockHelper.glassLightPurple});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.paneOrange, 16), new Object[] {"xxx", "xxx", 'x', OverworldBlockHelper.glassOrange});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.paneWhite, 16), new Object[] {"xxx", "xxx", 'x', OverworldBlockHelper.glassWhite});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.divineRock, 1), new Object[] {OverworldItemHelper.divineShard, Block.stone});
        GameRegistry.addSmelting(Block.pumpkin.blockID, new ItemStack(OverworldItemHelper.pumpkinPie, 1), 0);
        GameRegistry.addSmelting(OverworldItemHelper.empoweredMeatRaw.itemID, new ItemStack(OverworldItemHelper.empoweredMeatCooked, 1), 0);
        
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.twilightClock, 1), new Object[] {"xxx", "xxx", "xxx", 'x', Item.pocketSundial});
        GameRegistry.addShapelessRecipe(new ItemStack(TwilightItemHelper.spawnBase, 1), new Object[] {TwilightItemHelper.MythrilSoul, TwilightItemHelper.MythrilSoul, TwilightItemHelper.MythrilSoul, TwilightItemHelper.MythrilSoul, TwilightItemHelper.MythrilSoul});
        GameRegistry.addShapelessRecipe(new ItemStack(TwilightItemHelper.spawnVamacheron, 1), new Object[] {TwilightItemHelper.spawnBase, TwilightItemHelper.AugiteSoul, TwilightItemHelper.AugiteSoul, TwilightItemHelper.AugiteSoul, TwilightItemHelper.AugiteSoul});
        GameRegistry.addShapelessRecipe(new ItemStack(TwilightItemHelper.spawnKAROT, 1), new Object[] {TwilightItemHelper.spawnBase, TwilightItemHelper.UviteSoul, TwilightItemHelper.AugiteSoul, TwilightItemHelper.AugiteSoul, TwilightItemHelper.MythrilSoul});
        GameRegistry.addShapelessRecipe(new ItemStack(TwilightItemHelper.spawnReyvor, 1), new Object[] {TwilightItemHelper.spawnBase, TwilightItemHelper.AugiteSoul, TwilightItemHelper.AugiteSoul, TwilightItemHelper.DraviteSoul, TwilightItemHelper.AzuriteSoul});
        GameRegistry.addShapelessRecipe(new ItemStack(TwilightItemHelper.spawnDensos, 1), new Object[] {TwilightItemHelper.spawnBase, TwilightItemHelper.UviteSoul, TwilightItemHelper.AugiteSoul, TwilightItemHelper.AzuriteSoul, TwilightItemHelper.MythrilSoul});
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.spawnMamormeter, 1), new Object[] {"xxx", "xyx", "xxx", 'x', OverworldItemHelper.purpleBlaze, 'y', OverworldItemHelper.infernoSword});
        GameRegistry.addShapelessRecipe(new ItemStack(TwilightItemHelper.spawnZichile, 1), new Object[] {TwilightItemHelper.spawnBase, TwilightItemHelper.DraviteSoul, TwilightItemHelper.AugiteSoul, TwilightItemHelper.DraviteSoul, TwilightItemHelper.AzuriteSoul});
        GameRegistry.addShapelessRecipe(new ItemStack(TwilightItemHelper.spawnTwilightDemon, 1), new Object[] {TwilightItemHelper.spawnBase, TwilightItemHelper.AugiteSoul, TwilightItemHelper.AugiteSoul, TwilightItemHelper.AzuriteSoul, TwilightItemHelper.MythrilSoul});
        GameRegistry.addShapelessRecipe(new ItemStack(TwilightItemHelper.spawnSoulFiend, 1), new Object[] {TwilightItemHelper.spawnBase, TwilightItemHelper.UviteSoul, TwilightItemHelper.MythrilSoul, TwilightItemHelper.AzuriteSoul, TwilightItemHelper.DraviteSoul});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.serenadeStriker, 1), new Object[] {"y  ", "yyy", "  y", 'y', Item.diamond});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.serenadeHealth, 1), new Object[] {"y  ", "yyy", "  y", 'y', OverworldItemHelper.netheriteChunk});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.seranadeDeath, 1), new Object[] {"y  ", "yyy", "  y", 'y', OverworldItemHelper.shadowBar});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.growthSerenade, 1), new Object[] {"y  ", "yyy", "  y", 'y', OverworldItemHelper.arlemite});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.frostCannon, 1), new Object[] {"x x", "x x", "yyy", 'y', OverworldItemHelper.iceStone, 'x', OverworldItemHelper.shadowBar});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.ghastCannon, 1), new Object[] {"x x", "x x", "yyy", 'y', OverworldItemHelper.hellStoneIngot, 'x', OverworldItemHelper.shadowBar});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.soundOfMusic, 1), new Object[] {"yyy", "yxy", "yyy", 'y', OverworldItemHelper.purpleBlaze, 'x', Item.silk});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.divinesword, 1), new Object[] {" y ", "yyy", " x ", 'y', OverworldItemHelper.divineStone, 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.poisonSaber, 1), new Object[] {" y ", "zyz", "zxz", 'y', OverworldItemHelper.jungleStone, 'x', Item.stick, 'z', OverworldItemHelper.shadowBar});
        GameRegistry.addRecipe(new ItemStack(Block.bedrock, 1), new Object[] {"yyy", "yxy ", "yyy", 'y', Block.obsidian, 'x', OverworldBlockHelper.rupeeBlock});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.krakenScale, 1), new Object[] {"y y", "y y", "yyy", 'y', new ItemStack(Item.dyePowder, 1, 0)});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.redsandstairs, 4), new Object[] {"  x", " xx", "xxx", 'x', OverworldBlockHelper.redsand});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.skeletonChest, 1), new Object[] {"yyy", "y y", "yyy", 'y', Item.bone});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.deadbridge, 5), new Object[] {"yyy", "y y", "yyy", 'y', Item.lightStoneDust});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.skullTorch, 4), new Object[] {"x", "y", 'y', Item.bone, 'x', Item.coal});
        DivineRPG.RemoveRecipe(new ItemStack(Item.helmetDiamond));
        DivineRPG.RemoveRecipe(new ItemStack(Item.plateDiamond));
        DivineRPG.RemoveRecipe(new ItemStack(Item.legsDiamond));
        DivineRPG.RemoveRecipe(new ItemStack(Item.bootsDiamond));
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.diamondHelmet, 1), new Object[] {"xxx", "x x", 'x', Item.diamond});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.diamondBody, 1), new Object[] {"x x", "xxx", "xxx", 'x', Item.diamond});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.diamondLegs, 1), new Object[] {"xxx", "x x", "x x", 'x', Item.diamond});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.diamondBoots, 1), new Object[] {"x x", "x x", 'x', Item.diamond});
        GameRegistry.addShapelessRecipe(new ItemStack(TwilightItemHelper.DraviteDust, 9), new Object[] {TwilightItemHelper.DraviteFragments});
        GameRegistry.addShapelessRecipe(new ItemStack(TwilightItemHelper.AzuriteDust, 9), new Object[] {TwilightItemHelper.AzuriteFragments});
        GameRegistry.addShapelessRecipe(new ItemStack(TwilightItemHelper.MythrilDust, 9), new Object[] {TwilightItemHelper.MythrilFragments});
        GameRegistry.addShapelessRecipe(new ItemStack(TwilightItemHelper.UviteDust, 9), new Object[] {TwilightItemHelper.UviteFragments});
        GameRegistry.addShapelessRecipe(new ItemStack(TwilightItemHelper.AugiteDust, 9), new Object[] {TwilightItemHelper.AugiteFragments});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.homeTeleporter, 1), new Object[] {"zzz", "zyz", "zzz", 'z', Item.enderPearl, 'y', Item.diamond});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.hotSpike, 1), new Object[] {"y y", " y ", "y y", 'y', OverworldItemHelper.netheriteBar });
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.corruptedPickaxe, 1), new Object[] {"yyy", " x ", " x ", 'y', OverworldItemHelper.corruptedStone , 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.corruptedShovel, 1), new Object[] {" y ", " x ", " x ", 'y', OverworldItemHelper.corruptedStone , 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.corruptedAxe, 1), new Object[] {"yy ", "yx ", " x ", 'y', OverworldItemHelper.corruptedStone , 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.corruptedMaul, 1), new Object[] {"yyy", "yxy", " x ", 'y', OverworldItemHelper.corruptedStone , 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.deathBringer, 1), new Object[] {" y ", "yxy", " x ", 'y', OverworldItemHelper.corruptedStone , 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.superEnchantMentTable, 1), new Object[] {"yyy", "xxx", "xxx", 'y', OverworldItemHelper.corruptedStone , 'x', OverworldBlockHelper.darkstone});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.corruptedStone, 1), new Object[] {"yyy", "yyy", "yyy", 'y', OverworldItemHelper.corruptedShards});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.enderHelmet, 1), new Object[] {"yyy", "y y", 'y', OverworldItemHelper.enderStone});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.enderBody, 1), new Object[] {"y y", "yyy", "yyy", 'y', OverworldItemHelper.enderStone});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.enderBoots, 1), new Object[] {"y y", "y y", 'y', OverworldItemHelper.enderStone});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.enderLegs, 1), new Object[] {"yyy", "y y", "y y", 'y', OverworldItemHelper.enderStone});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.legendaryEnderEye, 1), new Object[] {"yyy", "yyy", "yyy", 'y', OverworldItemHelper.enderStone});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.iceStone, 1), new Object[] {"yyy", "yyy", "yyy", 'y', OverworldItemHelper.iceShard});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.aquastriveHelmet, 1), new Object[] {"yyy", "y y", 'y', OverworldItemHelper.aquaticIngot});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.aquastriveBody, 1), new Object[] {"y y", "yyy", "yyy", 'y', OverworldItemHelper.aquaticIngot});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.aquastriveBoots, 1), new Object[] {"y y", "y y", 'y', OverworldItemHelper.aquaticIngot});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.aquastriveLegs, 1), new Object[] {"yyy", "y y", "y y", 'y', OverworldItemHelper.aquaticIngot});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.moltenSword, 1), new Object[] {" y ", " y ", " x ", 'y', OverworldItemHelper.moltenStone, 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.frostSword, 1), new Object[] {" y ", " y ", " x ", 'y', OverworldItemHelper.iceStone, 'x', Item.stick});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.enderBow, 1), new Object[] {" xz", "y z", " xz", 'x', OverworldItemHelper.enderStone, 'y', OverworldItemHelper.watcherEye, 'z', Item.silk});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.corruptCannon, 1), new Object[] {"yyy", "x x", 'y', OverworldItemHelper.corruptedStone, 'x', Item.stick});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldItemHelper.corruptBullet, 16), new Object[] {OverworldItemHelper.corruptedShards});
        
        GameRegistry.addRecipe(new ItemStack(ArcanaBlockHelper.arcanaPortalFrame, 12), new Object[]{" x ", "yyy", " x ", 'x', OverworldItemHelper.blueFireStone, 'y', Block.blockSteel});
        
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.stainedGlass, 1), new Object[] { "y  ", " x ", "   ", Character.valueOf('x'), Block.glass, Character.valueOf('y'), ArcanaItemHelper.marsineItem });
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.stainedGlass1, 1), new Object[] { " y ", " x ", "   ", Character.valueOf('x'), Block.glass, Character.valueOf('y'), ArcanaItemHelper.marsineItem });
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.stainedGlass2, 1), new Object[] { "   y", " x ", "   ", Character.valueOf('x'), Block.glass, Character.valueOf('y'), ArcanaItemHelper.marsineItem });
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.stainedGlass3, 1), new Object[] { "   ", "yx ", "   ", Character.valueOf('x'), Block.glass, Character.valueOf('y'), ArcanaItemHelper.marsineItem });
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.stainedGlass4, 1), new Object[] { "   ", " xy", "   ", Character.valueOf('x'), Block.glass, Character.valueOf('y'), ArcanaItemHelper.marsineItem });
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.stainedGlass5, 1), new Object[] { "   ", " x ", "y  ", Character.valueOf('x'), Block.glass, Character.valueOf('y'), ArcanaItemHelper.marsineItem });
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.stainedGlass6, 1), new Object[] { "   ", " x ", " y ", Character.valueOf('x'), Block.glass, Character.valueOf('y'), ArcanaItemHelper.marsineItem });
        GameRegistry.addRecipe(new ItemStack(OverworldBlockHelper.stainedGlass7, 1), new Object[] { "   ", " x ", "  y", Character.valueOf('x'), Block.glass, Character.valueOf('y'), ArcanaItemHelper.marsineItem });
    
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.AzuriteArrow, 4), new Object[]{" y ", " x ", " z ", 'y', TwilightItemHelper.AzuriteFragments, 'x', Item.stick, 'z', Item.feather });
        GameRegistry.addRecipe(new ItemStack(TwilightItemHelper.FuryArrow, 4), new Object[]{" y ", " x ", " z ", 'y', TwilightItemHelper.AugiteFragments, 'x', Item.stick, 'z', Item.feather });
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.ironHelmet, 1), new Object[] {"xxx", "x x", 'x', Item.ingotIron});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.ironBody, 1), new Object[] {"x x", "xxx", "xxx", 'x', Item.ingotIron});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.ironLegs, 1), new Object[] {"xxx", "x x", "x x", 'x', Item.ingotIron});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.ironBoots, 1), new Object[] {"x x", "x x", 'x', Item.ingotIron});
        GameRegistry.addRecipe(new ItemStack(OverworldItemHelper.flamingFury, 1), new Object[] {"zxz", "zxz", "zyz", 'z', OverworldItemHelper.infernoSword, 'x', OverworldItemHelper.furyFire, 'y', OverworldItemHelper.shadowBar});
        
        //GameRegistry.addShapelessRecipe(new ItemStack(Block.stone, 9), new Object[]{new ItemStack(OverworldBlockHelper.iceblock, 1, 4)});
        //GameRegistry.addShapelessRecipe(new ItemStack(Block.slowSand, 9), new Object[]{new ItemStack(OverworldBlockHelper.iceblock, 1, 6)});
        //GameRegistry.addShapelessRecipe(new ItemStack(Block.ice, 9), new Object[]{new ItemStack(OverworldBlockHelper.iceblock, 1, 0)});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldItemHelper.rupee, 9), new Object[]{OverworldBlockHelper.rupeeBlock});
        //GameRegistry.addShapelessRecipe(new ItemStack(Block.sand, 9), new Object[]{ new ItemStack(OverworldBlockHelper.iceblock, 1, 5)});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldItemHelper.netheriteBar, 9), new Object[]{OverworldBlockHelper.netheriteBlock});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldItemHelper.arlemite, 9), new Object[]{OverworldBlockHelper.arlemiteBlock});
        //GameRegistry.addShapelessRecipe(new ItemStack(Item.flint, 9), new Object[]{new ItemStack(OverworldBlockHelper.iceblock, 1, 1)});
        //GameRegistry.addShapelessRecipe(new ItemStack(Block.dirt, 9), new Object[]{new ItemStack(OverworldBlockHelper.iceblock, 1, 7)});
        //GameRegistry.addShapelessRecipe(new ItemStack(Block.gravel, 9), new Object[]{new ItemStack(OverworldBlockHelper.iceblock, 1, 2)});
        //GameRegistry.addShapelessRecipe(new ItemStack(Item.coal, 9), new Object[]{new ItemStack(OverworldBlockHelper.iceblock, 1, 3)});
        GameRegistry.addShapelessRecipe(new ItemStack(OverworldBlockHelper.realmiteIngot, 9), new Object[]{OverworldBlockHelper.realmite});
	}
}